### ISSUE TITLE
I got an issue for capture audio from other applications while using GetDisplayMedia for screen sharing in a React Native app.

### ISSUE THREAD

**Issue by priyankgandhi0** [w3c/mediacapture-main#1002]
I've implemented screen sharing using WebRTC in my React Native app, but I'm encountering an issue where the audio from other apps, such as YouTube, is not being captured during screen broadcasting.

Below is the React Native code snippet I'm using for screen sharing:

const screenShareStreamRef = useRef();
    const [screenShareStream, setScreenShareStream] = useState(null);
    const screenShareVideoProducer = useRef();
    const screenShareAudioProducer = useRef();

    let audioTrack, videoTrack, screenstream;
      const startScreenStream = async () => {
        try {
          const displayStream = await mediaDevices.getDisplayMedia({ video: true });
          videoTrack = displayStream.getVideoTracks()[0];
      
          const audioStream = await mediaDevices.getUserMedia({ audio: true });
          audioTrack = audioStream.getAudioTracks()[0];
      
          // Combine video and audio tracks into a single MediaStream
          screenstream = new MediaStream([videoTrack, audioTrack]);
      
          screenShareStreamRef.current = screenstream;
          setScreenShareStream(screenstream);
                
        } catch (error) {
          console.error(error);
        }
    })

For both iOS and Android, I've followed the setup provided in this guide: [Link to the setup guide](https://getstream.io/video/docs/reactnative/advanced/screensharing/setup/react-native/)

Additionally, for iOS, I've added the necessary files into the project, as mentioned in the guide: [Link to the files](https://github.com/GetStream/stream-video-js/tree/main/sample-apps/react-native/dogfood/ios/Broadcast%20Extension/)

I'm looking for insights or solutions on how to capture audio from other apps during screen sharing. Any help would be appreciated. Thank you!

**Comment by eladalon1983** [comment]
You appear to be asking for screen-sharing video (getDisplayMedia) but microphone-derived audio (getUserMedia). You should instead call `getDisplayMedia({video: true, audio: true})`.

Note that availability of video/audio for screen-sharing differs by (1) browser, (2) OS and (3) what the user ends up sharing (tab/window/screen). For example, Chrome does not currently support screen-sharing on Android. Such issues belong in the browser's bug-tracker rather than here, though.

**Comment by alvestrand** [comment]
Closing as "not a problem with the spec".

**Comment by priyankgandhi0** [comment]
@eladalon1983 I have already do this but the same issue.
