### ISSUE TITLE
repo name nit: it'd be nice if this were simply w3c/mediacapture

### ISSUE THREAD

**Issue by hober** [w3c/mediacapture-main#1003]

**Comment by jan-ivar** [comment]
That sounds appealing. I assume we have a way of doing so without breaking old links?

I do notice that for https://w3c.github.io/webrtc-pc the TR version is named https://www.w3.org/TR/webrtc

So that might be another option.

**Comment by jan-ivar** [comment]
To clarify, today we have:
- https://w3c.github.io/mediacapture-main
- https://www.w3.org/TR/mediacapture-streams
- https://wpt.fyi/results/mediacapture-streams

Is the proposal to change all (or just some) to:
- https://w3c.github.io/mediacapture
- https://www.w3.org/TR/mediacapture
- https://wpt.fyi/results/mediacapture

?

**Comment by eladalon1983** [comment]
> I'm not convinced this is worth doing at this point.

I'd also not have suggested this because I think it's more work than it's worth. But if the people who suggested this renaming are motivated enough...

Maybe the inverse is easier? Maybe you could create https://w3c.github.io/mediacapture and have it redirect to https://w3c.github.io/mediacapture-main? (Just a thought.)

**Comment by alvestrand** [comment]
FWIW, Google search for link:https://w3c.github.io/mediacapture-main claims that there are around 5.740 links around the Web to the github.io version of the spec.
And another 7.570 linking to link:https://github.com/webrtc/mediacapture-main

So the redirects will have to stay around forever.

**Comment by dontcallmedom** [comment]
given the expected cost/benefits ratio, we're no longer proposing to proceed with this
