### ISSUE TITLE
Improve description of EventHandler attributes

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-main#103]
Statements of this form are almost completely devoid of information:

> This event handler, of type active, MUST be supported by all objects implementing the MediaStream interface.

A simple rewrite makes a big difference:

>  This event handler, of type active, is fired when the MediaStream becomes active.

And this is throughout.

Chasing down what the conditions are for firing an event is surprisingly difficult without something like this.

As for what I recommend removing, I have no idea why you would have strict normative requirements around support for this and not other things.

**Comment by stefhak** [comment]
Labeling as "Editorial" (no functional changes).
