### ISSUE TITLE
Clarification in "Introduction" section

### ISSUE THREAD

**Issue by stefhak** [w3c/mediacapture-main#108]
From Philippes review:
"It writes “local devices (video cameras, microphones, Web cams) “ and "local devices that can generate multimedia stream data.” and therefore it leads to think it deals only with input devices while it deals also with audio output devices.

The use cases includes "uses, such as real-time communication, recording, and surveillance” and I suggest to include music applications as well to make clear it includes the audio output."
Filed issue to keep track.

**Comment by dontcallmedom** [comment]
I'm not sure which specific text in the spec this comment is referring to - the quoted parts didn’t match anything I could find. /cc @philjoseph

**Comment by philjoseph** [comment]
Indeed Dom**inique** 

My comment was done on based on the latest published version http://www.w3.org/TR/mediacapture-streams/ and not on the latest editor draft and Stefan added it into the issues.

However, I still think the current draft lacks this clarification that it applies to both input and output media devices. For example, in current draft, it is written that 
*This document also defines the MediaStream API, which provides the means to control where multimedia stream data is consumed, and provides some control over the devices that produce the media.* 
There is only mention of devices producing data and not devices that consume data. I think it still worth editorial attention

**Comment by dontcallmedom** [comment]
I've made a pull request (#121) that adds a mention of the device info api for both input and output. If there are other places where changes are needed, could you document them specifically?

Thanks!

**Comment by stefhak** [comment]
Fixed.
