### ISSUE TITLE
Normative text in "Terminology" section

### ISSUE THREAD

**Issue by stefhak** [w3c/mediacapture-main#109]
From Philippes review:
"The paragraph: 

"Other than the source identifier (defined in MediaDeviceInfo.deviceId), other bits of source identity are never directly available to the application until the user agent connects a source to a track. Once a source has been "released" to the application (either via a permissions UI, pre-configured allow-list, or some other release mechanism) the application will be able discover additional source-specific capabilities.“

goes beyond terminology and should come with more details in a further part, such as Section 9. Enumerating Local Media Devices"

Filed issue to keep track.

**Comment by dontcallmedom** [comment]
I think that text has already been moved out of the Terminology section — @philjoseph can you confirm this is now moot?
