### ISSUE TITLE
Explanation of constraints in GUM call

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/mediacapture-main#113]
*Initially [reported in bugzilla](https://www.w3.org/Bugs/Public/show_bug.cgi?id=25771) by Cullen Jennings 2014-05-18 13:47:59 UTC*

step 4 of GMD is really hard to understand what is going on an why

The whole algorithm is hard to convince people it is correct because it is hard to understand what is going on. Prefer to see it rewritten in style of Constrainable section. 

In gum constructor around step 8.5, it seems wrong as the advanced is not a set of key -value pairs but is an array of sets of k/v pairs

Step 10 in gum constructor is wacky - what is this for? need to be more specific than randomly fail if you feel like it 

in step 11 gum constructor, should be clear that call MSUT not return things that are not in the finalSet

**Comment by dontcallmedom** [comment]
*comment by Harald Alvestrand 2014-07-01 08:34:36 UTC*

Step 8 (constraining) needs to be replaced with a reference to the constrainable pattern's algorithm + some text that explains the unique properties of the algorithm in this context (that it's applied to multiple devices at the same time, and results in picking a device).

I think step 10 (Optionally jump to PermissionFailure) was intended to capture the case of a stored denied access. ("No, and don't permit the page to ask again"). The language is quite vague, and can be improved.

In step 11, it does say "MUST include ... from the finalSet". I don't think we an make it much clearer without repeating ourselves.

**Comment by dontcallmedom** [comment]
*Comment by Harald Alvestrand 2014-11-20 15:41:02 UTC*

PR #28 is trying to deal with this section.

**Comment by dontcallmedom** [comment]
now that PR #122 (replacement of PR #28) is merged, can this be closed? @fluffy

**Comment by alvestrand** [comment]
Closing. (Fluffy's on vacation this week)
