### ISSUE TITLE
add hotlinks to the definition of "constraint" under applyConstraints

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#123]
From comments in #122. Specifically, the text under SelectSettings() could use a link to introduce "constraint", since SelectSettings() is a likely jump target.

**Comment by alvestrand** [comment]
@dontcallmedom is this in a PR, or integrated?

**Comment by dontcallmedom** [comment]
oops, I had forgotten to turn it into a pull request, now done. https://github.com/w3c/mediacapture-main/pull/137
