### ISSUE TITLE
Lack of timeout / cancellation leads to UI inconsistencies

### ISSUE THREAD

**Issue by ssokol** [w3c/mediacapture-main#127]
(Long time listener, first time caller - please forgive any errors with regard to process or form.)

The current standard does not appear to include a requirement that implementations provide a means of either:

a) allowing application code to cancel a pending getUserMedia() request, thus removing the permissions UI element from the browser;

or

b) allow application code to set a timeout on the permission request for a getUserMedia() call, thus allowing the request to fail with a timeout error and the browser to withdraw the permission request element.

This leads to an inconsistent state where the application code has given up but with the Navigator UI still displaying the permissions request dialog. This can lead to user confusion.

I realize that to some degree this is a matter of implementation, but I think it would be worthwhile for the standard to include either a means of cancellation or a timeout.

**Comment by stefhak** [comment]
Hi, welcome! A similar subject was recently discussed on the list, starting at http://lists.w3.org/Archives/Public/public-media-capture/2015Jan/0053.html .

We prefer discussions happening there, so I suggest you read up on that thread and then bring this to the list.
Br,
Stefan

**Comment by alvestrand** [comment]
Discussion happened on the list February 19-20. It was suggested (by Anne) that this is part of a larger topic that may need a wider discussion.
When considering the design options, cancellation seemed to be more popular than timeouts.

**Comment by alvestrand** [comment]
A similar subject was discussed in whatwg recently, as pointed out by EKR:

https://github.com/whatwg/fetch/issues/27

The issue seems contentious.

**Comment by alvestrand** [comment]
I'm closing this issue for now. After the release of the CR version of webrtc-pc, we'll look at closed issues labelled "icebox".
