### ISSUE TITLE
 Fitness distance must interpret plain values in advanced array as exact.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#128]
Right now, the advanced array in [Example 3](http://w3c.github.io/mediacapture-main/getusermedia.html#constrainable-interface) does squat, unless it's re-written as:

    var constraints =
    {
      width: {min: 640, ideal: 1280},
      height: {min: 480, ideal: 720},
      advanced: [{width: {exact: 1920}, height: {exact: 1280 } },
                 {aspectRatio: {exact: 1.3333333333} }]
    };

**Comment by dontcallmedom** [comment]
shouldn't `aspectRatio` also use `exact:`?

**Comment by jan-ivar** [comment]
Yes, thanks, I've updated my comment above. The point though, so that there is no confusion, is that we should not alter the example but the algorithm. :-)

**Comment by dontcallmedom** [comment]
oh, good you clarified, I was going to update the example :)

**Comment by alvestrand** [comment]
Sent a note on this (together with #132) to the list. Awaiting comments.

**Comment by stefhak** [comment]
The list input so far (in the thread starting at http://lists.w3.org/Archives/Public/public-media-capture/2015Feb/0018.html) indicate that bare values in the "advanced" section means "exact".

**Comment by burnburn** [comment]
Addressed in commit af37807bb453969d50a0b0aee28851318931eacd
