### ISSUE TITLE
Should attach the media element to the MediaStream object

### ISSUE THREAD

**Issue by qjia7** [w3c/mediacapture-main#134]
In http://w3c.github.io/mediacapture-main/#loading-and-playing-a-mediastream-in-a-media-element, it says 'When the MediaStream state moves from the active to the inactive state, the User Agent MUST raise an ended event on the media element and set its ended attribute to true.' But currently, there is no directly relationship between mediastream and media element. In mediastream, we can control active to inactive and trigger the 'inactive' event. But we can't raise an ended event on the media element. Should we add the 'attach to element algorithm' like mediasource does?
 (http://w3c.github.io/media-source/#mediasource-attach )

**Comment by qjia7** [comment]
Ping @stefhak @alvestrand @dontcallmedom

**Comment by alvestrand** [comment]
The User Agent has access to both the MediaStream and the Media Element.
The Media Element has a direct relationship to the MediaStream: The Media Element's srcObject attribute is set to the MediaStream.
I don't understand the problem (I may be dense).

Could you explain some more why you see this as an issue?

**Comment by qjia7** [comment]
I submit it based on chromium implementation. Currently, <code>srcObject</code> hasn't been supported in chromium.

**Comment by alvestrand** [comment]
OK, then it's not a spec issue. It may be a Chromium issue.
Does Chromium raise the ended event or not? Do you feel like writing a w3c test to verify if it does or not?

**Comment by alvestrand** [comment]
Closing this issue as "not an issue with the specification".
