### ISSUE TITLE
No way to represent a boolean Capability that can be turned on or off

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#138]
The doc in #118 talks about "a microphone that can be opened with echo cancelation turned on or off".

What should getCapabilities() return for such a mic? The document seems to assume:

    { echoCancelation: { min: false, max: true } }

which I think is a great idea!

This requires a spec-change to [ConstrainBooleanParameters](http://w3c.github.io/mediacapture-main/getusermedia.html#dictionary-constrainbooleanparameters-members).

**Comment by dontcallmedom** [comment]
an alternative would be to allow for a sequence of boolean in `ideal` and `exact` as we do for enums; arguably, a boolean is closer to an enum as a model.

**Comment by dontcallmedom** [comment]
(I've prepared a pull request for the min/max proposal, but will hold from submitting it until the alternative approach gets discussed)

**Comment by jan-ivar** [comment]
Good point. We probably shouldn't rely on an understanding of false < true in an API. So:

    { echoCancelation: [false, true] }

seems cleaner (even though parsing is worse). BTW, any progress on what exactly getCapabilities() returns? I had to rely on spec examples to learn whether it should be the above or:

    { echoCancelation: { exact: [false, true] } }

**Comment by alvestrand** [comment]
Ideal makes no sense for getCapabilities, but I see nothing wrong with

echoCancelation: { exact: [false, true] }

as a return value for getCapabilties.
This would require changing the syntax for "exact" in ConstrainBooleanParameter to "boolean or sequence<boolean>".
@adam-be is still working on a WebIDL proposal.

**Comment by jan-ivar** [comment]
It would require more than that, since my reading of the spec right now has both getSettings and getCapabilities returning plain values to mean required, just like in advanced. Are you asking for a change there? That should be discussed separately perhaps. My mistake for bringing it up here.

**Comment by burnburn** [comment]
FWIW, in my mind Boolean has always been a special subset of enum, meaning it's a list with only two values.  I guess that matches the most recent comments above.

**Comment by jan-ivar** [comment]
Works for me as well. I'm also coming around to Harald's point on perhaps having "exact" in ConstrainBooleanParameter, though how I got there is a bit convoluted:

Reason A: I think "ideal' could make a lot of sense in getCapabilities() as a way to learn about things like native resolution, though I've been unsuccessful raising support for that. In any case, I observe that it would be hard to add things like that later if we go with plain values, since users would already be expecting plain values and would need to learn to expect something different. A dictionary on the other hand is easy to extend with future information.

Reason B: It's a bit confounding that values returned in a dictionary may have different meaning if one were to pass it back to the UA. E.g. One might naively expect .applyConstraints(alterSomeValues(getCapabilities())) to do something reasonable, but it wont if we return plain values in getCapabilities() (if we avoid plain values however then it works!)

So @adam-be should we avoid returning plain values in getCapabilities? (we still want plain values in getSettings() I think, though one might make the same argument there).

**Comment by alvestrand** [comment]
Will be solved in #37

**Comment by alvestrand** [comment]
Done.

**Comment by adam-be** [comment]
The current spec says:
sequence<boolean> echoCancellation;

Is that enough or should we add a note that the form should be [true, false]?

**Comment by alvestrand** [comment]
I'd actually prefer [false, true] since I prefer lowest values first, and think of false being smaller than true (old C habits die hard).

Adding a note saying "the UA SHOULD return [false, true]" should be fine.

**Comment by adam-be** [comment]
So should this be a specific note for echoCancellation or is this something general that should go into the Constrainable Pattern section for features that have an "on" and "off" mode, but it's not always the case that you can toggle the setting.

**Comment by jan-ivar** [comment]
What are we solving? Unless it's a MUST, this is useless information, and I don't think we should make it a MUST, so I think we shouldn't mention anything.

**Comment by dontcallmedom** [comment]
@jan-ivar I guess the question is whether the value of track.getCapabilities().echoCancellation[0] is deterministic for a track from a device that supports toggling echo cancellation.
I see no reason why it should not be deterministic, and I agree with @alvestrand that [false, true] sounds like the right value.

I think the right place to specify it is in getusermedia.html#widl-MediaTrackCapabilities-echoCancellation for the time being; it's hard to know how it extends to other capabilities without specific examples, and I don't think we need to determine that now in any case.

**Comment by jan-ivar** [comment]
Doing that would make

    if (track.getCapabilities().echoCancellation[0])

fail for devices that support toggling of echoCancellation. If I were a device I would want to return the default value first, so that people aren't surprised when the unmodified device acts differently than what they learned.
