### ISSUE TITLE
MediaDeviceInfo.label and groupId are unnecessarily nullable

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#141]
[The spec](http://w3c.github.io/mediacapture-main/getusermedia.html#idl-def-MediaDeviceInfo) lists MediaDeviceInfo.label and groupId as nullable:

    interface MediaDeviceInfo {
        readonly    attribute DOMString       deviceId;
        readonly    attribute MediaDeviceKind kind;
        readonly    attribute DOMString?      label;
        readonly    attribute DOMString?      groupId;
    };

But the enumerateDevices algorithm never ever returns null for these (instead it returns empty string). Even the description of label says it returns empty string, so we should remove nullable here.

**Comment by martinthomson** [comment]
Not sure about this.  I think that we should be returning a null when values are not provided.

**Comment by jan-ivar** [comment]
Usually, nullable is interesting when one wants to distinguish between empty string and null. Why would we need that here? Are all cameras with groupId = "" of the same group?

**Comment by martinthomson** [comment]
I contend that relying on reserving a point from the value space of a parameter to designate an exceptional condition is less clear than relying on a `null` value.

**Comment by jan-ivar** [comment]
I disagree that null is outside the value space. This is extending the value space (needlessly).

**Comment by adam-be** [comment]
We use empty string elsewhere when a string has no value (e.g. MediaStreamTtrack.label) so I think that should be the case here as well.

**Comment by adam-be** [comment]
Proposed fix: 79b3de46b6

If we still want to consider moving to a model where null is used instead, please open a new issue/PR to address that.
