### ISSUE TITLE
enumerateDevices' access model is unclear

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#142]
From [the spec](http://w3c.github.io/mediacapture-main/getusermedia.html#methods-2):

> If none of the local devices are attached to an active MediaStreamTrack, let filteredList be a copy of resultList, and all its elements, where the label member is the empty string.

Taken literally, this exposes the label to all concurrently open tabs during active gUM use in *any* tab regardless of site, which is not what we mean, because [it further says](http://w3c.github.io/mediacapture-main/getusermedia.html#access-control-model):

> The algorithm described above means that the access to media device information depends on whether or not permission has been granted to the page's origin to use media devices.

This narrows access down to a page's origin, but is fuzzy about the duration of access, wrt whether access is afforded outside active use (MediaStreamTracks are stopped), or when persistent permission has been (previously) granted.

These statements seem quite contradictory in their description about what matters for access, and neither matches gUM permissions which are afforded, not even per page, but, *per instance* and not per origin (unless permanent access is granted). 

Questions:
1. Open same jsfiddle in two tabs, grant access in one and deny in the other. Who sees label?
2. Open different jsfiddles in two tabs, grant access in one and deny in the other. Who sees label?
3. Stop the MediaStream. Can you still see label?
4. Never start a MediaStream, but persistent permissions were granted on a previous visit. See label?
5. Never start a MediaStream, but persistent permissions were granted on a previous visit to another page on the same host. See label?

**Comment by martinthomson** [comment]
My preference is that labels are visible to:
* windows or tabs that have active streams, or
* origins that have a persistent grant

**Comment by jan-ivar** [comment]
Makes sense to me.

**Comment by jan-ivar** [comment]
Question 6. If the user gives access to a camera but denies to microphones, can the app see labels on mics?

FWIW, what Firefox is implementing is pretty much what Martin says above, with the clarification that no distinction is made between audio and video, i.e. an active stream or persistent permission of either kind lets you see labels for all (both types of) devices.

**Comment by dontcallmedom** [comment]
I've made a pull request towards what I understand the suggest is; the pull request doesn't explicit change anything to answer question #6, because I think the current spec already does it:
since it doesn't say to limit devices by their kind, it defaults to all enumerable media devices.

**Comment by jan-ivar** [comment]
lgtm.
