### ISSUE TITLE
explanation of kind in getSupportedConstraints (DOMString kind);

### ISSUE THREAD

**Issue by fluffy** [w3c/mediacapture-main#147]
The getSupportedConstraints (DOMString kind) takes a kind parameter but it looks like the only place you can figure out what that is used for is by reading the examples.

**Comment by jan-ivar** [comment]
I never understood the point of the *kind* parameter. Why allow a UA to implement something for one kind and not the other? This paremeter has no benefit to users other than creating allowances for UAs and therefore violates the [priority of constituencies](http://www.w3.org/TR/html-design-principles/#priority-of-constituencies) in my mind.

We've failed to break down constraint implementation by kind anyway, as current implementations of screensharing show.
