### ISSUE TITLE
Need to be clear how future extensions add new constraints 

### ISSUE THREAD

**Issue by fluffy** [w3c/mediacapture-main#148]

**Comment by dontcallmedom** [comment]
isn't this something for the IANA registry?

**Comment by jan-ivar** [comment]
Future specifications would presumably use [partial dictionaries](http://heycam.github.io/webidl/#dfn-partial-dictionary) for their WebIDL, and would need to do so for *all four of the dictionaries we just introduced*. If we folded the four dictionaries into one then just one partial dictionary would do.

**Comment by stefhak** [comment]
I think this was addressed by https://github.com/w3c/mediacapture-main/pull/150 which was just merged, so I close this Issue.
