### ISSUE TITLE
html5 player playing remote video

### ISSUE THREAD

**Issue by shtefcs** [w3c/mediacapture-main#154]
Hi there,

I am not sure what this lib is exactly, but I assume it have something with HTML5 player.

My question is it possible to play remote video in html 5 player ?

**Comment by dontcallmedom** [comment]
hi @shtefcs , this repo is not about a library, but is used to develop a new Web standard.

If you have questions about usage of HTML5, I suggest bringing it to another forum, e.g. on stackoverflow.

**Comment by shtefcs** [comment]
Hi @dontcallmedom . I am sorry for being noobish, just came here searching for solution and help. Can you just confirm is this something which can be used for playing remote video in HTML 5 player ?

Peace,

**Comment by dontcallmedom** [comment]
this repo is not a software library, it is a specification for an API that is implemented in browsers. That API gives access to video streams from local cameras. 

Hope this helps

**Comment by shtefcs** [comment]
Yes, it make it clear. Thank you and sorry once again.
