### ISSUE TITLE
Premature optimization in enumerateDevices steps

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#155]
I see no functional impact from this statement:
> If this method has been called previously within this application session, let oldList be the list of MediaDeviceInfo objects that was produced at that call (resultList); otherwise, let oldList be an empty list.

Lets remove it and leave optimizations to implementations.

**Comment by jan-ivar** [comment]
I guess it's there to guard against the steps that follow which dictate device probing in direct response to each enumerateDevices call (a polling model). 

What's odd is that we now also support 'ondeviceschanged' (a push model), making the obvious place to update any global internal list of devices be right before we fire that event.

There's still a reason to build a list uniquely for each (session of an) enumerateDevices call: make the IDs origin-unique, but I'm not sure the amount of CPU needed to do that warrants having the spec optimize around it for us.

I feel there's a better way to word this, but it's escaping me at the moment.

**Comment by alvestrand** [comment]
It's not an optimization, it's an invariant.

The guarantee you get from keeping oldList around is this:

enumerateDevices().then(list => list1 = list);
... time passes ....
enumerateDevices().then(list => list2 = list);

Guarantee:
If <device> is present in both list1 and list2, it has the same deviceId and groupId.

There's even a weird case where it matters more:
If at time 1, a headset was present with no microphone, and at time 2, the headset has grown a microphone (pluggable microphone detectable from browser? Weirder things can happen), you need the oldList to guarantee that the headset and the microphone has the same groupId.

**Comment by jan-ivar** [comment]
Ah, it's to implement the groupId which is not persistent. I didn't read it carefully enough. Thanks for explaining it.
