### ISSUE TITLE
enumerateDevices should be getAll() to match other APIs

### ISSUE THREAD

**Issue by esprehn** [w3c/mediacapture-main#157]
```mediaDevices.getAll()``` is pretty clear and matches other APIs like the Cache API in SW.

**Comment by adam-be** [comment]
I'm unsure of the word "get" here. We don't want to faulty hint that this method "gets" the devices and access to use them (like getUserMedia() does).

**Comment by esprehn** [comment]
Perhaps you want getDevices() or getAvailableDevices() ? Having consistency is important for developer ergonomics. :)

**Comment by jan-ivar** [comment]
@esprehn I think it's the "get" part that's at issue, , not "All". Personally I voted for `devices.enumerate()`.

**Comment by esprehn** [comment]
No other API uses the word enumerate like this. This is a getter, just like cache.getAll() or getPermission(), etc. You could perhaps also just call it list(), but enumerateDevices() is super weird in the platform.

**Comment by alvestrand** [comment]
It's not unheard of. http://www.w3.org/TR/ws-enumeration/#Enumerate was a first hit on googling under w3.org/TR.

**Comment by alvestrand** [comment]
And the corresponding WebMIDI operator is called "requestMIDIAccess"...

http://www.w3.org/TR/webmidi/#requestmidiaccess

**Comment by alvestrand** [comment]
The WG has decided to respond with a proposed resolution to the Last Call comment suggesting "no change". Closing this bug for now; it may be reopened if the LC resolution process warrants reopening.

**Comment by annevk** [comment]
@alvestrand FYI, WS-* is the anti-pattern of standards.
