### ISSUE TITLE
Language does not seem tamper-free

### ISSUE THREAD

**Issue by annevk** [w3c/mediacapture-main#158]
E.g. if I overwrite `MediaStream.prototype.addTrack` does that affect `MediaStream`'s constructor? I think both `addTrack()` and the constructor are meant to invoke a "private" algorithm. This happens throughout the specification.

**Comment by jan-ivar** [comment]
Agree. Would you mind pointing to an example that writes it that way?

**Comment by annevk** [comment]
https://dom.spec.whatwg.org/#dom-node-appendchild refers to an internal "append" algorithm which defers to an internal "pre-insert" algorithm. If you click on the definitions of **append** and **pre-insert** you'll find that there's many places throughout the specification that use these algorithms.

**Comment by adam-be** [comment]
Yes. MediaStream.clone() suffers from the same thing (calling MediaStreamTrack.clone()). Let's do a private algorithm.

**Comment by adam-be** [comment]
Proposed fix: PR #167

**Comment by alvestrand** [comment]
Addressed by #167
