### ISSUE TITLE
MediaStream's active attribute

### ISSUE THREAD

**Issue by annevk** [w3c/mediacapture-main#159]
The link from the constructor to "active" indicates a `MediaStream` state of active/inactive. However, the prose doesn't reference to this as a state but rather as something that is a boolean. This is rather confusing.

**Comment by jan-ivar** [comment]
I gather the prose meant to link to the [#widl-MediaStream-onactive](http://w3c.github.io/mediacapture-main/getusermedia.html#widl-MediaStream-onactive) attribute rather than the state of the same name.

**Comment by annevk** [comment]
I see. That's the same problem as #158. It's best to refer to the internal slots as public members can start throwing and such.

**Comment by adam-be** [comment]
OK. Recap for my own understanding.
Depending on if we refer to the active attribute or the active/inactive concept, we should link consistently.
active attribute: #widl-MediaStream-active
active/inactive concept: #stream-inactive.

**Comment by adam-be** [comment]
Proposed fix: #168

**Comment by alvestrand** [comment]
Closed after merging #168.
