### ISSUE TITLE
MediaStreamTrackEvent's track member is not nullable

### ISSUE THREAD

**Issue by annevk** [w3c/mediacapture-main#160]
Either you need to make this nullable or you need to require the dictionary argument and not give that a default value of null.

**Comment by jan-ivar** [comment]
Can't default a non-nullable to null for sure. Most of this was written before required dictionary arguments (or before knowledge of them at least). Using those here seems appropriate to me FWIW.

I seem to recall a desire in this group (or might have been webrtc) to avoid nullable in events unless it carries meaning to a recipient, or at least I recall us going around a couple of times on that.

**Comment by adam-be** [comment]
It's also strange to have a non-optional dictionary without any required members. The dictionary is required but you can leave it empty.

Out of the two options (nullable or required), is there one that is more common that we should follow?

**Comment by annevk** [comment]
Not required is more common, but only because required is new. I would personally use required on the dictionary member I think since nullable seems rather pointless.

**Comment by alvestrand** [comment]
I like a required dictionary argument (glad to have it).

**Comment by adam-be** [comment]
Proposed fix: #169

**Comment by alvestrand** [comment]
Addressed by #169
