### ISSUE TITLE
Remove "Direct Assignment to Media Elements"

### ISSUE THREAD

**Issue by annevk** [w3c/mediacapture-main#161]
It conflicts with the definition given in the HTML Standard, which also allows for setting a `Blob` object and such. Given that it's integrated there, providing a pointer seems better.

**Comment by adam-be** [comment]
Yes. That's been our intention since hixie offered to spec it up.

**Comment by alvestrand** [comment]
The text in http://www.w3.org/html/wg/drafts/html/master/single-page.html#dom-media-srcobject seems like an appropriate reference. Assigning to Dom as he is the expert on cross-document references.
