### ISSUE TITLE
Please use [Exposed]

### ISSUE THREAD

**Issue by annevk** [w3c/mediacapture-main#163]
That way it is much clearer what is exposed to Window and/or Worker.

**Comment by adam-be** [comment]
I don't see reason not to.

**Comment by alvestrand** [comment]
What is the default exposure if nothing's specified?
It seems we need a decision on what's exposed to Worker; I've been assuming that everything's exposed to Window.

**Comment by alvestrand** [comment]
Note - [Exposed] is not defined in http://www.w3.org/TR/WebIDL/ but is defined in http://heycam.github.io/webidl/#Exposed - so we need to make sure our references point to the right place. (It's not the only new WebIDL feature we depend on, so we should reference the new spec anyway).

**Comment by annevk** [comment]
I would prefer that even the default is explicitly specified. That way it is more clear that you meant the default rather than forgot to mention this.

**Comment by alvestrand** [comment]
Conclusion of list (non)discussion was that we do [Exposed=Window].

**Comment by alvestrand** [comment]
Resolved in #172
