### ISSUE TITLE
Consider specifying a minimum length for deviceId

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-main#173]
In reviewing the Audio Output API, they are attempting to reserve a value for use in APIs that would accept a `deviceId` value.  That is made fraught with the potential for collisions because the definition of `deviceId` doesn't constrain the value-space of the device identifier at all.  A minimum length - or any other sort of constraint on the value-space - would allow the Audio Output API to choose a value that is guaranteed not to collide.

**Comment by alvestrand** [comment]
Having reserved values was one of the parts of the puzzle that I remember discussing with Mozilla folks quite some time ago. Typical approaces involve reserving a character range, a length range or something else for "predefined identifiers".
Would "randomly generated device IDs MUST be at least 8 characters long; if any predefined device IDs are defined by any specification, they MUST be 7 characters or less" suffice?
("default" is 7 characters)

**Comment by martinthomson** [comment]
I have no problem with that.  We'd have to acknowledge that there might be values with reserved semantics, which the spec doesn't have, but that's just typing.

**Comment by jan-ivar** [comment]
Isn't this an overload?

**Comment by alvestrand** [comment]
Conclusion from list discussion seems to be that reserved values are a bad idea.
Filed https://github.com/w3c/mediacapture-output/issues/19 to get the reserved values changed.

**Comment by vivienlacourba** [comment]
Adding link to the June 2015 list discussion: https://lists.w3.org/Archives/Public/public-media-capture/2015Jun/0015.html
