### ISSUE TITLE
Constrainable pattern IDL should pass an IDL validator

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-main#176]
As detailed in LC-3019, the current IDL for the Constrainable pattern doesn't pass an IDL checker.
These types won't be instantiated as-is in a browser anyway, but conformant WebIDL is nice.

Suggest @jan-ivar as the best person to write a PR that accomplishes this.

**Comment by jan-ivar** [comment]
I'm a bit swamped unfortunately. @adam-be any chance you could take this? I merely suggested repeating the pattern we use for `Constraints`: Put in an empty dictionary and call it done.

**Comment by adam-be** [comment]
PR #208 

There are still some WebIDL validation error due to our use of the [Exposed] extended attribute. I've filed a bug on the validator to address that [1].

[1] https://github.com/dontcallmedom/webidl-checker/issues/17

**Comment by adam-be** [comment]
The WebIDL validator bug has been fixed by @dontcallmedom

**Comment by stefhak** [comment]
Fixed via #208
