### ISSUE TITLE
Missing serializer in MediaDeviceInfo

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#178]
[MediaDeviceInfo](http://w3c.github.io/mediacapture-main/getusermedia.html#device-info) could have been a dictionary, but it's not. It's an interface. That's fine, but it is not an *enumerable* interface which seems ironic for a dumb information object. E.g. when I do:

    navigator.mediaDevices.enumerateDevices().then(all => console.log(JSON.stringify(all));

I get:

    [{},{}]

rather than:

    [{"kind":"audioinput","deviceId":"u2AZF5gn1InjquhwEPO9pplZYwjJ8TAn6C66BAkOxK4=","label":"Built-in Microphone","groupId":""},
     {"kind":"videoinput","deviceId":"h6A9f3jGMQufyezzjm97H7s5RA5ssC1CRBpPkS+hoiQ=","label":"FaceTime HD Camera (Built-in)","groupId":""}]"

Intentional or document bug?

**Comment by alvestrand** [comment]
Merged fix in #179.
