### ISSUE TITLE
Switch terminology from "asynchronously" to "in parallel" to follow the HTML standard

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#180]
In algorithms like [getUserMedia](http://w3c.github.io/mediacapture-main/getusermedia.html#dom-mediadevices-getusermedia). See https://github.com/w3ctag/promises-guide/issues/31

**Comment by adam-be** [comment]
I strongly support sticking to the commonly used language here.

**Comment by jan-ivar** [comment]
Which one is that?

**Comment by adam-be** [comment]
To clarify; I think we should follow the guide and use "in parallel".

**Comment by stpeter** [comment]
I'd be happy to submit a PR.

**Comment by alvestrand** [comment]
Fixed.
