### ISSUE TITLE
getUserMedia({ }) should be a TypeError

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#189]
In hindsight, I think it's clear that `getUserMedia({ })` should be a `TypeError` rather than a `NotSupportedError`.

Having `{ lasers: true }` throw `NotSupportedError` may sound good, but gives the wrong impression, as it leads to surprise when `{ lasers: true, audio: true }` succeeds without error.

More importantly, the arrival of the `required` keyword for dictionary members in WebIDL suggests that empty dictionaries in new APIs are more likely to throw `TypeError` than anything else. Even though this `required` keyword wont work in our particular case, who knows, WebIDL may someday add a way to specify mutually-exclusive required members, and we'd wish we'd made this change now.

This also aligns well with the recent move to make this validation synchronous https://github.com/w3c/mediacapture-main/pull/182

**Comment by adam-be** [comment]
I think `TypeError` makes sense when at least one `required` member is present (since it's actually possible to determine that a JavaScript object, missing that member, cannot represent the dictionary type). As you describe, it's a bit trickier in our case since we have an "unconstrained" dictionary.

If we add prose that, along with the dictionary WebIDL, makes up the new definition of the `MediaStreamConstraints` dictionary type, then I think `TypeError` might be appropriate.

**Comment by alvestrand** [comment]
@jan-ivar can you mention this proposal on the list, so that we're sure nobody who cares has an argument they want to make about it?

**Comment by alvestrand** [comment]
Posted on the list June 19.

**Comment by adam-be** [comment]
@jan-ivar, the mutually-exclusive required member feature you mentioned above would be useful for RTCIceCandidate as well. :) Either sdpMLineIndex or sdpMid.

**Comment by jan-ivar** [comment]
@adam-be - for sure. Avoids manual spec prose for errors, which we all know can go wrong, like here: "When constructed, values for candidate and either sdpMid or sdpMLineIndex MUST be provided." in http://w3c.github.io/webrtc-pc/#constructors-2 (using MUST on user rather than UA).

**Comment by adam-be** [comment]
We need to fix that one.

An other example where we would need the mutual exclusive dictionary members: RTCDataChannelInit with its maxPacketLifeTime and maxRetransmits members.

**Comment by adam-be** [comment]
Just before someone else mentions it, for this particular case (MediaStreamConstraints) we would rather need an "at least one of..."-extension rather than a mutual exclusive WebIDL dictionary extension. :)

**Comment by adam-be** [comment]
I've posted a question on the script coord list regarding this.

https://lists.w3.org/Archives/Public/public-script-coord/2015JulSep/0065.html

**Comment by adam-be** [comment]
I've got one reply on the mail to the script coord list. It was from @annevk and he suggests using TypeError

**Comment by adam-be** [comment]
Proposed PR: #189

**Comment by alvestrand** [comment]
Fixed by #239.
