### ISSUE TITLE
Support zoom specification

### ISSUE THREAD

**Issue by owencm** [w3c/mediacapture-main#191]
UAs should allow clients to specify, and dynamically modify a zoom attribute.

With getUserMedia, developers are currently constrained to performing crops and digital zooms after the fact, but they should be able to provide zoom controls to users which takes advantage of the zoom capability provided by the camera.

For example, Android developers are able to do this as follows: http://developer.android.com/reference/android/hardware/Camera.Parameters.html#setZoom(int)

**Comment by alvestrand** [comment]
This may sound like procedural, but the getusermedia spec is currently being cleaned up for final release as CR; we don't really want to add new functionality to it.

Zoom was discussed and put away as "too complex for the first iteration" at the Boston interim, February 2013 - you have to consider things like "how long does it take to move from one zoom state to another?", and "where is the zoom level just now?" - if we want to tackle these issues, we should support the entire pan/tilt/zoom/focus battery of controls.

I suggest you find some more people to work with and try to formulate this as an extension spec.

**Comment by stefhak** [comment]
Closing as there has been no more input. As Harald points out the best path is probably to work on an extension spec.
