### ISSUE TITLE
Support setting focus

### ISSUE THREAD

**Issue by owencm** [w3c/mediacapture-main#192]
UAs should allow clients to control the focusing of the device's camera.

getUserMedia doesn't provide any control to the developer over which parts of the image to focus on. Native platforms enable apps to allow the user to tap on a location on the stream to focus (and often recalculate exposure etc). 

Consider the various controls over focus that Android exposes to native apps:

http://developer.android.com/reference/android/hardware/Camera.Parameters.html#getFocusAreas()
http://developer.android.com/reference/android/hardware/Camera.Parameters.html#getFocusMode()

**Comment by stefhak** [comment]
This kind of functionality should probably go into an extension spec.

**Comment by owencm** [comment]
Do any other extension specs for mediacapature exist today? Is it best to start a thread on public-media-capture to see if I can drum up support for focus/zoom/etc in an extension spec or do you think something else would be more fruitful?

**Comment by stefhak** [comment]
Yes, there is a bunch of extension specs (Recorder, ImageCapture, ScreenCapture, from element). Go to github.com/w3c and search for mediacapture and you'll find them. I think ImageCapture might be good to look into, but then I suggest you start an email thread. It is important to get the use cases described in the mail.

**Comment by stefhak** [comment]
@owencm I'm closing this Issue now. Some feedback and advice on how to move forward is given above.
