### ISSUE TITLE
Add a channel count constraint to spec

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-main#197]
Proposal from Joe Berkovitz on behalf of the Audio WG.

Summary:

The proposed change will associate a channel count with an audio MediaTrack, allowing both device discovery (via constraints) and device description (via capabilities and settings) to account for the number of audio channels in a track.

Rationale:

Channel counts are fundamental descriptors of audio tracks, as width or height are fundamental to video tracks (for input, at any rate). Knowing the potential and real channel counts of device streams are essential for audio-based apps to present or make meaningful choices between devices, and to adjust an application's behavior to best fit a given device.

The Audio WG did consider using an enumerated type for channel layouts (e.g. "mono", "5.1", etc.) but has settled on channel counts because they are always knowable and discoverable in the UA's native environment, while knowledge of actual channel layouts are neither universally available nor standardized. Channel layout constraints could be added in the future if needed.

Definitions:

The channel count of an audio track is the number of independent channels of sound that it contains, i.e. the number of audio samples per sample frame.

Proposed changes:

- Add a boolean channelCount attribute to MediaTrackSupportedConstraints.
- Add a long channelCount attribute to MediaTrackSettings
- Add a long/LongRange channelCount attribute to MediaTrackCapabilities
- Add a ConstraintLong channelCount attribute to MediaTrackConstraintSet

Thank you very much for your consideration.

**Comment by stefhak** [comment]
This has been on the list, and there were no objections. As a result PR #210 was created.

**Comment by burnburn** [comment]
PR #210 was merged.
