### ISSUE TITLE
Order of events ('addtrack' and 'active')

### ISSUE THREAD

**Issue by adam-be** [w3c/mediacapture-main#201]
(The below text is sent to the list)

Consider a case with an inactive MediaStream. For some reason, a new 
'live' track is added to it by the user agent. This means that both an 
'addtrack' and 'active' event must be fired at the stream. I don't 
believe we have specified the order of these.

My proposal is that the 'addtrack and 'removestrack' events fire before 
'active' and 'inactive' in all such cases.

This means that the active attribute will be false when the 'addtrack' 
handler is fired, but it's better than the other way around. And in this 
particular case, it's pretty easy to foresee the upcoming activity 
change by looking at the readyState of the track.

**Comment by stefhak** [comment]
Adam has sent mail to list: https://lists.w3.org/Archives/Public/public-media-capture/2015Jun/0040.html

**Comment by adam-be** [comment]
PR for proposed solution (no discussion yet)
#207

**Comment by stefhak** [comment]
Fixed via #207
