### ISSUE TITLE
Text on 'overconstrained' confusing about deviceId constraint

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#203]
The text on [overconstrained](http://w3c.github.io/mediacapture-main/getusermedia.html#event-mediastreamtrack-overconstrained) reads:

"This error event fires for each affected track (when multiple tracks share the same source) after the user agent has evaluated the current constraints against a given [deviceId](http://w3c.github.io/mediacapture-main/getusermedia.html#dfn-deviceid) and is not able to configure the source within the limitations established by the union of imposed constraints."

Here, [deviceId](http://w3c.github.io/mediacapture-main/getusermedia.html#dfn-deviceid) links to the deviceId constraint definition.

Do we mean "source"? AFAIK the deviceId constraint is not special when it comes to overconstraining.

Also, a "union of constraints" seems confusing to me, when constraints themselves operate by producing an intersection of available capabilities. I don't think we define anywhere what the union of multiple constraints is. Is there a different way to describe this?

**Comment by burnburn** [comment]
Yes, I agree that this should say source instead of deviceId.

Also, "union of imposed constraints" would be better worded as "intersection of imposed constraints".

Do you want to send a PR, or should I just make these changes myself?  I don't believe they are controversial.

**Comment by jan-ivar** [comment]
Feel free, thanks!

**Comment by burnburn** [comment]
@stefhak, can you please confirm that you believe these to be uncontroversial changes that I can just go ahead and make?

**Comment by stefhak** [comment]
I believe they are uncontroversial, please go ahead.

**Comment by burnburn** [comment]
Addressed by PR #229
