### ISSUE TITLE
Use [SameObject]

### ISSUE THREAD

**Issue by foolip** [w3c/mediacapture-main#204]
Some attributes which return objects that appear to always be the same:
MediaStreamTrackEvent.track
MediaStreamErrorEvent.error (nullable, so I'm not sure if it's OK)
NavigatorUserMedia.mediaDevices

@heycam, is it OK to use [SameObject] on a nullable attribute?

**Comment by heycam** [comment]
Per spec, no:

> The [SameObject] extended attribute MUST NOT be used on anything other than a read only attribute whose type is an interface type, an array type or object.

Maybe [SameObject] should become something that indicates that whatever value is returned will always be the same, regardless of whether it's an object.  Gecko's bindings generators support a [Constant] which means this.

**Comment by foolip** [comment]
Hmm, OK. Do you want a spec bug suggesting that change to keep track of it?

Pending that, it seems like MediaStreamTrackEvent.track and NavigatorUserMedia.mediaDevices could be fixed.

**Comment by stefhak** [comment]
Message sent to list https://lists.w3.org/Archives/Public/public-media-capture/2015Jul/0002.html

**Comment by stefhak** [comment]
There was some discussion, and the conclusion so far seem to be "this is not harmful, let's do it".

**Comment by adam-be** [comment]
Proposed fix: https://github.com/w3c/mediacapture-main/pull/228

**Comment by foolip** [comment]
:+1:

**Comment by burnburn** [comment]
PR is merged.
