### ISSUE TITLE
deviceId not available on MediaStreamTrack

### ISSUE THREAD

**Issue by mhofman** [w3c/mediacapture-main#205]
It is currently impossible for an app to reliably identify the device corresponding to a track to which it was granted access to using `getUserMedia()`.
The only unique identifier is `MediaDeviceInfo`'s `deviceId` attribute, which doesn't exist on `MediaStreamTrack` objects. The `label` attribute is present on both objects but is not guaranteed to be unique (e.g. if 2 webcams of the same make/model are available). 

There are multiple use cases where this is needed, including:
- Application requests device access using `getUserMedia()` then shows a custom UI to the user to confirm selection of the device (aka "preview" feature). That UI might have an option to change the chosen devices based on results from device enumeration, where "highlighting" the currently active device is necessary.
- Application requests device access using `getUserMedia()` and directly uses whatever device was selected by the user in the User Agent's UI (or is the default if the UA doesn't ask the user to select a specific device). However, the application wants to "remember" the choice of the user so that it can request this specific device in subsequent visits.

Exposing a `deviceId` attribute on `MediaStreamTrack` objects would solve these use cases.

**Comment by jan-ivar** [comment]
@mhofman - It will exist as `track.getCapabilities().deviceId` once someone implements it.

**Comment by jan-ivar** [comment]
http://w3c.github.io/mediacapture-main/getusermedia.html#media-track-capabilities

**Comment by mhofman** [comment]
My bad, I totally missed `getCapabilities()` ...
