### ISSUE TITLE
Persist deviceIds only after gUM permission grant.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#218]
[Discussed favorably on the list](https://lists.w3.org/Archives/Public/public-media-capture/2015Jul/0004.html), the idea is to limit exposure of persistent ids to the drive-by web.

**Comment by stpeter** [comment]
Handled via manual merge: https://github.com/w3c/mediacapture-main/commit/1bc469f03d50dc9b0965ebac37a12a9eaa5bab4d
