### ISSUE TITLE
Need for creating unconnected MediaStreamTracks 

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-main#221]
In the IETF RTCWEB WG, we have been faced with a scenario where it actually makes sense to create a MediaStreamTrack unconnected to a source (what it really does is to pass the .kind value to addTrack() in order to create an RTCRTPSender - it may concievably carry more information than that).

We removed "new MediaStreamTrack()" some time back, but we may need to resurrect it.

**Comment by jan-ivar** [comment]
Can you explain the scenario?

**Comment by alvestrand** [comment]
The createRtpSender solution seems to have more momentum behind it, and will make this unneccessary. Closing for now.
