### ISSUE TITLE
Clarify whether groupId is origin-unique

### ISSUE THREAD

**Issue by jyasskin** [w3c/mediacapture-main#222]
In #202, @jan-ivar pointed out that [`MediaDeviceInfo.groupId`](https://w3c.github.io/mediacapture-main/#widl-MediaDeviceInfo-groupId) isn't explicitly specified to be origin-unique. However, the [`enumerateDevices`](https://w3c.github.io/mediacapture-main/#widl-MediaDevices-enumerateDevices-Promise-sequence-MediaDeviceInfo) algorithm sets `groupId` to "a newly generated unique identifier" if no device in _oldList_ is in the same physical device. I believe that has to be origin-scoped in order for `deviceId` to be origin-scoped.

_oldList_ is bound by
> If this method has been called previously within this browsing session, let oldList be the list of MediaDeviceInfo objects that was produced at that call (resultList); otherwise, let oldList be an empty list.

And then objects from it are used to populate the return value of `enumerateDevices()`:
> If device is represented by a MediaDeviceInfo object in oldList, append that object to resultList...

That's a little confused: If the method was called in a different execution environment in the same browsing session, this returns a MediaDeviceInfo object from a different global object, so `instanceof` checks won't work. But you can't just limit to previous calls in the current execution context or `groupId` won't be shared within the origin.

**Comment by alvestrand** [comment]
In my opinion, it's obviously origin-unique, but I could be wrong.

**Comment by jan-ivar** [comment]
Here's the trouble I have reading it: `enumerateDevices` is a global method, and in its [processing steps](https://w3c.github.io/mediacapture-main/#dom-mediadevices-enumeratedevices) I find no mention of origin-uniqueness, unless there is some definition of "browsing session" that includes origin-specific context. I thought it just meant "for as long as the browser is running".

In other words, if not for the requirement given under [deviceId](https://w3c.github.io/mediacapture-main/#widl-MediaDeviceInfo-deviceId), I think one could be forgiven for thinking the list returned was global.

Absent similar wording under [groupId](https://w3c.github.io/mediacapture-main/#widl-MediaDeviceInfo-groupId), it seems at least difficult to deduce that it must be origin-unique as well.

**Comment by stefhak** [comment]
I looked into "browsing session" a bit (or rather, @dontcallmedom helped me), and apparently it is not defined. But it is OTOH used quite a bit (usage in e.g.: http://www.w3.org/TR/geolocation-API/, 
http://www.w3.org/TR/powerful-features/, http://www.w3.org/TR/wsc-usecases/, http://www.w3.org, TR/discovery-api/, http://www.w3.org/TR/push-api/). I understand it meaning "for as long as you stay on this page/origin this time", so origin is part of it.

**Comment by alvestrand** [comment]
Last time I hunted for "browsing session", I ended up with "the lifetime of a top level browsing context" (as defined in http://www.w3.org/TR/html51/browsers.html#top-level-browsing-context) as a working definition. There was some reason why someone else (dom might remember) suggested that we wouldn't want to put that definition into the document, but I can't remember what it was.

**Comment by dontcallmedom** [comment]
I think the reason might have been that this spec sounds like an odd place to define such a broadly useful concept…

**Comment by jyasskin** [comment]
@annevk, would it make sense to define "browsing session" in HTML? If so, and if it's impossible right now because HTML is somewhat frozen at the moment, then *this* spec should define the term, with an issue to move it into HTML when that's possible.

**Comment by annevk** [comment]
Yes it would (and your suggested process makes sense). However, what exactly is meant with a browsing session here? If we're talking JavaScript objects they cannot outlive the global object so you could just tie them to that.

**Comment by stefhak** [comment]
@annevk I like that idea. How should it be formulated in spec text?

**Comment by alvestrand** [comment]
@annevk what's the lifetime of the global object that a page sees, and where is it defined?
I'm under the impression that when I navigate to a new page, I get a new global object and a new top-level browsing context; if I open an iframe within the current page, the iframe is a new browsing context, but not a new top-level browsing context; does it have a new global object or not?

**Comment by annevk** [comment]
@alvestrand the lifetime is defined by HTML. Global objects are typically 1:1 with documents. You can assume as much for the purposes of your API. Here's defined what happens when a document is unloaded: https://html.spec.whatwg.org/multipage/browsers.html#unload-a-document Which is triggered by navigation. Navigation also takes care of creating new global objects and such.

What you typically do in specification land if you want to rely on the lifetime of some other object is saying that the other object has an associated _X_. Now you can rely on that _X_ being there as long as the other object is around. And fiddle with it. Then if you need to do cleanup steps yourself for your own objects, you write those down, and attach them to https://html.spec.whatwg.org/multipage/browsers.html#unloading-document-cleanup-steps.

I'm hoping that in due course objects being associated with some other object can become a bit more formal in terms of "internal slots" and some other stuff, but we aren't so organized just yet.

**Comment by stpeter** [comment]
We seem to have agreement that groupId is indeed origin-unique. I will provide a small pull request that clarifies this in the text.

**Comment by stefhak** [comment]
I'll take over from Peter.

**Comment by stpeter** [comment]
Intended to be addressed by https://github.com/w3c/mediacapture-main/pull/240
