### ISSUE TITLE
tracks vs. sinks in Section 5

### ISSUE THREAD

**Issue by stpeter** [w3c/mediacapture-main#225]
Section 5 has the following sentence:

"Using the ConstrainablePattern interface, one of the tracks requests a higher resolution (1920 by 1200 pixels) from the home client's video source."

Should "tracks" actually be "sinks" there?

**Comment by jan-ivar** [comment]
"the ConstrainablePattern interface" is presumably `MediaStreamTrack.applyConstraints`, i.e. "tracks".

**Comment by stpeter** [comment]
I suppose. It feels strange to say the track is the actor here, rather than saying that the sink is the actor, i.e., that the sink requests a higher resolution by calling applyConstraints() on the track. But perhaps this is just terminology...

**Comment by jan-ivar** [comment]
Ah, good point, yes `track` is literally the object, not the subject.

**Comment by stefhak** [comment]
All editors should look at this.

**Comment by jan-ivar** [comment]
I suspect the intent here is something like: "In response to `applyConstraints()` being called, one of the tracks wants a higher resolution (1920 by 1200 pixels) from the home client's video source."

**Comment by alvestrand** [comment]
I think Jan-Ivar's language suggestion makes sense.
