### ISSUE TITLE
WebIDL reference needs updating

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-main#230]
We're using a number of features that are not present in the approved version of WebIDL - [SameObject] was the last one (see #228 ).

We should reference a version of the spec that contains these features (and live with the consequences).

**Comment by dontcallmedom** [comment]
There are ongoing discussions about updating the TR version of WebIDL to include most (if not all) of the things we're using: https://lists.w3.org/Archives/Public/public-webapps/2015JulSep/0261.html

The reference clearly needs updating, but I suggest we should wait till these discussions settle before we do so.

**Comment by alvestrand** [comment]
Given that we depend on this spec, can we insert a reference in a form that makes it clear we're depending on the "level 2" being published before we can go to full Recommendation (or whatever level requires all normative references to resolve)?
In IETF, this is called "reference to draft", and will hold RFCs at the RFC Editor until resolved. I don't know what we call it in W3C.

**Comment by dontcallmedom** [comment]
See https://lists.w3.org/Archives/Member/chairs/2015JulSep/0072.html (Member-only link, sorry) for more details on the plan in this space
