### ISSUE TITLE
clone a track: "inherit" not defined

### ISSUE THREAD

**Issue by annevk** [w3c/mediacapture-main#232]
It's not clear what this means.

**Comment by stpeter** [comment]
Perhaps this change makes sense...

OLD
Let trackClone inherit track's underlying source, kind, label, readyState, and enabled attributes, as well as its currently active constraints.

NEW
Set the source, kind, label, readyState, enabled attributes, and constraints for trackClone to the values currently active for track.

**Comment by annevk** [comment]
Yeah that makes more sense, though it's still somewhat wrong, since "IDL attributes" are actually getters and setters. So you'd have to copy over the internal state and not muddle with the publicly-facing stuff.

**Comment by adam-be** [comment]
Sure the IDL attributes are getters and setters, but it becomes quite verbose to define an internal representation for each and every attribute when it represents a simple value.

I recall often seeing spec text saying something like:
"Change the foo attributes value to 'bar'"
and
"The foo attribute MUST return the value to which it was last set by the User Agent."

That doesn't mean that it's 100% correct, but that it seems like a fairly common shortcut.

**Comment by annevk** [comment]
It is, but it's also wrong. I've filed a bug on IDL to start including the notion of internal slots to make this easier on specification authors.

**Comment by domenic** [comment]
+1 internal slots. Until IDL has support, see for example https://domenic.github.io/streaming-mediastreams/#media-stream-recorder which is my latest attempt at this. Yes it can be a bit verbose, but the gain in precision is very helpful to implementers and readers. Setting a readonly attribute is really wrong.

**Comment by alvestrand** [comment]
Adam will do what stpeter suggested.

**Comment by alvestrand** [comment]
Fixed by #270
