### ISSUE TITLE
"MediaStream.active" is wrong

### ISSUE THREAD

**Issue by annevk** [w3c/mediacapture-main#233]
What this actually means is a static "active" member of the "MediaStream" class, whereas you're talking about something on the instance.

This kind of error repeats itself throughout the draft.

**Comment by adam-be** [comment]
Yeah, we should probably change those. I think we can just strip the interface name from most occurrences, and when it's not 100% clear which interface we're talking about we can add text clarifying that.

**Comment by adam-be** [comment]
PR that fixes MediaStreamTrack and MediaStream attributes and methods: #235

**Comment by adam-be** [comment]
PR updated to address wording like MediaDevices.getUserMedia().

**Comment by alvestrand** [comment]
Fixed in #235
