### ISSUE TITLE
PowerNetworkFrequency constraint?

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-main#234]
Most cameras seem to have some place in their API where you set the line power frequency of the area you live in; this is used to suppress flicker from fluorescent or LED-based lighting fixtures.

Many times, the OS or the browser can make a guess at the right power frequency based on environment factors like timezone or location, and everything's OK.

But sometimes it's wrong. And it makes people unhappy.

One option is to have a way to override the setting from the application if needed; we can, for instance, have a tri-state constraint, mirroring the camera APIs:

powerNetworkFrequency = "50Hz", "60Hz", "default"

(I don't see a case for allowing "powerNetworkFrequency=200", which would be the case if we made it a number.... even though there are railway power grids at 16 2/3 Hz, they're rare enough that we should ignore them for simplicity's case).

**Comment by fluffy** [comment]
Uh, can someone provide a specific example of a modern camera that has this issue. Also be great to see pointers to what OS allow the browser application tell the OS this info and how it is passed in things like USB to the camera. This may all be there but nice if someone could provide some pointers to it.

**Comment by alvestrand** [comment]
The specific case that has been cited is units in the 50Hz part of Japan trying to deflicker at 60Hz.

**Comment by fluffy** [comment]
I have a setup where I can set the lighting to anything from 24 to 120 Hz. Glad to test stuff but I'm surprised we are having problems with modern cameras and want to find out the details of what the problem is.

**Comment by alvestrand** [comment]
Based on offline discussion, the conclusion seems to be that having a constraint for doing this is the wrong way of addressing the issue. If the browser needs to have help from Javascript to learn what the power frequency is, that needs to be a browser-wide configuration, not a per-camera-capture configuration.
