### ISSUE TITLE
step 5 in clone algorithm seems confusing.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#237]
s/Let trackClone be the result of this algorithm./Let the result of this algorithm be trackClone./ ?

**Comment by burnburn** [comment]
From an English language perspective either is fine.  We have in general followed the pattern of Let X be Y, so unless there is a compelling reason to change this I suggest we leave it as is.

**Comment by jan-ivar** [comment]
English is imprecise. Doesn't "Let X be Y" usually mean `let x = y;` ? I think here we're trying to say `return trackClone`, not `let trackClone = algorithm();`.

**Comment by alvestrand** [comment]
Actually "return trackClone" seems better than either.

**Comment by jan-ivar** [comment]
Both English and software language. :thumbsup:

**Comment by burnburn** [comment]
Jan-Ivar, you are, as usual, correct :)  New PR #264 contains this minor wording change.  I expect we will just apply it tomorrow.

**Comment by alvestrand** [comment]
Merged #264.
