### ISSUE TITLE
Some text on constraints needs updating.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#238]
Under [#tracks-and-constraints](http://w3c.github.io/mediacapture-main/getusermedia.html#tracks-and-constraints) I find:

> “Each track maintains an internal version of the Constraints structure, namely a mandatory set of constraints (no duplicates) and an optional ordered list of individual constraint objects (may contain duplicates). The internal stored constraint structure is exposed to the application by the constraints attribute, and may be modified by the applyConstraints() method."

This is clearly talking about about the mandatory{}/optional[] syntax we used to have, and should be updated or removed.

I also find the text confusing in that it sets up the notion of an "internal version" version perhaps different from the API version, and then goes on to say this "internal" structure is exposed, which is odd. Do we mean "internal slot"? And can we say "copy" instead of version? Lastly, there is no constraints *attribute*, but `track.getSettings()`.

**Comment by dontcallmedom** [comment]
I've provided a pull request #285 that simply removes the paragraph; it doesn't contain normative statement, nor does it seem to be describing useful behaviour at this point.

probably worth getting @burnburn confirmation though.
