### ISSUE TITLE
Management of track members in a stream

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-main#242]
The spec is currently pretty lean on detail when it comes to where the set of track is managed.  There are multiple actors that might want to do that.  We should be clear on what the rules of engagement are.

**Comment by martinthomson** [comment]
The primary case of concern here is that the spec doesn't recognize that the set of tracks in a stream might be manipulated by things that are out of the control of an application.  In particular, `RTCPeerConnection` and it's session negotiation.

I don't think that this requires much, but `removeTrack` (or maybe **remove a track** from a `MediaStream`) isn't specified at all.

**Comment by alvestrand** [comment]
@aboba will take care of this

**Comment by aboba** [comment]
Section 4.2.3 defines the basic operation of removeTrack().  

We could add more detail in Section 4.2, such as the following: 

To remove a track to a MediaStream, the User Agent must run the following steps:

1. Let track be the MediaStreamTrack in question and stream the MediaStream object to which track is to be removed.

2. If track is not in the stream's track set, then abort these steps.

3. Remove the track from the stream's track set.

**Comment by alvestrand** [comment]
The spec for the  removetrack event is together with addtrack in section 4.4 (casing confused me a bit).
Seems that we have the spec, it might need to be easier to find somehow.

**Comment by alvestrand** [comment]
See #276 for the issue about which spec talks about event firing.
