### ISSUE TITLE
Confusing typo in sources and sinks.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#243]
Under [#the-model-sources-sinks-constraints-and-settings](http://w3c.github.io/mediacapture-main/getusermedia.html#the-model-sources-sinks-constraints-and-settings):
> While not shown, an equally valid settings change request could be client's side). In addition to impacting sink Y and Z in the same manner as A, B and C were impacted earlier, it could lead to re-negotiation with the peer connection on the home client in order to alter the transformation that it is applying to the home client's video source. Such a change is NOT REQUIRED to change anything related to sink A or B or the home client's video source.

I think "remote client" is meant here, and there's an orphan end bracket ')'.

**Comment by burnburn** [comment]
fixed directly in commit 9e6ff86821a3c23ac7f14dc0c182c62b1159dc1d.
