### ISSUE TITLE
Explain how extensions are to be done

### ISSUE THREAD

**Issue by burnburn** [w3c/mediacapture-main#244]
After a discussion with Nigel Megitt, it has become clear that the specification needs some text explaining how we intend the specification to be extended.  The [Depth work] (http://www.w3.org/TR/mediacapture-depth/) is something we could point to as an example.  We should probably capture at least the following points, in some form:
* It is expected that the specification will be extended.
* Extensions should be done via an extension specification.
* Any WebIDL in the specification can be extended as long as the expected behavior is explained.
* New constrainable properties may be defined, along with additional values for existing properties.
* Although additional support (conformance) requirements for implementers of the extension specification can be defined, no new requirements can be placed upon implementers of the core specification who do not implement the extension specification.

**Comment by burnburn** [comment]
I will write an initial PR with draft text by tomorrow.

**Comment by stefhak** [comment]
@burnburn as none of my mails seem to make it through to you, I make an attempt using this channel. The links I meant are 
https://w3c.github.io/sensors/#extensibility
https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#extensibility

**Comment by burnburn** [comment]
Yes, I don't seem to be receiving any emails from you anymore :(.

I'm going to just put here the drafty text I had written.  The examples you point to are very very much more precise than I think we want, but that is what we can discuss.

Here is the starting text I had written:
*************************************************
Although new versions of this specification may be produced in the future, it is also expected that other standards will need to define new capabilities that build upon those in this specification.  Such extensions to this specification MUST be defined as new, separate Extension Specification documents that adhere to the following guidelines:
- The Extension Specification MAY extend any WebIDL in this specification as long as the expected behavior is explained in the Extension Specification.  The Extension Specification MAY add new methods and attributes and MAY add new legal values for existing attributes.  The Extension Specification MUST NOT remove any methods, attributes, or legal attribute values defined in this specification.
- The Extension Specification MAY define new constrainable properties, as well as additional values for existing constrainable properties.
- Although additional support (conformance) requirements for implementers of the Extension Specification are permitted, the Extension Specification MUST NOT place new requirements upon implementers of this specification who do not implement the Extension Specification.
- Where the Extension Specification changes the legal syntax or described semantics from that given in this specification, the Extension Specification MUST define expected interoperation, if any, with implementations that support this specification but not the Extension Specification.

Other specifications which have created such extensions are XXX and YYY.
*************************************************

**Comment by ekr** [comment]
Suggested text:
Future versions of this specification and W3C-published specifications will not define extension code points that conflict with previously defined code points or code points known to be in use in the field. Implementors who are using a given code point may notify the WG of their use by emailing the WG list at <address>.

**Comment by burnburn** [comment]
Posted a new text proposal on the list:  https://lists.w3.org/Archives/Public/public-media-capture/2015Dec/0009.html

**Comment by stefhak** [comment]
@burnburn do you think we could close this issue now?

**Comment by burnburn** [comment]
Yes.  Closing.
