### ISSUE TITLE
track.applyConstraints() doesn't do anything.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#246]
Here's the full processing model for [MediaStreamTrack's applyConstraints:](http://w3c.github.io/mediacapture-main/getusermedia.html#widl-MediaStreamTrack-applyConstraints-Promise-void--MediaTrackConstraints-constraints):
> See ConstrainablePattern Interface for the definition of this method.
> 
> Parameter | Type | Nullable | Optional | Description
> ---------------|--------|------------|-------------|-------------- 
> constraints | MediaTrackConstraints | ✘ | ✘ | A new constraint structure to apply to this object.
> Return type: Promise<void>

Unless I'm mistaken, the Constrainable pattern has no concept or knowledge of video and audio tracks, so AFAICT all this method does is alter what `track.getSettings()` returns. I think most users would expect it to do a little more than that: actually change something about the video or audio coming out of this track's source.

**Comment by alvestrand** [comment]
It may be easier to get this right after #258 is merged.

**Comment by alvestrand** [comment]
#258 is now merged. Jan-Ivar, do you want to try a PR?

**Comment by burnburn** [comment]
Yes, the current text only implies that some change in tracks occurs but does not define it.  The right solution is to define how the SettingsDictionary and the parameters (such as "object" in SelectSettings) are assigned, along with adding what Jan-Ivar originally pointed out was missing, the final statement of the resulting change in the ConstrainablePattern object (the track).  The last part is essentially filling in the details of what this text means in the context of a track:  "In a single operation, remove the existing constraints from object, apply newConstraints, and apply successfulSettings as the current settings."

**Comment by alvestrand** [comment]
@jan-ivar would you like to make a PR for this?

**Comment by stefhak** [comment]
@jan-ivar ping!

**Comment by alvestrand** [comment]
Fixed by #308
