### ISSUE TITLE
Conflicting information about OverconstrainedError.constraint

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#248]
[7.4 Error names](http://w3c.github.io/mediacapture-main/getusermedia.html#error-names) says:

> Name | Description | Note
> ---------|-----------------|-------
> OverconstrainedError | One of the mandatory Constraints could not be satisfied. | The constraint attribute is set to the name of the constraint *that caused the error*

while [10.2.1 getUserMedia](http://w3c.github.io/mediacapture-main/getusermedia.html#dom-mediadevices-getusermedia) says:
> If *finalSet* is the empty set, let constraint be any required constraint whose fitness distance was infinity for all settings dictionaries examined while executing the **SelectSettings** algorithm

This is not the same thing. For example, if the following fails with `OverconstrainedError`:

    { width: { min: 1280 }, frameRate: { min: 60 }, facingMode: { exact: "user" } }

then it's because there are no resolutions at or above 1280 pixels wide that *also* do 60Hz *and* face the user, even though there may be plenty of 1280x720+ resolutions, 60Hz modes, and cameras that face the user.

The first definition fails because there is no single "constraint that caused the error".

The second definition works, except it returns "", because none of the three constraints have infinite fitness distance from *all* the settings dictionaries.

I need to know which one to implement.

**Comment by jan-ivar** [comment]
FWIW Firefox 43 now implements the second definition.

**Comment by alvestrand** [comment]
I think any required constraint name that contributes to the non-satisfaction should be a legal answer here (that is - the second definition with some relaxation) - it would be nice to return the one that was the most trouble to satisfy, but I don't think it's realistic to require that (too hard to tell).

We know that we can't guarantee that the constraint set is satisfiable if that particular constraint is removed - the other constraints may already be conflicting.

**Comment by jan-ivar** [comment]
Once I thought about it, I like the second definition, because it is well-defined. As a web developer, any constraint I get back I should give it up entirely on and retry, until I get "" then it means each of my constraints are valid on their own, and I should try different combinations of them.

**Comment by muthusmkmtp** [comment]
I have to record my own tab of the browser like chrome.tabCapture API does in chrome browser. What media constraints should I provide to mediaResorder API in firefox to do as of in chrome?
