### ISSUE TITLE
PING: Refer to security-arch on the MUST inside Best Practice for HTTPS

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-main#250]
The "best practice" on storing permissions in section 10.6 "Implementation suggestions" has a MUST in it. It should be rephrased to make it clear that it's saying that security-arch section 5.2 has the MUST, and that it's quoting it, not establishing a new requirement.

This also requires adding security-arch to references, and making the reference normative.

(The alternative is to move it to a place where normative text is appropriate.)

**Comment by alvestrand** [comment]
Fixed in #266

**Comment by alvestrand** [comment]
The fix for #250 did not make it into #266 (it was in #265). Line 3273.

**Comment by aboba** [comment]
Sorry, fixed in PR 278:
https://github.com/w3c/mediacapture-main/issues/250

**Comment by alvestrand** [comment]
Done in #278
