### ISSUE TITLE
PING: Mark fingerprintability of device enumeration

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-main#251]
The fact that there are fingerprinting issues with device enumeration should be called out.

"Finally, can we mark the fingerprintability of the device enumeration section?
http://w3c.github.io/fingerprinting-guidance/#mark-fingerprinting"

**Comment by alvestrand** [comment]
@aboba can you take a look at these 3 issues and possibly draft a PR for them?

**Comment by elagerway** [comment]
Closing, Fingerprint marks #262 merged.
