### ISSUE TITLE
Non-existent constraints attribute in 4.3.2

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#257]
[4.3.2 Tracks and Constraints](http://w3c.github.io/mediacapture-main/getusermedia.html#tracks-and-constraints) says:

"Each track maintains an internal version of the Constraints structure, namely a mandatory set of constraints (no duplicates) and an optional ordered list of individual constraint objects (may contain duplicates). The internal stored constraint structure is exposed to the application by the constraints attribute, and may be modified by the applyConstraints() method."

This paragraph seems redundant and outdated. There is no constraints attribute anymore, the internal description seems old and [getSettings](http://w3c.github.io/mediacapture-main/getusermedia.html#widl-ConstrainablePattern-getConstraints-Constraints) seems to cover everything else.

Also, the undefined term *Constraints structure* is used throughout, where I think we mean *Constraints dictionary*.

**Comment by jan-ivar** [comment]
I mean [getConstraints](http://w3c.github.io/mediacapture-main/getusermedia.html#dfn-getconstraints).

**Comment by jan-ivar** [comment]
The next paragraph seems redundant as well:

"When applyConstraints() is called, a User Agent MUST queue a task to evaluate those changes when the task queue is next serviced."

This seems redundant and even somewhat contradictory to [applyConstraints' processing steps](http://w3c.github.io/mediacapture-main/getusermedia.html#dfn-applyconstraints).

**Comment by dontcallmedom** [comment]
this is a dup of #238 for which a PR exists #285 exists. I suggest closing that one.

**Comment by alvestrand** [comment]
Closing because it's a duplicate.
