### ISSUE TITLE
Permission model for cross-origin iframes

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-main#267]
@juberti suggested that Chrome has some special interaction between the top-level browsing context and iframes when gUM consent is requested.  What, if any, special treatment do we need for cases where gUM is called from within an iframe.

Options: 
1. iframes can request permission as normal, bound to their origin
2. iframes can only request permission their origin == the top level origin
3. iframes can request permission, but they have to request special permission to operate in an iframe (permission key is iframe-origin + a boolean indicating top-level vs iframe)
4. as 3, but each different top-level origin gets a different special permission (permission key is top-level-origin + iframe-origin)
5. permission key is the full origin chain from top-level down
6. Browsers choose

**Comment by stefhak** [comment]
Discussion at TAPC: 1, 4 and 6 most promising.

**Comment by alvestrand** [comment]
Was there discussion on what to do with regard to stored permissions? I assume these would be treated as today, but indexed by whatever we decide the permission key is.

Option 6 seems like a cop-out, and will lead to developers doing browser-sniffing.

**Comment by jan-ivar** [comment]
I'm a bit unclear, what exactly is Chrome is doing? Persistent permissions seem to work fine in https://jsfiddle.net/srn9db4h/ in both Chrome and Firefox, even though it uses an iframe of a different domain (fiddle.jshell.net).

**Comment by adam-be** [comment]
Ping @martinthomson, @juberti and @jan-ivar. How do you want to proceed with this one?

**Comment by martinthomson** [comment]
My preference is that we do a little research and try to double-key (option 4).  By research here, I mean ask developers who might be building widgets and see if they scream.

**Comment by martinthomson** [comment]
Opened w3c/permissions#55 to track the possibility of using an additional origin key for compartmentalizing permissions.

**Comment by alvestrand** [comment]
The webappsec guys seem to give at least lip service to double-keying in their permissions draft.

**Comment by alvestrand** [comment]
The pushback seems to be that if we define double-keying to be useful for our permissions, we should say so, and put it in the spec.

**Comment by stefhak** [comment]
Sounds like the double keying approach (and define it in mediacapture-main) is liked. But how do we go about making the research on whether this is tolerable by app developers?

**Comment by alvestrand** [comment]
It appears that it's hard to get answers without a specific text (and probably guesswork even then). @adam-be will make a PR for option 4 (double key).
