### ISSUE TITLE
 Active state spec inconsistencies

### ISSUE THREAD

**Issue by adam-be** [w3c/mediacapture-main#283]
We have some inconsistencies in the spec regarding the active state.

See email discussion: https://lists.w3.org/Archives/Public/public-media-capture/2015Nov/0012.html

**Comment by alvestrand** [comment]
Discussion seems to have died down with alternative #3 (remove the events) being deemed acceptable.
Adam to write up a PR.

**Comment by adam-be** [comment]
PR #291
