### ISSUE TITLE
Dealing with LC-3019 "WebIDL compilability in template"

### ISSUE THREAD

**Issue by stefhak** [w3c/mediacapture-main#288]
Filing this issue to keep track of that we implement the resolution of https://www.w3.org/2006/02/lc-comments-tracker/47318/WD-mediacapture-streams-20150414/3019. Quoting the resolution:

'We will replace "limitations of the interface definition language" with more details on the actual limitation of WebIDL in terms of using the ConstrainablePattern template.

We do not plan to make any other changes to the actual interface definitions.  It is worth noting that the ongoing discussion (LC-3017) on how to define the various kinds of MediaStreamError will likely result in additional non-WebIDL-complete definitions in the specification.'

**Comment by burnburn** [comment]
We need some text around what the actual limitations are.  IIRC, the issue is that it is not the ConstrainablePattern interface itself that needs to be extensible but the return types for the various methods of ConstrainablePattern, and that the "implements" notion in WebIDL can't handle this kind of extensibility.  @adam-be , does this sound right to you?

**Comment by adam-be** [comment]
Looking at the original issue, the validation issue seem to be solved at least.

Regarding the text about the limitations. I think what you describe is about right. We want to a set of objects with a pattern, but the actual objects don't contain anything that can be directly reused between different users of the constrainable pattern. I think Jan-Ivar's reasoning around a "template pattern" in [1] (at the bottom) makes sense.

[1] https://lists.w3.org/Archives/Public/public-media-capture/2015Apr/0037.html

**Comment by alvestrand** [comment]
We think that Dom intended to say "the chairs have to decide if the LC issue can be closed".

**Comment by stefhak** [comment]
The question to the reporter of LC-3019 if he is happy with this resolution has been sent. No response yet.

**Comment by alvestrand** [comment]
The chairs have decided that this can be closed once the tracker is updated.

**Comment by stefhak** [comment]
Tracker has been updated (https://www.w3.org/2006/02/lc-comments-tracker/47318/WD-mediacapture-streams-20150414/3019).
Closing.
