### ISSUE TITLE
How is an implementation expected to scale video?

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-main#292]
There's a couple of mentions of scaling, but nothing concrete.  I couldn't find anything in the HTML spec quickly, but there might be something we can reference.

**Comment by alvestrand** [comment]
If nobody's seen a need to define something until now for HTML, and stuff is generally seen as working, perhaps we don't need it to be clearer? </duck>

**Comment by alvestrand** [comment]
Closing as "we don't need to define the concept of scaling in this TF".
(it may be an issue relevant to the encoder, but that's a WEBRTC WG issue)
