### ISSUE TITLE
How to handle known but unsupported constraints

### ISSUE THREAD

**Issue by adam-be** [w3c/mediacapture-main#296]
See list discussion:
https://lists.w3.org/Archives/Public/public-media-capture/2015Dec/0056.html

**Comment by alvestrand** [comment]
When the constraint is known but useless (echoCancellation, only "false" supported), the text needs to say that it's supported, but only with one value. @adam-be  will check that the text is consistently clear on this subject.

**Comment by adam-be** [comment]
I tried to clarify this a bit in PR #307.

**Comment by jan-ivar** [comment]
I think there is value in having UAs not return `true` in supportedConstraints until they can reliably implement it. The reason is that for a constraint `foo`:

As a web-dev, if browser X returns `false` in supportedConstraints then I know the browser does not support it, and I can tell the user their browser is the problem, not (necessarily) their hardware.

If browser X returns `true` in supportedConstraints but then I get a single zeroish value in all getCapabilities(), then it would be nice if I could assume that the browser does support it, and I could unequivocally tell the user their browser is fine, but that they need to run out and buy more hardware.

**Comment by adam-be** [comment]
So what you're saying @jan-ivar is that you think it's OK to return a single "off" as a capability if the reason a feature is not supported is out of the browser's control. Have I understood you correctly?

**Comment by jan-ivar** [comment]
It's hard to infer a general rule from the `echoCancellation` constraint, given how complicated it is, conflating both feature vs. value (boolean), and inherent-property vs. control-setting (there are mics with controllable hardware aec, mics with hardware aec that cannot be turned off, mics without aec, and browsers that do software aec), but I'll try.

Say my system has two mics, `micA` with hardware aec ***that cannot be turned off***, and `micB` without aec.

If a browser claims to support the `echoCancellation` constraint, and the browser

1. does ***not*** support software aec, then I would expect `devInfoMicA.getCapabilities().echoCancellation` to yield `[ true ]`, and `devInfoMicB.getCapabilities().echoCancellation` to yield `[ false ]`.

2. If it ***does*** support software aec, then I might expect
`devInfoMicA.getCapabilities().echoCancellation` to yield `[ true ]`, and `devInfoMicB.getCapabilities().echoCancellation` to yield `[ false, true ]`.

3. If it ***does*** support software aec, but ***cannot glean hardware capabilities***, then I might settle for
`devInfoMicA.getCapabilities().echoCancellation` to yield `[ false, true ]`, and `devInfoMicB.getCapabilities().echoCancellation` to yield `[ false, true ]`.

(The third one is arguably a bug, but is where browsers find themselves atm, and some control is better than no control.)

The fourth case, where the browser neither supports software aec, nor can tell the difference between my two mics, seems identical to not supporting the constraint. Claiming support here and returning all `[ false ]` values would make the fourth case is indistinguishable from (1) where neither `micA` nor `micB` support aec, undermining the value of the information for no good reason.

**Comment by alvestrand** [comment]
Let's not overengineer this.

getSupportedConstraints() was specifically added to solve the problem that IDL engines, when passed dictionaries, silently drop attributes that they don't know about.

If we imagine it being used for any other purpose, we reduce its value.

**Comment by jan-ivar** [comment]
Why undermine a use-case with a redundancy?

**Comment by jan-ivar** [comment]
The issue here is `getCapabilities` and what it should return, not `getSupportedConstraints`. I think the WebIDL issue is orthogonal to this question in fact.

**Comment by adam-be** [comment]
Right now we have a quite general description of Capabilities [1] and we have left it up to individual capabilities to describe in more detail what they return (for example echoCancellation [2]). That way we get specific descriptions, which might be easier to read that general descriptions but the downside might be that similar capabilities behave differently. So how should we proceed?

[1] https://w3c.github.io/mediacapture-main/#capabilities
[2] https://w3c.github.io/mediacapture-main/#widl-MediaTrackCapabilities-echoCancellation

**Comment by jan-ivar** [comment]
Specific wins for me. In fact, aren't these capabilities of specific sources, rather than global to the User Agent? Even echoCancellation I wouldn't assume to be a gobal property:

    -    If the User Agent cannot do echo cancellation a single false is reported
    +    If the source cannot do echo cancellation a single false is reported.

**Comment by adam-be** [comment]
@jan-ivar, please have a look at #315. I've tried to sort of some of the things we've talked about here (including the change you proposed in your last comment).

**Comment by stefhak** [comment]
Fixed with #315 .
