### ISSUE TITLE
Consider merging ErrorEvent definition with Media Stream Recording

### ISSUE THREAD

**Issue by miguelao** [w3c/mediacapture-main#298]
Sister issue of https://github.com/w3c/mediacapture-record/issues/42.

**Comment by alvestrand** [comment]
@alvestrand to check with @miguelao that this can be closed, since it's only a recording change.

**Comment by miguelao** [comment]
I'm happy with the status. I wonder if we could consider (here or in another issue) to have an ```error``` field [like HTMLMediaElement](https://html.spec.whatwg.org/multipage/embedded-content.html#media-elements) - like mentioned in w3c/mediacapture-record#42 ?

**Comment by alvestrand** [comment]
We've discussed a proposal for an error field before. With many things going on, it's unclear enough what the error field would represent that it's not a good idea.

Closing issue - mediacapture-record should be able to resolve this.
