### ISSUE TITLE
Unclear how to associate current active device with enumerated devices

### ISSUE THREAD

**Issue by jnoring** [w3c/mediacapture-main#299]
After calling getUserMedia and setting up a webrtc connection, we can fetch info about the local stream like so (assume localStream is a MediaStream object):

```
localStream.getTracks();
```

...this returns an array of MediaStreamTrack objects.  What is unclear to me is how to take the MediaStreamTrack objects, and reconcile that with ```navigator.mediaDevices.enumerateDevices```. assuming the browser sets the "label" attribute on both the MediaDeviceInfo object returned from enumerateDevices, as well as the "label" attribute on MediaStreamTrack, in theory it's possible to make an association.  I have no idea why a MediaStreamTrack wouldn't just HAVE a MediaDeviceInfo associated with it, or why the MediaStreamTrack ID wouldn't be some common key between the two objects, or any number of other methods that are significantly better than relying on label.  Or if I'm flat-out doing it wrong, but so far I haven't figured out an obvious way.

Currently Firefox doesn't set this label, so literally--unless I've missed something--there is no way to know what the current active camera/microphone is for a given MediaStream in Firefox.  As best I can tell this is also legitimate per the spec, since MediaStreamTrack's label attribute states ```User Agents MAY label audio and video sources```, so technically no label is required.

Two questions:

1. What am I doing wrong?  This feels ridiculously hard to implement in a way that doesn't suck.
2. From an API standpoint, having MediaDeviceInfo be completely separate from MediaStreamTrack makes for an API that is really, really cumbersome to use.  Has anyone at the w3c tried to make a coherent cross-browser API (which, at this point, should be theoretically possible with both Chrome and Firefox) that A) allows device enumeration, B) allows device selection, C) can tell what the current active device(s) are and D) persists user-selected devices between runs of the page?

**Comment by mhofman** [comment]
You can match [MediaStreamTrack.getSettings().deviceId](http://w3c.github.io/mediacapture-main/#widl-MediaTrackSettings-deviceId) with [MediaDeviceInfo.deviceId](http://w3c.github.io/mediacapture-main/#widl-MediaDeviceInfo-deviceId).

I believe at TPAC we talked about linking to the MediaDevice object from the MediaStreamTrack somehow, but I can't remember the outcome of that discussion.

**Comment by alvestrand** [comment]
This seems to be explained well. @jnoring, can you confirm that the explanation addresses your concern? If so, I'll close the issue.

**Comment by jnoring** [comment]
Neither Chrome nor Firefox currently implement ```MediaStreamTrack.getSettings()```, unfortunately.  I'm at a dead-end until those guys get their act together, it seems.

**Comment by jnoring** [comment]
@alvestrand it does.  You can close.

**Comment by alvestrand** [comment]
Thanks! Closing.

@jnoring for Chrome and getSettings, you can follow https://bugs.chromium.org/p/webrtc/issues/detail?id=2481 - it will be updated when we get around to it. (Scheduled behind new-style constraints, which is a bigger task, unfortunately).

**Comment by jnoring** [comment]
Honestly with the label attribute on MediaStreamTrack, the Chrome situation is tedious but manageable.  Firefox, on the other hand, is a complete failure.  It is--as best I can see--impossible to know what camera/mic is currently selected.

**Comment by jan-ivar** [comment]
@jnoring To answer your second question about cross-browser, the example http://webrtc.github.io/samples/src/content/devices/input-output/ works in both Chrome, Firefox, and afaik Edge, so I think that answers A, B and D. 

Also note that C is often not an issue when doing B, since it is deterministic in that case, if you use `deviceId: { exact: id }`, as is done in the above-linked example.

C is an issue when not doing B, especially in Firefox at the moment. We are in the process of addressing this. The bugs to track are: https://bugzil.la/1233870 (label) and https://bugzil.la/1213517 (getSettings).

**Comment by randallb** [comment]
FWIW getSettings looks like it's hitting in Chrome 59.

**Comment by ryuujo1573** [comment]
> You can match [MediaStreamTrack.getSettings().deviceId](http://w3c.github.io/mediacapture-main/#widl-MediaTrackSettings-deviceId) with [MediaDeviceInfo.deviceId](http://w3c.github.io/mediacapture-main/#widl-MediaDeviceInfo-deviceId).

These two fields disagreed with each other in my case:
the former is something like `2832941d9201b00969211442bf60ea29942e7df00b357b4a5b461f98258f8fc2`
and the latter is like `WebAudio-136f5dad-b321-40e0-ba31-66f8e6136a11`
Is it about chrome/edge ?

```
Microsoft Edge
Version 110.0.1587.41 (Official build) (arm64)
Darwin ascii_name.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64
