### ISSUE TITLE
on{add,remove}track event description inconsistency

### ISSUE THREAD

**Issue by miguelao** [w3c/mediacapture-main#302]
(normative) Section https://w3c.github.io/mediacapture-main/#attributes seems to imply that every ```{add,remove}track()``` ends up firing an ```on{add,remove}track``` event, but (non-normative) Section 
https://w3c.github.io/mediacapture-main/getusermedia.html#event-summary includes the rather odd limitation: 
> Note that this event is not fired when the script directly modifies the tracks of a MediaStream.

Propose that the appropriate Event gets fired regardless of the origin of the call (or at least explain better this inconsistency).

**Comment by stefhak** [comment]
I agree that it is odd that the (normative) behavior is described in a non normative section. However, the behavior (i.e. not firing when the script adds or removes tracks) has been discussed a few times, and this is consistent with other parts of the platform, so I don't think it should be changed.

**Comment by adam-be** [comment]
The normative behaviour is described in section 4.2 [1]. You find it a few paragraphs down starting with "When the User Agent initiates adding a track to a MediaStream...".

Perhaps we should update the text in the event summary to say:
"Note that when the script calls addTrack(), the the given track is added directly (synchronously) and this event is not fired."

[1] https://w3c.github.io/mediacapture-main/#mediastream

**Comment by stefhak** [comment]
Right. Given that I'm inclined to close this Issue. Anyone objecting to that? @miguelao ?

**Comment by miguelao** [comment]
Summing up (for adding, resp. removing):
- if JS does ```stream.addTrack(leTrack)```, where ```leTrack.remote == false```, then no ```onaddtrack``` is fired. Same if ```leTrack.remote == true```. ```addTrack()``` is synchronous and immediate.
- if the UA on its own will adds a Track to ```stream```, then an ```onaddtrack``` is fired.

I'd rather have this info in https://w3c.github.io/mediacapture-main/#attributes, but that' a purely editorial comment so I'd leave it to the editors. Thanks, closing!
