### ISSUE TITLE
getUserMedia: spec does not define what happens when browser gUM dialog disappears completely

### ISSUE THREAD

**Issue by jnoring** [w3c/mediacapture-main#303]
Currently, some browsers--namely Firefox--will remove the gUM prompt if a browser swaps to a different tab, or goes to another application.  The problem is the page receives no notification about this dialog going away, so processing in the page is generally hung waiting for a success/error promise or callback to fire.

The current spec doesn't appear to address this (I could be wrong about this). If the gUM prompt goes away for any reason without user interaction, should the calling page be informed of this?

**Comment by Pehrsons** [comment]
The dialog disappearing sounds more like an implementation bug than a spec bug to me.

However, you'll find that the dialog in Firefox is still available behind the camera button in the address bar. You can at any time open this dialog to resolve or reject the gUM promise.

**Comment by jnoring** [comment]
In Firefox, I believe this is considered "by design": https://bugzilla.mozilla.org/show_bug.cgi?id=895971

Users are not going to find the camera button in the address bar.  I have almost never seen a user find this UI on their own, and that includes both Chrome and Firefox.

**Comment by mhofman** [comment]
IMHO, definitely an implementation issue.
The application can already detect this lost of focus using other Web APIs, and show a modal itself to bring the user attention's to the icon in the address bar. Not optimal but possible to work around the browser issue.

The only thing I could see being a spec issue is that the gUM call is not cancelable, so if the app for some reason wanted to "renew" the permission prompt, it has no way to do so without potentially having multiple outstanding requests. I believe issue #127 is talking about this and is already in the icebox.

**Comment by stefhak** [comment]
I'm inclined towards closing this issue as "won't fix".
@mhofman we've talked quite some about canceling gUM, but that turned into the question of canceling a Promise which is discussed elsewhere. I have not followed up on that part lately though.

**Comment by mhofman** [comment]
Yup I'm aware of the promise cancellation discussions. Complicated topic that should be solved at the platform level, not in individual specs. I agree, we should close this and track cancellation in 127.

**Comment by stefhak** [comment]
Closing per the above discussion .
