### ISSUE TITLE
Hardware fingerprinting mitigation

### ISSUE THREAD

**Issue by KOLANICH** [w3c/mediacapture-main#312]
Maybe we should prescribe browser vendors to mitigate the identified possibilities of hardware fingerprinting? For example detect dead pixels (and any other static defects) on webcams, add some fake dead pixels, discard and interpolate them.

Some references to the ways of fingerprinting can be found in http://arxiv.org/pdf/1503.01408.pdf

**Comment by mhofman** [comment]
Access to stream data is gated on a user permission prompt.

Once the application has access to the video and audio, there are a lot more obvious fingerprinting sources than hardware info, namely the user sitting in front of the computer...

**Comment by KOLANICH** [comment]
>Once the application has access to the video and audio, there are a lot more obvious fingerprinting sources than hardware info, namely the user sitting in front of the computer...

The user's face may be not visible and a user can think he is not trackable, but he is.

**Comment by stefhak** [comment]
Closing per @elagerway 's comment in #311 . The issue will remain (but in the "closed" category), we can return to it for an extension or later version if we thing that is the right thing to do.
