### ISSUE TITLE
Stop a remote track has no effect

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-main#314]
The current description of track's stop:

When a MediaStreamTrack object's stop() method is invoked, the User Agent must run following steps:
- Let track be the current MediaStreamTrack object.
- If track is sourced by a non-local source, then abort these steps.
- Notify track's source that track is ended so that the source may be stopped, unless other MediaStreamTrack objects depend on it.
- Set track's readyState attribute to ended.

This seems wrong to me. Stopping a track should cause the track to stop, no matter where it comes from. If it's a non-local source, its handler may choose to ignore the notification or not; this spec does not have to say.

Suggested fix:

- Delete step 2
- Modify step 3 to be "Notify track's source that track is ended."
- Add a sentence under the description that says "For local sources that are notified of a track ending, the source will be stopped if no other MediaStreamTrack objects depend on it,"

**Comment by stefhak** [comment]
I like this proposal.

**Comment by martinthomson** [comment]
Isn't it true that a remote track has the same reference-counting requirement as a local one?  That is, if a MediaStreamTrack from a RTCPeerConnection has been cloned, then stopping one of the clones would do nothing; stopping all of the clones might signal to RTCPeerConnection that the media is no longer wanted.  Or, maybe RTCPeerConnection can choose to ignore that signal on its own rather than having the gUM spec tell it what to do.

**Comment by alvestrand** [comment]
I think the requirement might be a leftover from when we thought that local events could trigger signalling - if all the local sinks of a remote stream were to be stopped, it would be logical to turn off the decoder, but it would probably not be required that the UA fire the onnegotiationneeded signal.

But the way I'm suggesting we write it, this handling can be safely relegated to the webrtc-pc document.

**Comment by alvestrand** [comment]
Note: We should make sure the link to WebRTC-PC is followable.

https://github.com/w3c/webrtc-pc/issues/513 filed.

**Comment by alvestrand** [comment]
Fixed by #318
