### ISSUE TITLE
MediaTrackSettings/ConstraintSet/Capabilities... should link names to their descriptions

### ISSUE THREAD

**Issue by adam-be** [w3c/mediacapture-main#316]
We currently have rather big dictionaries with a lot of members where the descriptions are empty and the whole description section just duplicates information that is already in the WebIDL. We should link to the 4.3.9 Constrainable Properties section for each member.

The MediaTrackCapabilities descriptions may need more information for some members.

**Comment by alvestrand** [comment]
Fixed by #345
