### ISSUE TITLE
Switch getUserMedia permission-rejection to NotAllowedError ?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#317]
A new DOMException `NotAllowedError` was just added in https://github.com/heycam/webidl/pull/85. It seems more appropriate than today's `SecurityError` for `getUserMedia` when permissions are rejected (there are links in the PR suggesting it being useful for `PermissionDeniedError`-type errors, and that's what we had originally).

After all, we don't want people thinking `getUserMedia` is insecure now do we? Thoughts?

**Comment by jan-ivar** [comment]
My understanding is that `SecurityError` is more for security issues that come up with violations of same-origin policies. We had at least one developer of an extension that got confused.

**Comment by alvestrand** [comment]
Description of NotAllowedError doesn't permit user refusing - description is "The request is not allowed by the user agent or the platform in the current context.".

https://github.com/heycam/webidl/issues/95 is a request for clarification on what should be done.

**Comment by jan-ivar** [comment]
Isn't the user agent an agent of the user? In other words, if something is not allowed by a user agent, then maybe that's because the user instructed the agent to disallow it?

FWIW https://github.com/heycam/webidl/pull/85#issuecomment-172502495 seems to mention user interaction.

**Comment by alvestrand** [comment]
Sadly, I can't find a definition of either "user agent" or "user" in the webidl spec. I assume that they're assumed to be inherited from somewhere, but the spec doesn't say where. New bug?
(There's one reference to "HTML user agent" in an example, which may be a hint.)

"User" is also used in the context of "user objects", indicating that it's used for the Javascript that uses the WebIDL-defined API, which is not what we're talking about here.

Terminology is hard...

**Comment by jan-ivar** [comment]
FWIW "user agent" seems self evident to me, since users are not software. I don't think web errors should tell on the user (single out a user-choice as the "problem"), because the only use for that seems to be social engineering and/or feature-hostage-taking.

**Comment by jan-ivar** [comment]
Also, no message is perfect, but can we agree it is superior to today's "The operation is insecure", which anecdotally leads to people thinking `getUserMedia` is "unsafe" (from the subject of this [SO question](http://stackoverflow.com/questions/35834308/webrtc-screen-capture-is-still-unsafe-even-if-https-is-used)?

**Comment by alvestrand** [comment]
Conclusion: Let's use NotAllowedError. PR requested.

**Comment by alvestrand** [comment]
Merged.
