### ISSUE TITLE
Should we remove track attributes "remote" and "readonly"?

### ISSUE THREAD

**Issue by stefhak** [w3c/mediacapture-main#320]
This has been discussed on the list recently.

**Comment by alvestrand** [comment]
Note of impending consensus sent out March 8. Waiting for a week or so before drawing the conclusion.

**Comment by dontcallmedom** [comment]
https://lists.w3.org/Archives/Public/public-media-capture/2016Mar/0036.html was sent 9 days ago, so I think #321 should be merged and this be closed.

**Comment by alvestrand** [comment]
The chairs agree.

**Comment by alvestrand** [comment]
#321 merged.

**Comment by guest271314** [comment]
@alvestrand Interestingly Firefox 68 sets the `MediaStreamTrack` `label` attribute to `"remote"` when passed to a WebRTC `PeerConnection` using `addTrack()` which results in the error `SecurityError: The operation is insecure.` when `MediaRecorder` `start()` method is executed. Have not been able to find that functionality described in https://w3c.github.io/mediacapture-fromelement or https://w3c.github.io/mediacapture-main/. Bug report https://bugzilla.mozilla.org/show_bug.cgi?id=1542616, plnkr https://plnkr.co/edit/l0RoRH.
