### ISSUE TITLE
Browsing sessions and device IDs

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-main#322]
We've had a fair bit of back-and-forth about this at Mozilla (I hope to have https://bugzilla.mozilla.org/show_bug.cgi?id=1223773 opened so people can see that discussion, but it's still locked down).

The definition of "browsing session", which was created after the term was used in gUM, is a poor fit for this use case.  In that bug, @jan-ivar was motivated to go to somewhat extraordinary efforts to be compliant with the definition we have (see aforementioned bug).  That would be OK, except that it didn't really address a security issue.

Architecturally speaking, sites need to have a consistent view of any persistent state that a browser retains for them.  This includes device identifiers, which are, for better or worse, a form of persistent identifier.  Requiring identifiers to be discarded at specific points in time, as the current text does, and on a different timeline to other persisted state, can harm that view unnecessarily.  There is no security or privacy advantage to be gained by throwing away this state, but site integrity can be adversely affected.

I suggest that "browser session" isn't a good fit for what we want to have for the lifetime of device identifiers.

We've been around this problem a few times, and I think that ultimately we will find it hard to agree on a single lifetime for these identifiers.  However, I think that we can and should set expectations.  I propose:

1. That the minimum time over which the identifiers persist, absent user override, is a browsing session.  That is, unless a user intervenes, device identifiers are constant for a given origin for the duration of a browsing session.

2. That browsers be permitted to persist those identifiers after that, but they not be required to.

This allows a browser to drop identifiers on shutdown (whatever that means), or to run a timer, or to watch for the last window open to an origin to close and nuke at that point.  It also allows for different policies during normal and "private" browsing.

Ideally, we would persist these identifiers just like other origin-specific state, but the cost of implementing that vs. the benefit was considered and I don't think that we wanted to invest that effort.  I think that we would if we all decided that was the right thing to do.  I think that it is, but consider the value to be dismally low.  Thus, I did not propose this as a third part to the above proposal, but would support that if others do.

**Comment by alvestrand** [comment]
The idea we had was that apps could store a token (not necessarily in a cookie) and come back later (possibly much later) and find the same device at the same token. Any expiry at all works against that.
The way we implemented it, we have a single per-origin "cookie" (not very expensive), which we hash together with a stable identifier for the device to produce a device ID that is unique and persistent. The "cookie" gets cleared together with "clear cookies for this domain".

I think this makes sense for us, but YMMV.

**Comment by martinthomson** [comment]
I agree that this is the ideal solution; I will let @jan-ivar weigh in on whether this would work for the Firefox implementation.

**Comment by stefhak** [comment]
@martinthomson reading your text above, and reading the spec does not really make it clear what you want changed. I agree to Harald, not persisting deviceId (given the user has allowed use of input devices in the first place) between browsing sessions may make the user experience bad (and I even think you yourself argued so several years back :) ).

**Comment by martinthomson** [comment]
Change the lifetime of identifiers to "co-extant with cookies", as @alvestrand says Chrome does.  At least change it to require that they be stable for *at least* a browsing session.  The current text could be read as requiring that a browser break continuity at the end of a browsing session.

**Comment by ekr** [comment]
I agree with MT

**Comment by dontcallmedom** [comment]
To be clear, the suggestion here is to remove the following requirement, right?
> As long as no local device has been attached to an active MediaStreamTrack in a page from this origin, and no persistent permission to access local devices has been granted to this origin, then this identifier MUST NOT be reusable after the end of the current browsing session.

Or maybe more generally, remove the tie to browsing session and permission grant, and instead treat `deviceId` in every cases just as cookies and persistent storage are?

**Comment by stefhak** [comment]
@dontcallmedom how much worse would that be from a fingerprinting perspective?

**Comment by dontcallmedom** [comment]
as long as they're origin-scoped and cookies-lifetime-bound, I don't think it changes anything to the fingerprinting surface.

**Comment by jan-ivar** [comment]
@alvestrand what's the expiry of the Chrome cookie?

**Comment by jan-ivar** [comment]
Also, does it adhere to third-party-cookie policy?

**Comment by alvestrand** [comment]
It's not a cookie, it's a cookie-like object. AFAIK, lifetime is infinite, and it's (by definition) a first-party object. I'll have to look at the code to say more.

**Comment by jan-ivar** [comment]
That sounds similar to what Firefox has.

**Comment by stefhak** [comment]
@martinthomson @jan-ivar can you verify what you would like to see happen? Is it to remove the section Dom mentions,  is it some other change, or is it to do nothing to the spec?
If it is the first thing (i.e. remove the section) we must run it via the list.

**Comment by martinthomson** [comment]
Yes,  and my preference is to adopt the more general option Dom mentions too.

**Comment by alvestrand** [comment]
I think that's rolling back a change that @jan-ivar asked for (if my memory's right, he was the one who wanted the ability to not store the device-id-salting cookie if no device had been opened in the session).
I like the simplification, but to @dontcallmedom's comment - note that I don't think cookies and persistent storage are treated the same in all cases. (I could be wrong). Saying "MUST be cleared when cookies are cleared" may be correct (and short).

**Comment by dontcallmedom** [comment]
Re cookies and persistent storage, as the [Web storage spec](https://html.spec.whatwg.org/multipage/webstorage.html#privacy) states:
> Treating persistent storage as cookies
>
> If users attempt to protect their privacy by clearing cookies without also clearing data stored in the local storage area, sites can defeat those attempts by using the two features as redundant backup for each other. User agents should present the interfaces for clearing these in a way that helps users to understand this possibility and enables them to delete data in all persistent storage features simultaneously.

In practice, we already have [text to that effect for `deviceId`](http://w3c.github.io/mediacapture-main/getusermedia.html#widl-MediaDeviceInfo-deviceId):
> Since deviceId may persist across browsing sessions and to reduce its potential as a fingerprinting mechanism, deviceId is to be treated as other persistent storage mechanisms such as cookies

So I think we "just" need to remove the binding to permission grant and browsing session and should be good.

**Comment by martinthomson** [comment]
@dontcallmedom, SGTM, I'll spin up a PR.

**Comment by martinthomson** [comment]
Note that this corrects a contradiction, because we have:

> The same identifier MUST be valid between browsing sessions of this origin

**Comment by jan-ivar** [comment]
I think the PR goes too far. Here's what happened: In July, several of us confused "browser session" (browser-close, like session-cookies [3]) and "browsing session" (navigate away from page).

Firefox implements the former, i.e. clears temporary *pre-grant deviceIds* on browser shutdown (and last private browsing mode window).

The spec added a clear definition later, retroactively applied to this language (not a great way to cement intentional consensus). Realizing the spec was now stricter than what Firefox implemented, I opened [Bug 1223773](https://bugzilla.mozilla.org/show_bug.cgi?id=1223773) to comply, which I did, but the patch never landed due to discussion in the bug (the bug is now open, so I encourage people to read it).

Therefore, changing "browsing session" to "browser session" (or whatever we want to call it), is the *minimal ask*. Anything else is bathwater and baby.

> I think that's rolling back a change that @jan-ivar asked for (if my memory's right, he was the one who wanted the ability to not store the device-id-salting cookie if no device had been opened in the session).

If you recall, this solved last call feedback from privacy IG and contentious discussion from public backlash at the time [1] [2]. Do we really wish to reopen a privacy debate now?

[1] https://lists.w3.org/Archives/Public/public-media-capture/2015Jun/0042.html
[2] https://lists.w3.org/Archives/Public/public-media-capture/2015Jul/0004.html
[3] Interesting info on session cookies: http://stackoverflow.com/q/10617954/918910

**Comment by jan-ivar** [comment]
Here are the options at this point (in increasing order of impact):
 1. Do nothing and fix Firefox.
 2. Change "browsing session" to "browser session" or whatever we want to call it.
 3. Remove any requirement to clear pre-grant `deviceId`s.
 4. Require pre-grant `deviceId` to always be persisted (roll back July).

The above discussion seemed to start out with 3, and devolved into 4. One reason is this:

> Note that this corrects a contradiction, because we have:
>
> >    The same identifier MUST be valid between browsing sessions of this origin

This statement contradicts the July decision. By letting it stand, the net result of https://github.com/w3c/mediacapture-main/issues/326 is language seems to outlaw what Firefox is doing today.

**Comment by mhofman** [comment]
I would say 2. and 3. are both good approaches.
I can't see any use of 4. for legitimate applications and it opens up the possibility of "ghost cookies", i.e. a unique identifier for an origin, stored in the browser that's not visible to the user.

**Comment by stefhak** [comment]
Thanks @jan-ivar for reminding us of the PING comment and discussion.
I think #306 does 3. in your list.

**Comment by alvestrand** [comment]
I understand #4. I don't understand what #2 would accomplish - we're not talking terminology here, we're talking observable events. (And we should probably settle on terminology that equates to HTML "top level browsing context", but that's another issue.)

I don't understand #3. Would it mean "you have no idea whether pre-grant deviceIds will be persisted or not"? If that's what it means, I could live with it, but it seems odd.

#1 needs to be accompanied by a CL that modifies the statement found to be consistent with what we did in July (giving us #1.5). I think I'd prefer that.

Of the links provided, [3] appears irrelevant (different problem). Thanks for reminding us of [2]!

**Comment by stefhak** [comment]
I had a quick look in the doc, and with 1.5 I think there is more to do than modifying just that statement. Persisting ```groupId``` should also be gated to only be done if the user has granted access in the same way as ```deviceId```.
I also found ```sourceId``` being used, should be changed to ```deviceId```.

**Comment by jan-ivar** [comment]
> I think #306 does 3. in your list.

(Assuming you mean https://github.com/w3c/mediacapture-main/pull/326) I think it would, except it leaves the statement "The same identifier MUST be valid between browsing sessions of this origin" intact, which to me sounds like # 4, when interpreted together. @martinthomson would need to speak to PR intent.

**Comment by jan-ivar** [comment]
> I don't understand what #2 would accomplish

To clarify, I'm trying to say "browser close" there, which has nothing to do with top-level browsing context. Sorry if that was confusing, I just don't know the correct term. Whatever we call it, # 2 would mean mandate for all browsers essentially what Firefox does already (clear pre-grant deviceIds when the browser is closed, not when navigating away from a page).

Comparatively, # 3 would allow Firefox to continue its present level of clearing of pre-grant deviceIds, but *not mandate* such behavior (i.e. in other browsers). # 4 would force Firefox to stop clearing pre-grant deviceIds.

> #1 needs to be accompanied by a CL that modifies the statement found to be consistent with what we did in July (giving us #1.5). I think I'd prefer that.

I would be OK with that.

**Comment by martinthomson** [comment]
To clarify, when we create persistent state in a browser, then it should persist in the same timescale as all other persistent state. To do otherwise creates a very uncertain platform upon which to build apps. 

Doing otherwise has zero privacy impact to most users. Those with irregular cookie policies should get matching behaviour. That is: if a cookie goes, so do the IDs.

Do I have to include an explicit "if the browser feels like it, it can delete identifiers" …  would that make people happier? That is always true, but I could write it down.

**Comment by stefhak** [comment]
I had another look at the spec, and I think it is not that broken. ```The same identifier MUST be valid between browsing sessions of this origin, ... ```is only said in the context of a ```MediaStreamTrack```, and then (by definition) ```local devices have been attached to an active MediaStreamTrack```.
```As long as no local device has been attached to an active MediaStreamTrack in a page from this origin, and no persistent permission to access local devices has been granted to this origin, then this identifier MUST NOT be reusable after the end of the current browsing session.``` is OTOH only said in the context of enumerateDevices, i.e. there is no ```MediaStreamTrack```.

I drafted #328 to make ```groupId``` being handled in the same way.

**Comment by stefhak** [comment]
Based on the discussion in #328 I created #330

**Comment by stefhak** [comment]
My personal view is that we should go on the path of clarifying that groupId is not persisted (as @jan-ivar pointed out), and make a minimum of other changes (something along the lines of #330 ). However, I've been quite involved here, assigning @alvestrand for a more neutral view.

**Comment by alvestrand** [comment]
We may not need to change anything in how the IDs work (not persistent before you open something, is persistent after), but may have to add explanation to make it clearer that it's so.

**Comment by burnburn** [comment]
After reviewing #322, #326, #328, and #330, I think that #330 is accurate with the agreements so far.  Harald, do you believe we need more than that provided by #330?  I am not sure the spec needs more text, but I am very sure that all of us who explain how to use WebRTC will have to explain this point :)

**Comment by alvestrand** [comment]
I think that's a reasonable conclusion. Let's merge #330 when appropriate (Thursday?) and close this issue.

**Comment by stefhak** [comment]
#330 has been merged, we should be able to close this Issue.

**Comment by alvestrand** [comment]
Closing.
