### ISSUE TITLE
Get raw data from MediaStream

### ISSUE THREAD

**Issue by piedshag** [w3c/mediacapture-main#327]
Please excuse me if this is the wrong place to propose this. It would be really useful to have access to the raw data coming out of the MediaStream so it could be processed before being shipped off to a remote peer or displayed to the user. The data could perhaps be emitted in an `ondata` event which would emit raw data similar to that of the MediaRecorder. Would anyone else find something along these lines useful?

**Comment by alvestrand** [comment]
There's no such thing as "the raw data". There are many different possible internal representations, and we do not constrain which of them browsers use.
If you want the bitmap, paint it to a canvas via a video element.
If you want a compressed media format, use the MediaStreamRecorder.
I think we have the interfaces we need. What scenario isn't covered?

**Comment by piedshag** [comment]
I believe the Media recorder only gives you the media when the stream has finished or you end the recorder. I would like the media as it is produced and as far as I am aware that is not possible with the Media recorder.

**Comment by alvestrand** [comment]
See the "requestData" method in https://rawgit.com/w3c/mediacapture-record/master/MediaRecorder.html#methods - you can get the so-far-available data at any time.

**Comment by piedshag** [comment]
Thankyou!  I should have done some proper research

**Comment by alvestrand** [comment]
Seems that no action is needed. Closing.

**Comment by Pehrsons** [comment]
There's also https://w3c.github.io/mediacapture-worker/ being drafted.

**Comment by embirico** [comment]
Hey @alvestrand, sorry to resuscitate an old thread, but I currently have a use case for getting the raw data, and a scenario that doesn't seem to be currently covered:

I have an application with fairly long-lived streams (e.g. 1 hour long at a time), and I'd like to provide users with a way to capture short clips of the most recent, say, 15 seconds.

Currently it seems that creating a buffer of the most recent data directly from the MediaStream is not supported.
Also, it seems that keeping a buffer of the most recent blobs from MediaRecorder doesn't work, due to the spec stating that
> When multiple Blobs are returned (because of timeslice or requestData()), the individual Blobs need not be playable, but the combination of all the Blobs from a completed recording MUST be playable.

What do you think of supporting this scenario, or is there an interface I'm missing? Thank you!

**Comment by bc** [comment]
@embirico did you end up finding a solution? I have a similar use cae

**Comment by aboba** [comment]
@bc @embirico  As Harald has noted, access to raw video is already supported.  Therefore the focus for new APIs is on scenarios requiring higher performance than is currently achievable via Canvas or MediaRecorder. We have the following WebRTC-NV use cases for access to raw video (raw audio access is already provided via WebAudio Worklets): 
[Funny Hats](https://www.w3.org/TR/webrtc-nv-use-cases/#funnyhats*)
[Machine Learning](https://www.w3.org/TR/webrtc-nv-use-cases/#machinelearning*)

So far, there are two specifications under development which could conceivably address these use cases: 
[Funny Hats](https://www.w3.org/TR/webrtc-nv-use-cases/#funnyhats*)
[Machine Learning](https://www.w3.org/TR/webrtc-nv-use-cases/#machinelearning*)

[Insertable Streams](https://github.com/alvestrand/webrtc-media-streams)
[WebCodecs](https://github.com/WICG/web-codecs)

**Comment by BlobTheKat** [comment]
> If you want the bitmap, paint it to a canvas via a video element. If you want a compressed media format, use the MediaStreamRecorder. I think we have the interfaces we need. What scenario isn't covered?

Capturing microphone data to perform some processing and/or upload it over network. For some applications implementing WebRTC is more trouble than it's worth and reusing an existing http/websocket interface makes the most sense. The only way to obtain the raw data currently is with a script processor node on an AudioContext which can capture input data. This definitely feels like the wrong way to do it. MediaRecorder is not sufficient as the different supported output formats by different browsers are too restrictive to be useful in most cases

**Comment by JamesTheAwesomeDude** [comment]
> If you want the bitmap, paint it to a canvas via a video element.

Won't that still create a round-trip of generation loss?

https://en.wikipedia.org/wiki/Generation_loss#Transcoding

**Comment by fippo** [comment]
This particular case was solved a while ago by [MediaStreamTrackProcessor](https://developer.chrome.com/docs/capabilities/web-apis/mediastreamtrack-insertable-media-processing?hl=en) no?

**Comment by BlobTheKat** [comment]
> This particular case was solved a while ago by [MediaStreamTrackProcessor](https://developer.chrome.com/docs/capabilities/web-apis/mediastreamtrack-insertable-media-processing?hl=en) no?

Neat, didn't see that! Can't wait to start using it for my apps in... ~4 years?

**Comment by bradisbell** [comment]
@BlobTheKat Yeah, that's assuming it even gets built before someone decides to kill the spec because there's only one implementation (Chromium).  (e.g. https://github.com/w3c/mediacapture-main/issues/958 ... even if something is marked "at risk", you can bet that nobody is going to bother with it at that point.)  At the moment, there's debate as to whether to even allow the track processor for audio.  (https://github.com/w3c/mediacapture-transform/issues/29)

This is the nature of it.  We benefit from all this platform development, but give up a lot of influence over it in the process.

**Comment by youennf** [comment]
Safari latest beta supports track processor and video track generator, as standardized. Please have a try.

**Comment by BlobTheKat** [comment]
> Safari latest beta supports track processor and video track generator, as standardized. Please have a try.

It will still be a few years before that version and above have a large enough market share to make this a viable option, not even to mention we're still waiting on firefox...

**Comment by JamesTheAwesomeDude** [comment]
> Neat, didn't see that! Can't wait to start using it for my apps in... ~4 years?

> It will still be a few years before that version and above have a large enough market share to make this a viable option, not even to mention we're still waiting on firefox...

Just for the comfort of anyone stumbling across this thread in the future, this is being tracked browser-side at https://bugzilla.mozilla.org/show_bug.cgi?id=1749532
