### ISSUE TITLE
Support retrieving output device channel count

### ISSUE THREAD

**Issue by rivkabr** [w3c/mediacapture-main#332]
When selecting a specific output device to use (one of the devices returned from the enumarateDevices method), there is currently no way to know how many channels this device has.
This is important for applications that want to able to route the sound to specific channels.
A suggested implementation for this could be to add the channel count as an attribute of DeviceInfo.

**Comment by dontcallmedom** [comment]
The possibility of getting the capabilities of output devices was discussed in https://github.com/w3c/mediacapture-main/pull/211 where the idea was to bring this as part of a separate [audio output spec](http://w3c.github.io/mediacapture-output/); I don't know what progress if any there has been toward that. @joeberkovitz  ?

**Comment by alvestrand** [comment]
Closing as "later" - we won't get to this in version 1.
