### ISSUE TITLE
Make ended event a simple event

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-main#338]
Per discussion in #337 the ErrorEvent is a problem in that it can't be implemented as specified, due to a name clash with HTML.

The only user of ErrrorEvent is to provide an optional error on the "ended" event; so far, nobody's suggested text that says when we would include such an error.

Suggestion: Make the "ended" event a simple event, and remove ErrorEvent from the spec.
There are no known implementations at the moment.

**Comment by stefhak** [comment]
@alvestrand Your suggestion makes total sense IMO.

**Comment by elagerway** [comment]
Dom has volunteered to submit a PR on this.
