### ISSUE TITLE
originIdentifier is unused

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#339]
With the move of *request permission* to the permissions API, the variable `originIdentifier` is unused in the [getUserMedia algorithm](http://w3c.github.io/mediacapture-main/getusermedia.html#dom-mediadevices-getusermedia).

**Comment by jan-ivar** [comment]
Also unsure why we're adding a normative dependency to the permissions API. Does that mean the permissions API is required to implement in order to implement getUserMedia?

**Comment by alvestrand** [comment]
It gave us a language to talk about our permissions model without inventing new stuff.
The integration was a response to a "how do we relate" question.

**Comment by alvestrand** [comment]
@martinthomson I think this language was proposed by you. Comments?

**Comment by martinthomson** [comment]
I didn't write the text, and it's the first I've seen it.  It seems like we need to define this in terms of a [permissions storage identifier](https://w3c.github.io/permissions/#permission-storage-identifier).  Most likely by placing the top-level context in the optional bit.

**Comment by dontcallmedom** [comment]
@adam-be was the one who added the text in 2515dc8ffd56bd179189282fa9f872d2d1641d3e fwiw

**Comment by alvestrand** [comment]
Still 9 references that are not specific. Dom to take action to list these.

**Comment by dontcallmedom** [comment]
@alvestrand 's comment was meant for https://github.com/w3c/webrtc-pc/issues/337

**Comment by alvestrand** [comment]
Closed by #349
