### ISSUE TITLE
With single camera, calling getUserMedia twice causes PermissionFailure.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#352]
A [commit](https://github.com/w3c/mediacapture-main/commit/049fd00f87f9ed39a642826fb3ae521cf0e49bb2) from a little over a month ago broke the [`getUserMedia`](http://w3c.github.io/mediacapture-main/getusermedia.html#dom-mediadevices-getusermedia) algorithm here (step 6.3):

> [Retrieve the permission state](http://w3c.github.io/mediacapture-main/getusermedia.html#dfn-retrieve-the-permission-state) for all candidate devices that are not attached to a `live` MediaStreamTrack in the current browsing context. Remove from the set any device for which the permission state is "denied".
> 
> If the set is now empty, jump to the step labeled *Permission Failure* below.

For users with only one camera, the `set` will always be empty here if a page already holds an active track when it calls `getUserMedia`, resulting in permission failure.

**Comment by jan-ivar** [comment]
Even when the set is non-empty, it's become impossible to request the same camera twice.

**Comment by jan-ivar** [comment]
We probably also want to rewrite this to use `let` language like we do elsewhere.

**Comment by martinthomson** [comment]
I don't think that this is right.  If you have a single camera that has an active track, then it is not in the set of devices for which permission retrieval happens, and it therefore remains in the set.

It could be clearer though.

**Comment by jan-ivar** [comment]
@martinthomson Aha, `set` refers to `finalSet`. Yes that's what confused me. I read it as a self-contained sentence where 'set' referred to ''all candidate devices that are not attached to a live MediaStreamTrack in the current browsing context.".

Should be simple to fix.

**Comment by alvestrand** [comment]
Jan-Ivar, you're parsing it wrong.

Remember - the set is all devices that can be considered.

Text:
Retrieve the permission state for all candidate devices that are not attached to a live MediaStreamTrack in the current browsing context. Remove from the set any device for which the permission state is "denied".

The result of retrieval is not called a set; the only thing called a set around here is "finalSet".

Agree that it is better formulated as 

Retrieve the permission state for all devices in <finalSet> that are not attached to a live MediaStreamTrack in the current browsing context. Remove from <finalSet> set any device for which the retrieved permission state is "denied".

The point of the paragraph is to fail early when the user has already stored a denial for the device in that context; respect the user's choice and don't ask again.

I'll make a PR.

**Comment by jan-ivar** [comment]
Yes I parsed it wrong. Not to beat a dead horse, but the text retrieves the permission state from a subset. I genuinely thought `set` referred to that subset, so thanks for clarifying.

**Comment by jan-ivar** [comment]
So if "set" refers to `finalSet`, then this step prunes tracks from `finalSet`, but only jumps to *Permission Failure* if `finalSet` ends up empty...

That seems wrong. For example: If a site calls `getUserMedia({video:true, audio: true})` and the user has previously blocked the site from accessing their microphone, then the above step would prune away all audio tracks, leaving only video tracks in `finalSet`.

This makes it impossible, four steps later, to satisfy this: "The provided media MUST include precisely one track of each media type in requestedMediaTypes from the `finalSet`." - because no audio tracks remain in `finalSet`.

It should probably have jumped to *Permission Failure* in this case.

**Comment by alvestrand** [comment]
The algorithm's not well written for selecting two devices of different types. It would be easier to follow if it was written to select one device of one type, and wrapped inside another algorithm that says "now run the selection algorithm for both audio and video, combining the results in the following manner".

**Comment by alvestrand** [comment]
PR updated.
