### ISSUE TITLE
site A calling getUserMedia grants permission to site B.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#354]
A [commit](https://github.com/w3c/mediacapture-main/commit/bbdee2433051107e597a4fbd277b6d619113ac54) from a month ago changed the [getUserMedia algorithm](http://w3c.github.io/mediacapture-main/getusermedia.html#dom-mediadevices-getusermedia)'s step 7:
> [Request permission](http://w3c.github.io/mediacapture-main/getusermedia.html#request-permission) for use of the devices, while considering all devices attached to a `live` MediaStreamTrack to have permission status "granted", resulting in a set of provided media.

Putting aside https://github.com/w3c/mediacapture-main/issues/350, taken literally, this allows access to site B if site A has a live MediaStreamTrack.

We probably mean to limit this to `live` tracks in either the same browsing context or the same origin?

**Comment by alvestrand** [comment]
Same browsing context was intended, same as what was stated in step 3. I'll make a PR to repeat it.

In Norwegian, there's a term called "som fanden leser bibelen". Please suggest text improvements rather than implying malicious intent.
