### ISSUE TITLE
new getUserMedia language mandates collateral grants.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#355]
A [commit](https://github.com/w3c/mediacapture-main/commit/bbdee2433051107e597a4fbd277b6d619113ac54) from a month ago unilaterally changed the [getUserMedia algorithm](http://w3c.github.io/mediacapture-main/getusermedia.html#dom-mediadevices-getusermedia)'s step 7:
> [Request permission](http://w3c.github.io/mediacapture-main/getusermedia.html#request-permission) for use of the devices, while considering all devices attached to a `live` MediaStreamTrack to have permission status "granted", resulting in a set of provided media.

Putting aside https://github.com/w3c/mediacapture-main/issues/350, this mandates that UAs grant access to a camera if the site already has access to a microphone or a different camera. In essence, this makes any grant of a single device into a grant of all devices, a collateral grant.

Some browsers, like Chrome, already implement collateral grants by default (ask for anything once, and you have access to everything all the time). That's even a persistent collateral grant.

Other browsers, like Firefox, however, quite narrowly restricts grants to individual requests by default (unless the user explicitly chooses "Always Allow"). By restricting grants to individual requests, Firefox users effectively also restrict grants to specific devices (as long as they don't choose "Always Allow").

For instance, this means that in Firefox, users can grant permission to their microphone, but deny permission to their camera, and still hopefully participate in a conference call as an audio-only participant.
 
With this new language, it is not possible for Firefox to maintain or contemplate per-device permission.

The spec here is impinging on individual browser's permission models, and this change has apparently had no discussion.

**Comment by jan-ivar** [comment]
Sorry, I appear to have misread the sentence. The language is explicitly per-device, so my concerns seem unfounded. Closing.

**Comment by martinthomson** [comment]
Note that this does prevent a browser from limiting access to a device based on constraints.  For instance, a browser can't give access to a camera with the flash off without also allowing the site to later acquire the camera with the flash on.

**Comment by jan-ivar** [comment]
Yeah, but are we talking potential permission prompts on `track.applyConstraints()` now? Goody, then we can fold that under `request()` too. What a versatile API. ;)
