### ISSUE TITLE
Specify relation between return from getConstraints and constraints argument

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-main#360]
The current constrainable-pattern getConstraints() text says:

"The getConstraints method returns the Constraints that were the argument to the most recent successful call of applyConstraints(), maintaining the order in which they were specified. Note that some of the optional ConstraintSets returned may not be currently satisfied. To check which ConstraintSets are currently in effect, the application should use getSettings."

I think we should specify that what's returned is the semantic equivalent of what was passed in, as seen from the browser. When implementing this, I found that it was onerous to preserve the exact form passed in. In particular:
- Unrecognized constraints are stripped away by the parser. We shouldn't have to return them.
- Since { width: { ideal: 570 }} and { width: 570 } are semantically identical, we should either be free to return either form, or we should require that the simpler form be returned.
- Same for { deviceId: [ "foo" ] } and { deviceId: "foo" }

Suggested modification:

"The getConstraints method returns a set of constraints that is semantically equivalent to the argument to the most  recent successful call of applyConstraints(), maintaining the order of "advanced" elements that was specified. Note that...."

**Comment by alvestrand** [comment]
@burnburn might want to take a look

**Comment by stefhak** [comment]
I see no issue in moving forward with Harald's suggestion. I see no point in having to return _exactly_ what was passed in rather than something that is semantically equivalent.
BTW, I assume that omitting an unrecognized constraint is considered being "semantically equivalent".

**Comment by alvestrand** [comment]
@stefhak I think so too - the invariant should be that track.applyConstraints(track.getConstraints()) should lead to "no change in configuration".

**Comment by jan-ivar** [comment]
> Unrecognized constraints are stripped away by the parser. We shouldn't have to return them.

This part is implicit in WebIDL and dictionaries, thus shouldn't need any language change IMHO.

As to your other points, I'm not so convinced, because that normalizing is not done by WebIDL.

Can't you simply store the dictionary before you normalize it? That's what [I'm doing](https://bugzil.la/1213517).

**Comment by jan-ivar** [comment]
That said, due to our spec's novel use of dictionaries in unions, what I get back from

```js
navigator.mediaDevices.getUserMedia({video: true})
.then(s => console.log(s.getConstraints());
```
I think would surprise most people: 
```
{
  "deviceId":{},"echoCancellation":{},"facingMode":{},"frameRate":{},"height":{},
  "mediaSource":"camera","mozAutoGainControl":{},"mozNoiseSuppression":{},
  "viewportHeight":{},"viewportOffsetX":{},"viewportOffsetY":{},"viewportWidth":{},
  "width":{}
}
```

Note that this is the product of Mozilla's WebIDL compiler, and no special code on my part.

So perhaps preserving the literalness of this is of little value.

**Comment by jan-ivar** [comment]
> "The getConstraints method returns a set of constraints that is semantically equivalent to the argument to the most recent successful call of applyConstraints()

I think this needs to be "the most recent successful call of applyConstraints() *or getUserMedia()*", because we want to be able to see the initial settings from gUM, right?

**Comment by alvestrand** [comment]
The particular situation I ran into was that our IDL compiler is written with the assumption that dictionaries don't survive iteration of the event loop. So I have to store it somewhere else, and it seems natural to use a format that is easy for C++ to access.

The distinction between the two forms

{ width: 45 }
{ width: { ideal: 45 }}

and

{ deviceId: "foo" }
{ deviceId: ["foo"]}

is purely syntactic, not semantic. so my C++-storage-form had unified them.
Now, with getConstraints, I need to reverse them (because I can't keep the dictionary around), and it seems inconvenient to remember syntactic sugar I've thrown away, but easy to return the simpler form.

The language I suggested would allow what you're returning too, although I agree it seems "noisy" when seen by the user.

Agree fully on "the most recent successful call of applyConstraints() or getUserMedia()", perhaps even "the most recent successful invocation of the applyConstraints algorithm" or whatever the correct phrase is, in case we define a third function that applies constraints.

**Comment by burnburn** [comment]
I'm okay with this direction as long as @alvestrand and @jan-ivar agree.  Regarding "semantically equivalent", I would prefer language such as Harald suggested later:  'track.applyConstraints(track.getConstraints()) should lead to "no change in configuration".'

**Comment by jan-ivar** [comment]
wfm.

**Comment by alvestrand** [comment]
"no change in configuration" is a necessary but not sufficient description .... what should not change is the limits within the platform is permitted to modify the configuration (max/min/exact) and the preferences the platform is encouraged to consider (ideal). Just saying "no change in configuration" could lead people to believe that as long as the result of getSettings() doesn't change, all is well - which is not quite what was intended.

But I'll leave that to the language drafting. I think Jan-Ivar and I are in agreement now!

**Comment by jan-ivar** [comment]
Yes I've come around.

**Comment by burnburn** [comment]
In writing the PR for this I (re-) discovered that our long-ago change to use Select Settings only when applyConstraints() is called has effectively eliminated the possibility for the platform to change the settings on its own as long as the constraints continue to be satisfied, which does not match the original intent of constraints.  It is this which is tricky to write in the PR since we do not have a definition anywhere of what "currently-active constraints" would mean.  I will try to write a PR that sidesteps this issue.

**Comment by burnburn** [comment]
Thinking further on this, I consider it sad that we would no longer be returning the actual constraints passed into gUM or applyConstraints().  I like the idea that I could get the actual constraints I passed in, for example to be used in a graphical constraint-picker.  The user selects some constraints and clicks 'apply'.  When the user returns to this dialog later it would be nice to be able to configure my gui based on getConstraints() and have it be the same as what the user last configured.

**Comment by alvestrand** [comment]
Hmm..... would the following work?

somewhere under "operation":
"When external events happen that cause the UA to desire a change to the settings of a track, the UA can run the Select Settings algorithm again and apply the results at any time.
If this results in not being able to satisfy the constraints, the UA MUST fire the "overconstrained" event."

"Examples of things that might cause such events are lightning condition changes, network congestion, capture devices being shared by other tracks, or ...."

(For consistency, we should start sending black/silence when this happens. I don't think that's very user-friendly, however - sending out-of-constraints results might be more useful for the user.)

**Comment by alvestrand** [comment]
Current settings are returned with getSettings(). (and it has turned out not to be trivial to implement...)

**Comment by burnburn** [comment]
The re-running of the Select Settings algorithm (dynamic settings changes) is a different topic.  However, on this topic see my comments above regarding the problem of not having a definition for the "currently active constraints" other than the *newConstraints* argument to the applyConstraints algorithm.

**Comment by burnburn** [comment]
The new side issue mentioned above about the UA being able to change settings on the fly now has its own issue #394.

**Comment by burnburn** [comment]
Regarding getConstraints and the constraints given to gUM and applyConstraints(), I could use help from @jan-ivar .  The issue is figuring out how to be precise about what "semantic equivalence" would mean for different JavaScript objects passed in as arguments and returned from getConstraints().  In trying to write a PR for this I have been unable to find any approach that does not involve trying to enumerate equivalences not only of bare and ideal but also the various ways that objects can be equivalent.  Specifying the bare/ideal and any other constraint-mechanism-specific equivalences is fine, but I don't want to have to try to precisely enumerate equivalences among JavaScript objects that map to to the same WebIDL structure.  Any thoughts, Jan-Ivar?

**Comment by jan-ivar** [comment]
@burnburn You don't have to. As I [mentioned](https://github.com/w3c/mediacapture-main/issues/360#issuecomment-223404239), WebIDL dictionaries are secure normalized copies of known properties only, so there's no access to the full JavaScript object that was passed in (unknown things do not survive). This is already well-defined, as `getConstraints()` returns a dictionary of the same type.

(Btw. for this reason, a graphical constraints-picker would probably want to store its composition outside of the track anyway.)

Wouldn't it suffice to say something like: "UAs MAY return normalized constraints with the identical effect in all situations as the applied constraints" ? Programmers will be reading this after all.

**Comment by jan-ivar** [comment]
For reference, here is WebIDL's [JS to dictionary conversion algorithm](https://heycam.github.io/webidl/#es-dictionary).
