### ISSUE TITLE
Example image text is hard to read

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/mediacapture-main#361]
The white text on coloured boxes in the diagrams in §5 is hard to read. Please could you check the colour contrast and text size for accessibility?

For example, the second diagram, boxes next to B and Y are hard to read (small fuzzy text); the white text on a yellow callout box in the third diagram is hard to read (low contrast). Both problems are significantly present in the 5th and 6th diagrams, in some cases both in the same box.

In some cases black on white text is very small too.

This is not a full accessibility review, just a couple of problems that I spotted quickly and hopefully can easily be resolved.

**Comment by elagerway** [comment]
PR Merged

**Comment by nigelmegitt** [comment]
Thanks, that's much clearer!
