### ISSUE TITLE
Mismatch between "latest draft" and actual latest draft

### ISSUE THREAD

**Issue by annevk** [w3c/mediacapture-main#364]
As @domenic discovered in https://github.com/w3c/mediacapture-main/pull/362 it seems like while there's a latest editor's draft at https://w3c.github.io/mediacapture-main/ that's not really the latest draft. Can that perhaps be changed somehow, e.g., by making gh-pages the new master branch?

**Comment by fluffy** [comment]
Not unless we move to a model where before we merge a PR, we make sure we have agreements of the authors to merge the PR. On some other specs we do that by having them review and r+ the PR then make it. Instead the team has been using a model of making potential changes on the master and when people are OK with them, publishing them on web pages. The reasons for this had to do with on going court case and the assumption that if something is publicly published at https://w3c.github.io/mediacapture-main/ and a given person is listed as an author, then that person has actually read it.

**Comment by domenic** [comment]
I tend to agree that merging a PR in any other repository implies sign-off from the custodians of the repository.

In the meantime maybe we should be pointing people to https://rawgit.com/w3c/mediacapture-main/master/getusermedia.html which is always up to date?

**Comment by annevk** [comment]
But also inaccurate? It's unclear how non-approved commits are handled.

**Comment by fluffy** [comment]
Agree that a reviews + a PR and then it is merged is a more normal (and probably better) work flow. We just ended up with this one for a variety of reasons long ago that predate the use of git. If mistakes are found on master they just get fixed before it gets published.

**Comment by stefhak** [comment]
We've been working according to this model for a long time now as @fluffy says. I don't think we should change now.

**Comment by annevk** [comment]
Let me just note that I don't really find that a responsible response. We've identified a problem with the way you are operating. Namely that it is unclear that when a PR is merged that it actually means the change is made and there's no way for contributors to really know what will happen after that, other than following the commit history of a different branch.

No other standard follows this pattern or has this problem that I know of. Please reconsider.

**Comment by stefhak** [comment]
Are there any concrete cases when this has been identified to be a problem?
I can't remember a PR merged to master having been removed before going to gh-pages (but often there are some edits done - to stuff introduced by the PR or elsewhere - to make the document more consistent).

**Comment by domenic** [comment]
Yes. HTML is waiting to reference media capture for the recent changes in https://github.com/w3c/mediacapture-main/pull/362, which we were to understand (via discussions in https://github.com/w3c/mediacapture-main/issues/353) had consensus, whereas it seems like it does not, and the acceptance of that PR is just some kind of provisional work-mode business. That is a problem.

**Comment by stefhak** [comment]
I see the problem. I'd definitely say there is consensus for #362, but I understand the problem to not be able to refer to a draft with it merged. We should get a new Editor's draft out ASAP.

**Comment by stefhak** [comment]
A new draft is out, dated version at https://w3c.github.io/mediacapture-main/archives/20160624/getusermedia.html (or look at http://w3c.github.io/mediacapture-main).

**Comment by domenic** [comment]
Thank you. I pushed the change to HTML in https://github.com/whatwg/html/commit/688df431630fe7d9a0518e402c1f1543d0f493a0 so allowusermedia is now defined there: https://html.spec.whatwg.org/multipage/embedded-content.html#the-iframe-element

**Comment by stefhak** [comment]
Thanks, that looks good!
