### ISSUE TITLE
WebIDL requires constraints on getUserMedia to be optional

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-main#366]
We've encountered this before: A trailing dictionary argument with no required members MUST be optional. The argument to

        <dt>Promise&lt;MediaStream&gt; getUserMedia( MediaStreamConstraints
        constraints)</dt>

isn't.

I'm not happy with this, because we have to make it optional and then add prose saying it's not (omitting it will result in a TypeError, per the procedure already present in the text), but I guess we have to follow the rule.

**Comment by bzbarsky** [comment]
You don't need any extra prose here, right?  If it's optional, not providing it will produce the same dictionary as providing `{}` would, and then your existing prose would cause an exception to be thrown, afaict.

**Comment by alvestrand** [comment]
The extra prose that could be useful is "the word "optional" occurs in the WebIDL due to WebIDL rules, but the arugment MUST be supplied". This can be put in the text next to "If requestedMediaTypes is the empty set, return a promise rejected with a TypeError." (section 10.2.1, 3rd bullet of getUserMedia).
