### ISSUE TITLE
Remove 'advanced' constraints from the spec.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#369]
Chrome Canary now supports [modern spec constraints](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Parameters) with *getUserMedia*.

Finally, no-one needs to learn the semantics of the `advanced` array anymore.

Two years have passed, and I have yet to see a pattern that requires the advanced array on initial encounter.

If it's redundant, we should remove it.

**Comment by alvestrand** [comment]
Converting from previous usage often means a mapping of the old "optional" to the new "advanced".
So there's significant usage-by-proxy.

We can add use counters.

**Comment by fluffy** [comment]
Jan-ivar said this when the WG agreed to put it in advanced -  the WG disagreed with you. I am on interested in re having this whole discussion again - and further delays this already late spec -  unless something has changes that allows us to meet all the use cases without it. I don't see anything has changed.

**Comment by jan-ivar** [comment]
@fluffy I can appreciate that, but what use-case needs it again? @alvestrand Wouldn't all usage-by-proxy end whenever support for non-spec constraints is removed? Whenever you force people off those, they'll have to upgrade to `ideal`, likely fixing some logic errors of theirs in the process, given how hard it was to write preferences the old way without mistakes.

**Comment by elagerway** [comment]
The chairs are not seeing consensus needed to proceed on this one, closing for now.
