### ISSUE TITLE
Restore the active/inactive events on MediaStream

### ISSUE THREAD

**Issue by foolip** [w3c/mediacapture-main#370]
They were removed in https://github.com/w3c/mediacapture-main/pull/291

This came up [on blink-dev](https://groups.google.com/a/chromium.org/d/msg/blink-dev/EHy8zm0eVy0/Jfg0vkVNAAAJ) and it appears as if 3 of 4 browser engines support these events, Gecko being the exception.

Given that the `active` attribute itself is still present, the events don't seem to add much in terms of an implementation burden. IIUC, [the problem](https://lists.w3.org/Archives/Public/public-media-capture/2015Nov/0012.html) was about the timing of the attribute changing and the events firing. Assuming that the events are brought back, I see two options:
* Always change state and fire the corresponding event in the same task.
* Always queue a task to fire the event after the state change. This is what happens for HTML media elements, and it means that events can arrive when the state has already changed again.

@adam-be @alvestrand

**Comment by jan-ivar** [comment]
I read no persuasive arguments in the blink thread about why new browsers should implement this (these are JS-initiated changes, so no need to tell JS about them). All I read were concerns about removing them in Chrome, which is a Chrome issue, not a spec issue.

Not to be bleak, but once Chrome pivots to tracks, I think devs will have bigger fish to fry.

Once RTCPeerConnection pivots to tracks, you may no longer care what stream a track is in, since it has no effect on RTCPeerConnection.

Open to hear use-cases where they matter.

**Comment by foolip** [comment]
It's already in 3 out of 4 browser engines. Does anyone have a plan to remove the events? If not, then the fastest path to interop is pretty clear.

**Comment by jan-ivar** [comment]
3 out of 5.

**Comment by alvestrand** [comment]
@pthatcherg might want to comment.
This is a far less invasive deprecation/removal than the removal of pc.addStream, which we had strong WG consensus on at the last meeting.
Extra events  added by browsers is also completely orthogonal to spec conformance.

**Comment by foolip** [comment]
@guidou added use counters, let's wait for them to reach stable:
https://www.chromestatus.com/metrics/feature/timeline/popularity/1415
https://www.chromestatus.com/metrics/feature/timeline/popularity/1416

**Comment by pthatcherg** [comment]
I agree with Jan-Ivar: once we move to track-based everything, the stream state doesn't really matter.  And from reading the Chromium thread, it sounds like the removal is being held up by one product using it.  Chromium is free to leave it around until that one product no longer uses it (as we do with some other more serious non-compliant things), but that doesn't mean we should leave it in the spec.

I'm in favor of keeping it removed.

**Comment by foolip** [comment]
Is the readonly `active` attribute also in the category of stream state that doesn't matter, or does it still make sense with track-based everything? If it does make sense, is there a simple replacement for the events?

```JavaScript
function activeChanged() {}
stream.addEventListener('active', activeChanged);
stream.addEventListener('inactive', activeChanged);
```
becomes
```JavaScript
function activeMayHaveChanged() {}
stream.getTracks().forEach(function(track) {
  track.addEventListener('ended', activeMayHaveChanged);
  // and mute/unmute events?
});
stream.addEventListener('addtrack', activeMayHaveChanged /* and figure out which track is new and add listeners */);
stream.addEventListener('removetrack', activeMayHaveChanged);
// replace addTrack and removeTrack on MediaStream.prototype since those don't fire events?
```
I'm just guessing here, I've never used these APIs and want to know what advise a deprecation should give if they're to be removed.

**Comment by jan-ivar** [comment]
It doesn't matter, is how I read @pthatcherg. Your polyfill is about right, except it's `readyState`, so do: 

```js
var active = stream.getTracks().some(track => track.readyState != 'ended');
```

**Comment by foolip** [comment]
So, was it just an oversight that the `active` attribute wasn't removed as well? It looks like Gecko doesn't have it.

**Comment by jan-ivar** [comment]
@foolip Good question. It does seem redundant, doesn't it? You're correct that Gecko doesn't have it yet.

**Comment by foolip** [comment]
If nothing else it seems like these things should go together.

**Comment by elagerway** [comment]
The chairs are not seeing consensus needed to proceed on this one, closing for now.

**Comment by foolip** [comment]
@ShijunS, can you comment on Edge's plans regarding the active/inactive events and the active attribute?

**Comment by ShijunS** [comment]
@foolip, implementation wise, we will keep the events for now.  We will consider adding telemetry point for the usage of the events and decide whether to deprecate them down the road.  The stream object will be consumed by media element, web audio, recorder, etc., in addition to RTC.  I expect keeping the active attribute will be beneficial to developers in those areas although we don't have data yet on the usage patterns.

**Comment by foolip** [comment]
I'm adding a use counter for the `active` attribute in https://codereview.chromium.org/2128593003/ in case it'll be useful to have later on. (It looks strange to me to keep the attribute but remove the events.)
