### ISSUE TITLE
Consider splitting Spec into two: MediaStream{Track} and GetUserMedia() parts.

### ISSUE THREAD

**Issue by miguelao** [w3c/mediacapture-main#374]
The (non-normative) [introduction](https://www.w3.org/TR/mediacapture-streams/#intro):  
> This document defines APIs for requesting access to local multimedia devices, such as microphones or video cameras.
>
> This document also defines the MediaStream API, which provides the means to control where multimedia stream data is consumed, and provides some control over the devices that produce the media. It also exposes information about devices able to capture and render media.

Since there are now multiple ways to produce `MediaStream`s beyond the "access to local multimedia devices", could we consider splitting these two pieces of specification into two documents? (Or is this crazy?)

**Comment by alvestrand** [comment]
No, we won't do that. Too late in the process.
