### ISSUE TITLE
Should devicechange fire once or twice when I insert a USB cam with mic?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#375]
The spec appears conflicted on this:

Under [devicechange](https://w3c.github.io/mediacapture-main/getusermedia.html#event-mediadevices-devicechange) it says: *"[Fired when] the set of media devices, available to the User Agent, has changed."*

i.e. when the ***set*** changes. This seems to allow an implementation to add a cam and a mic to the ***set*** and fire 1 event.

But [elsewhere](https://w3c.github.io/mediacapture-main/getusermedia.html#mediadevices) it says:

*"When a new media input or output device is made available, and if the permission state of the "list-devices" permission is "granted", the User Agent MUST queue a task that fires a simple event named devicechange at the MediaDevices object. These events are potentially triggered simultaneously across browsing contexts on different origins; user agents can add fuzzing on the timing of events to avoid cross-origin activity correlation."*

... which seems to normatively dictate two events when e.g. I insert my Logitech camera which has both a camera and a microphone on it.

Oddly, the same paragraph allows for time-shifting, so there's apparently no urgency in firing these events, so the sole purpose of firing two events would seem to satisfy someone who is counting device additions and removals (which seems like a poor reason, given that you won't know whether it was an addition or a removal without comparing the list against a previous pull of the list, at which point you'd be able to cope with multiples as well).

Was this our intent, and is this the best behavior? We seem to use the term "device" loosely, so my guess is no. I vote we allow implementations to optimize here and fire one event in this case.

**Comment by jan-ivar** [comment]
Also the "can" should perhaps be a normative "MAY"?

**Comment by burnburn** [comment]
+1 to allowing implementations to fire one or two events, their choice, in this situation.  I don't believe the intention was to be able to count device changes but rather to be able to deal with changes that have occurred.

Yes, I think the "can" should be a "MAY".

Can you please suggest some precise wording changes that also make clear to developers that such an event could mean more than one device has changed?

**Comment by alvestrand** [comment]
Fixed by #376
