### ISSUE TITLE
Clearly mark the "Implementation Suggestions" section as normative or not

### ISSUE THREAD

**Issue by jyasskin** [w3c/mediacapture-main#390]
https://w3c.github.io/mediacapture-main/getusermedia.html#implementation-suggestions does not have a clear "This section is non-normative." indication, and the Conformance section says

> As well as sections marked as non-normative, all authoring guidelines, diagrams, examples, and notes in this specification are non-normative. Everything else in this specification is normative.

which says the Suggestions section is normative. However, the [change log for its addition](https://w3c.github.io/mediacapture-main/getusermedia.html#june-5-2012) says it's non-normative, and it'd be very strange for a section titled "suggestions" to actually hold requirements.

@jan-ivar's citing the section as normative in https://github.com/w3c/mediacapture-main/issues/387#issuecomment-245021280, so I think the decision either way will be controversial.

**Comment by jan-ivar** [comment]
@jyasskin I didn't mean to suggest it was normative, only that it sheds light on the thinking behind related normative language (specifically a concern about privacy around device accessibility, that non-stored permission ends when all tracks stop).

**Comment by alvestrand** [comment]
@jyasskin the authors thought it was non-normative when written. I think adding "implementation suggestions" to the list in the "Conformance" section should the right thing to do. But this text is generated from ReSpec boilerplate - it's not actually present in the source. Calling out to @dontcallmedom for advice here.

**Comment by dontcallmedom** [comment]
There is `<section id='conformance'>` where we can add anything we want to add to the conformance section.

In this specific case, I think we probably need to distinguish more clearly what's purely suggestions from what is normative, and put what is clearly normative in a section with a less confusing name.

**Comment by alvestrand** [comment]
Before marking it as non-normative (by merging PR #395), we need to review the section to make sure all normative-sounding statements are indeed stated normatively elsewhere - this section should either point to those statements or delete the text.

**Comment by burnburn** [comment]
FYI, review will start after we conclude on PR #411 sometime next week.
