### ISSUE TITLE
Exception discrepancy among filter nodes

### ISSUE THREAD

**Issue by a2sheppy** [w3c/mediacapture-main#393]
The specification says that BiquadFilterNode should throw NotSupportedError if the specified arrays aren't the same size. IIRFilterNode, on the other hand, is described as throwing InvalidAccessError.

I didn't check to see if other nodes differ as well, but these should be the same, for consistency. It would make error handling easier in code that uses multiple filter types.

**Comment by stefhak** [comment]
This issue may have been filed on the wrong repo - I can't remember there is anything about filters in mediacapture-main.

**Comment by alvestrand** [comment]
Closing because I can't see how it's relevant here.
