### ISSUE TITLE
Add text to extensibility for consumer of MST

### ISSUE THREAD

**Issue by burnburn** [w3c/mediacapture-main#400]
From TPAC:  For the extensibility section, when you define a new consumer you need to define how a MediaStreamTrack will render in the various states in which it can be -- ended, muted, etc.

**Comment by burnburn** [comment]
I'm not sure this text belongs in the gUM spec after all.  The extensibility section is about extending the contents of the Media Capture spec, not about defining new consumers of MSTs.  I could add a section for that, but it would be very different in character from the rest of the section.

**Comment by alvestrand** [comment]
Might belong as a new top level (or second level) section - it's a different topic than extending GUM, it's advice to users of the MST interface.
