### ISSUE TITLE
Allow ondevicechange to be fired before permission is granted or any device is opened

### ISSUE THREAD

**Issue by ShijunS** [w3c/mediacapture-main#402]
As part of the MediaDevices interface, the ondevicechange event is to inform the app to enumerate capture devices.  Given device enumeration is independent from whether there is a device in use or not by the current UA, firing the event should not be restricted either.  

As one use case, assuming we have a desktop machine without any capture device to start with, app can decide not to call gUM and hide the related features.  Once a device is plugged in, app can respond to the ondevicechange event to expose related features, such as a profile photo button, or a voice recording button, etc.  The Edge implementation today supports the use case.  The spec allowed it as well prior to the 20160423 version.

**Comment by jan-ivar** [comment]
That was https://github.com/w3c/mediacapture-main/issues/333.

**Comment by foolip** [comment]
I brought up a similar issue in a blink-dev intent thread:
https://groups.google.com/a/chromium.org/d/msg/blink-dev/s-w44wOMzqs/tEd_YNjkAAAJ

What was not discussed explicitly in https://github.com/w3c/mediacapture-main/issues/333 is the connection between the devicechange event and enumerateDevices. If the devicechange event is normally fired when the result of enumerateDevices would change, then merely suppressing the doesn't help if the same change can be observed by polling enumerateDevices. The small difference in timing accuracy seems very unlikely to matter.

**Comment by jan-ivar** [comment]
@foolip Good point that devicechange events are easily polyfilled with enumerateDevices. We should normalize the two features so people won't ever need to do that.

Someone suggested that, as an API cleanliness point, enumerateDevices() should return the old sequence before the event is fired anyway, and only calls after the event has fired should get the new sequence.

To extrapolate from that, if pages without permission never get the event fired, perhaps enumerateDevices should always return the old sequence if called more than once per page?

As counter-intuitive as it sounds, this would at least put the two features in the same basket, without deciding on the question in this issue one way or the other. I'm trying to avoid the "prevention had a loophole, so we shouldn't try" argument. ;)

@ShijunS Is it the case where users have no device to grant that is the problem? Would it help to make an exception for the zero to one devices case?

Other ideas:
 - Always fire on the active tab even without permission.
 - Apply a timing fuzz of several seconds of the event (and refreshed enumerateDevices results) on pages without permission. A site with permission could perhaps get somewhat higher timing precision.

**Comment by ShijunS** [comment]
@jan-ivar 
> Is it the case where users have no device to grant that is the problem?

Yes, for the use case I mentioned. The gUM() call is typically triggered by user interactions.  If there is no capture device attached, it'd be a bad experience for app to show a button and return an "oops, no device" after user grants the permission. 

> Would it help to make an exception for the zero to one devices case?

I think you meant 0-to-1 per deviceType.  I don't think we should introduce any special case here.  If we allow enumerateDevices already, suppressing (or delaying) the events won't provide any additional benefit or protection.

BTW, I don't like the polyfill approach, given enumerateDevices could potentially activate each hardware devices, although for a very short period of time.  A fast-pace polling through enumerateDevices can add unnecessary burden to the system.  The devicechange event will provide the most efficient trigger, in addition to better developer experience.  I think that is also the intention of the original design.

**Comment by jan-ivar** [comment]
> If we allow enumerateDevices already, suppressing (or delaying) the events won't provide any additional benefit or protection.

@ShijunS I was trying to avoid exactly that argument by aligning the functionalities of enumerateDevices and the devicechange event, since I'd much rather discuss this based on merit.

To move forward on this, we still need to address the concerns in https://github.com/w3c/mediacapture-main/issues/333 somehow I think.

> BTW, I don't like the polyfill approach

I think you misunderstand, I wasn't advocating using a polyfill. On the contrary, I was trying to remove any benefit from writing one. However, I'm digging a bit of a hole, since if users can't trust enumerateDevices, then getUserMedia is next.

**Comment by ShijunS** [comment]
@jan-ivar my bad, must have misread your comment on the polyfill part ;-)

Looking more into #333...

**Comment by ShijunS** [comment]
I like the following option proposed by @dontcallmedom in #333.
> or suggest UAs should fuzz the emission of the events (and their timestamps), possibly as an informative mitigation (in which case we should probably add a note on this in the privacy section as well)

The devicechange event doesn't look like the right place to pioneer a normative restriction, so an informative best practice would be a better fit.

**Comment by martinthomson** [comment]
Here's a more concrete suggestion:

Require that changes to the set of enumerated devices is delayed, and that the result of enumerateDevices is cached for the same period.  This need not be a significant time, just enough to create some uncertainty about cross-origin correlation.  This time should be reduced, perhaps to zero, for both origins with `list-devices` permissions as well as any foreground top-level browsing context (on the basis that connecting a device is analogous to a key stroke in this case).

Personally, I would only make the event/change available immediately to a foreground site and let the rest wait.  You might want to reduce the delay when switching tabs if the delay is significant.

I will note that this has a fairly obvious workaround/attack if it is poorly implemented: reload or make a new realm and call enumerateDevices to get a new value.  Thus, any timing information needs to be stored for origins (and periodically cleansed).

**Comment by foolip** [comment]
Can we spell out the details of the "unexpected correlation of browsing activity" and how any proposed solution will mitigate it? Fingerprinting is very reliable, so any two sites that cooperate can already know to a high degree of certainty that they're seeing the same user. To really confirm, they can both include an iframe from a shared third origin that generates a unique ID, adds it to a cookie/localStorage/IndexedDB, and then postMessages it to the two sites.

Is there anything that can be learned by observing the timing of device changes that cannot already be done?

**Comment by dontcallmedom** [comment]
First, some history of the discussion on devicechange correlation:
* it was part of the [feedback received from the Privacy Interest Group](https://www.w3.org/2016/03/getusermedia-wide-review.html#ping)
* more specifically, it was brought up by @npdoty in this [review of the document](https://lists.w3.org/Archives/Public/public-privacy/2015OctDec/0028.html):

> Particularly if this event will be fired before any permission is granted, it is important that it not be fired simultaneously in all browsing contexts. Sites can use simultaneous firing to correlate browsing activity in different tabs, different windows (including private windows), different browsers, in a way that may be unexpected to the user and undermine other protections they're attempting to implement.

In particular, I think one of the risks this tries to mitigate is if a browser is configured to severely limit leak of information (via fingerprinting, communication with third party origins), this particular correlation would still allow evading these restrictions.

Also, the simultaneous timing of these events can make them usable as correlation traces even if no communication channel can be established at the time of the simultaneous use of Web apps (e.g. offline usage), by comparing them afterwards.

But ideally @npdoty will also chime in on this.

**Comment by foolip** [comment]
The "including private windows" bit is interesting, but at least Chrome's [incognito mode](https://support.google.com/chrome/answer/95464?hl=en) is explicitly not protecting you from "The websites you visit themselves."

For browsing modes that attempts to minimize fingerprinting surface, some limitations on `enumerateDevices()` seems sensible. For browsers in their default configurations, if such limitations wouldn't be enough to fix the problem, which I suspect they are not, then requiring it doesn't seem meaningful.

(Offline scenarios ought not change the picture, as anything that happens can be recorded and analyzed later when online.)

**Comment by jan-ivar** [comment]
@foolip In the current climate, I think there's room for browsers to innovate and experiment with new privacy features, and giving up on fingerprinting outright would make this hard, which I think explains why there hasn't been an official capitulation on the issue. But I speculate.

FYI Firefox's Private Browsing with Tracking Protection is marketed as: *"Some websites use trackers that can monitor your activity across the Internet. With Tracking Protection Firefox will block many trackers that can collect information about your browsing behavior."*

In any case, these features live outside specs, so let's get back to seeing what we need to do to mitigate @ShijunS use-case. @alvestrand and I think we agree on at least the following:

 1. Remove the need for permission in the active tab with input focus (to solve Shijun's case, and based on Martin's [characterization](https://github.com/w3c/mediacapture-main/issues/402#issuecomment-250352996) of USB-fiddling as user input).

 2. Mandate that enumerateDevices() return old data until the event has fired.

The spec already encourages fuzzing the timing on firing of the event, but does not require it.

@alvestrand mentioned to me we might want to restrict fuzzing in the active tab and maybe even tabs with full gUM (not device-info) permission, to solve the use-case where a user yanks their USB camera, and in response to the `ended` event this fires, the JS immediately calls enumerateDevices() to figure out what happened. Returning stale data in that case would be confusing, but maybe that's a separate issue.

**Comment by adam-be** [comment]
> Mandate that enumerateDevices() return old data until the event has fired.

This seems reasonable to not make enumerateDevices() more "powerful" than listening for the event. It also aligns well with how events usually work with state updates and then event fire synchronously in a queued task.

**Comment by adam-be** [comment]
@jan-ivar or @ShijunS, would any of you volunteer to draft a PR when we start converging on a set of needed changes?

**Comment by ShijunS** [comment]
@adam-be, I'll give a shot.

**Comment by adam-be** [comment]
Thanks @ShijunS

**Comment by adam-be** [comment]
Closed by PR #412
