### ISSUE TITLE
Revive createObjectURL?

### ISSUE THREAD

**Issue by foolip** [w3c/mediacapture-main#404]
createObjectURL was removed in 2013:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=23091
7167f7339eccc21c14b575718aefa4def01efb30

However, it is still supported in Chrome, Edge and Firefox, as tested with this code:

``` JavaScript
var stream = new (window.MediaStream || window.webkitMediaStream);
var url = URL.createObjectURL(stream);
console.log(url);
```

Rather than attempting to remove it, bringing it back in the spec may be less effort for everyone involved. Here's how it's spec'd for Blob and MediaSource:
https://w3c.github.io/FileAPI/#creating-revoking
http://w3c.github.io/media-source/#url

**Comment by alvestrand** [comment]
One reason for my strong dislike of createObjectURL is that it prevents mocking of the stream object (for code that could otherwise be debugged and tested without ever making a real stream object).

There are more.

We already have a "backwards compatibility legacy" section - if we dump all the bad ideas we've discarded into that section, we get easier backwards compatibility, but we abandon all hope of eventually leaving the bad ideas behind us.

**Comment by foolip** [comment]
Can you elaborate on the mocking, is this something a web developer would do are is it for unit testing of the implementation?

If it would help inform the decision, we could measure usage in Chrome.

**Comment by alvestrand** [comment]
My personal experience (a couple of years ago) was with trying to write an utility function that kept track of a bunch of streams and how they were connected to a HTMLMedia object.

In order to test this function, I passed it a mock HTMLMedia object and a mock stream, and attempted to run it through its paces.
I could easily mock the "srcObject" attribute on the HTMLMedia object, and detect that it was set correctly - but I could not catch the call to createObjectURL without overriding the method on the global URL object for all usages - which seemed dramatic to me at the time.

I would think usage in Chrome is pretty massive - it's not long ago that we shipped srcObject at all, and I doubt many consumers have converted so far. But use counters are a Good Thing.

**Comment by foolip** [comment]
Adding use counters in https://codereview.chromium.org/2383503002/

I would be very surprised if usage is low enough to justify removal given the current state of near-interop, but if it's not in the way we can just park this issue for a few months until we know.

**Comment by stefhak** [comment]
We had a lot of discussion about this, and decided to remove it. Reasons included:
- it was never fully specced
- implementations did differ
Also, I think it was pre-fixed in all implementations.
I don't think we have strong enough arguments for re-opening this question.

**Comment by foolip** [comment]
Whatever the state of implementations was at the time, they are now unprefixed and appear to work.

**Comment by stefhak** [comment]
Putting the Icebox label on this one. I don't see us doing anything at least until we have some input from the counters added.

**Comment by foolip** [comment]
Internal data from the last 7 days on Chrome Dev channel show usage in chromestatus.com-terms of ~0.04% for `URL.createObjectURL(mediaStream)`, ~0.73% for `URL.createObjectURL(blob)`, and ~1.49% for  `URL.createObjectURL(mediaSource)`.

These numbers will change for stable, and I'm OK waiting for that, but it looks *very* unlikely that all `URL.createObjectURL` variants could be removed, so even if usage of the MediaStream variant would drop to <0.01% it wouldn't seem worthwhile to attempt removal in all three engines already shipping it.

**Comment by stefhak** [comment]
Great to hear some data is coming. I note that only three persons have been involved in this discussion. @foolip would you be willing to take this to the list to get more input?

**Comment by foolip** [comment]
Sure, I've sent https://lists.w3.org/Archives/Public/public-webrtc/2016Oct/0077.html

**Comment by stefhak** [comment]
Thanks!

**Comment by jan-ivar** [comment]
@foolip Just because something is hard to drop doesn't mean it should be in the spec, or is impossible to drop. We do the usual pattern of deprecation warnings, then deprecation errors, and tell devs to move over. There's less to type, so this change should be welcome, and quite compatible. Are those numbers from Chrome? Didn't Chrome just implement srcObject a month ago? Firefox unprefixed srcObject a year ago. Let's give devs some time.

**Comment by jesup** [comment]
Mozilla has always opposed using createObjectURL for WebRTC and MediaStreams in general.  The primary reason is that once you call createObjectURL, you lose any way to track usage of the resource, and must keep it available until the page is destroyed.  This is why we pushed hard for srcObject, and are very glad it's now implemented in Chrome.  createObjectURL was effectively cruft the beginning of the effort.

**Comment by foolip** [comment]
@jan-ivar @jesup, in Gecko, is createObjectURL more problematic for MediaStream than for MediaSource or Blob? Would removing just one variant allow for any simplification?

Let's wait for the numbers from Chrome stable channel, but if they're roughly the same, and no vendor is actively pursuing removal, then things will likely stay the same. (Just deprecation messages don't seem to reliably drive down usage, presumably because in the long tail of sites there's nobody looking at the console.)

**Comment by jan-ivar** [comment]
@foolip Two bad things beat three bad things. I believe [the plan](https://groups.google.com/forum/#!topic/mozilla.dev.platform/wBV5TNDEziU) is to support `srcObject` for all three eventually.

Of those numbers you mention, how many call [revokeObjectURL](https://developer.mozilla.org/en-US/docs/Web/API/URL/revokeObjectURL) correctly? We're fixing bugs by moving people off createObjectURL. Not only is the resource not freed, the camera light stays on.

We told people WebRTC isn't stable, and people signed on knowing they would need to update their code. E.g. How many in the long tail used http?

**Comment by foolip** [comment]
There's no question that this is a bad API, but removing things is hard work and you have to prioritize. Interop problems would be at the top of my list, but if anyone is motivated to get it removed (not just deprecated) in Chrome, Edge or Firefox in a reasonable time frame, then it could prove that it's safe for the remaining two. @jan-ivar, do you plan to remove it from Firefox, and in what kind of time frame?

(The [usage](https://www.chromestatus.com/metrics/feature/timeline/popularity/666) of getUserMedia on insecure origins when it was [removed](https://codereview.chromium.org/1284193003) was ~0.001%.)

**Comment by jan-ivar** [comment]
@foolip Thanks for the usage data on http. Removing things take time, especially when some browsers lag on implementing good alternatives.

I see `webkitGetUserMedia` is almost at ~0.01 yet it's not in the spec. My point is that just existing is not a sufficient criteria to be in a spec. Specs are based on consensus, not just web compat, and sometimes we have to take the long view.

**Comment by jan-ivar** [comment]
We could turn video black-and-white or degrade resolution on sites using `createObjectURL`...

**Comment by jesup** [comment]
We could overlay with a "Time until this stops working" countdown.

**Comment by annevk** [comment]
> [...] sometimes we have to take the long view.

That ends up creating an anti-competitive situation whereby new entrants don't know what's required to support the web platform. So WHATWG and W3C largely too have abandoned that kind of thinking quite a while ago in favor of specifying what is actually required to implement a browser.

If things can be removed after a while, great, but we shouldn't end up in a situation where something is not specified for years just because it was assumed it could be removed.

**Comment by domenic** [comment]
In particular, it's fine to mark things as deprecated, and remove them from specs once they're removed from browsers. But in the meantime, specs need to reflect the reality of what's implemented, not wishful thinking. Not speccing something doesn't make it go away faster; it just creates interop pain and prevents the spec from being useful for implementers.

**Comment by jan-ivar** [comment]
@annevk, @domenic Agree this API has lingered for way long. There's a flip-side though, e.g. we left in the [legacy non-promise version of RTCPeerConnection](http://w3c.github.io/webrtc-pc/#legacy-interface-extensions), and just this week Edge announced they just completed a working version of "WebRTC 1.0", except... you guessed it... with a non-promise API only.

I'm hopeful they'll address this, but it doesn't help that most examples of WebRTC mentioned in questions on SO for example, keep using the legacy non-promise API, even though the authors clearly just wrote it.

**Comment by annevk** [comment]
Hmm that sucks. How is the web-platform-tests story for the promise API? (Good that all examples in the specification use promises, makes it extra weird they just ignored it.)

**Comment by foolip** [comment]
I've tested Edge 14, and `navigator.mediaDevices.getUserMedia` returns a promise, while `navigator.getUserMedia` takes a pair of callbacks. Seems to be in order?

**Comment by stefhak** [comment]
@foolip I guess @jan-ivar is referring to WebRTC APIs (such as createOffer, setLocal).

**Comment by foolip** [comment]
Oh, now I see. Maybe @ShijunS can comment, but it seems a bit unlikely that the existence of the callback variants, clearly marked as legacy, is the reason that promise variants weren't shipped.

**Comment by domenic** [comment]
I don't think the presence or absence of the non-promise versions is what prompted Edge to implement them. Rather, I think it was the need to be compatible with web content in a competitive market. Now imagine if they had to do all that without a spec---then there would be *two* non-promise versions that became part of the web!

**Comment by ShijunS** [comment]
@domenic is largely correct about why we decided to first implement legacy functionalities in WebRTC.  We implemented support to createObjectURL for the same reason.  
However, I don't think createObjectURL should be (re)included into the WG spec. I believe we all wanted the web community to eventually move away from the legacy APIs.  In addition, I expect there will be a lot of nuances to have createObjectURL fully defined and have the created url consumable by all consumer objects.  Also, from implementation perspective, I'm not confident that all existing implementations behave exactly the same for all use cases.  For instance, in Edge, we first implemented srcObject for mediaelement, then realized some sites wouldn't change right away to adopt that, so built an internal polyfill on top of srcObject to support createObjectURL.  Clearly this won't scale to all other scenarios or other consumer objects still to be defined.  And, we have no plan to invest further along the direction.

Btw, the Edge WebRTC implementation discussion should probably go somewhere else :-)

**Comment by foolip** [comment]
@ShijunS, `URL.createObjectURL(mediaStream)` URLs seem to only work with media elements in Chrome too, so that's probably the interoperable intersection that sites are actually using. A spec for it could say that that's the only context where the URL works.

I'll ping this issue again in January when use counter numbers from stable are available. If there's still no sign of concrete interest in removal, then I'll argue that the responsible thing is to spec it until such interest materializes.

**Comment by foolip** [comment]
The use counters I added have reached the stable channel now:
https://www.chromestatus.com/metrics/feature/timeline/popularity/1604
https://www.chromestatus.com/metrics/feature/timeline/popularity/1605
https://www.chromestatus.com/metrics/feature/timeline/popularity/1606

For the `MediaStream` variant, usage is in the 0.007-0.01% range. Usage of the `srcObject` setter is much lower, around 0.0003%.
https://www.chromestatus.com/metrics/feature/timeline/popularity/1603

It's not easy to know what the fallback code looks like, but without careful httparchive analysis I wouldn't guess that removing `URL.createObjectURL(mediaStream)` would break real sites.

Is any browser vendor interesting in dropping support in the near term? If not, what to do?

**Comment by jan-ivar** [comment]
@foolip What do you mean "fallback code"?

**Comment by stefhak** [comment]
@foolip I guess that most sites that play ```MediaStream```s still use the (deprecated in the spec) ```URL.createObjectURL(mediaStream)``` method to play them in a media element (based on comparing 0.007-0.1% with 0.0003%).

However, at the time when we had ```URL.createObjectURL(mediaStream)``` it was a moving target as the File API (which we modeled it after) was moving back and forth regarding e.g. auto revocation (if memory serves). So I am not sure all UAs that implement ```URL.createObjectURL(mediaStream)``` do it in the same way. Additionally, the File API has now moved further and has two different methods for generating an URL for a blob.

My vision may be blurred, but to me it still makes most sense to keep URL generation out of the spec (which of course does not forbid UAs to support it) and just spec ```srcObject```.

**Comment by annevk** [comment]
> (which of course does not forbid UAs to support it)

Again, if all UAs do support it, not specifying it is anti-competitive.

You have two choices:

* Get it removed from implementations
* Define how it works

**Comment by alvestrand** [comment]
Anne, I don't agree with you either.

**Comment by stefhak** [comment]
@annevk regardless of how you define "all UAs" that would not be the case here, but perhaps that is not what you mean?

And what do you do about "Define how it works" if current implementations don't all do the same?

**Comment by foolip** [comment]
> What do you mean "fallback code"?

I mean that sites could be using either of these patterns:

```JavaScript
if ('srcObject' in video) {
  video.srcObject = stream;
} else {
  video.src = URL.createObjectURL(stream);
}
```

or

```JavaScript
try {
  video.src = URL.createObjectURL(stream);
} catch (e) {
  video.srcObject = stream;
}
```

or variations thereof. I think the first is much more likely, but it does matter to the estimation of risk which API is typically used first.

**Comment by annevk** [comment]
> Anne, I don't agree with you either.

If you don't give a reason, that's not very meaningful.

> regardless of how you define "all UAs" that would not be the case here, but perhaps that is not what you mean?

Can a new user agent get away with not supporting this or would they get compatibility issues? Edge adding this strongly suggests they would get issues.

> And what do you do about "Define how it works" if current implementations don't all do the same?

Within the constraints of web compatibility. Getting implementations to converge would then be a next step.

**Comment by foolip** [comment]
@stefhak Thanks for the extra detail on the state of things when this came about. However we ended up in this situation, currently a simple `video.src = URL.createObjectURL(stream)` call does seem to work in Chrome, Edge and Firefox, or are there problems even there? (WebKit also has it in their IDL files, but the `Conditional=MEDIA_STREAM` is not enabled in Safari.)

If there is a lack of interoperability, then that could be an opportunity to simplify to the union of interoperable behavior, but unfortunately it doesn't in itself make it likely that sites will transition to using `srcObject`. Unless some implementation is serious about removal, I would expect even deprecation (in spec and implementations) to have quite limited effect. To quote myself:

> Is any browser vendor interesting in dropping support in the near term? If not, what to do?

**Comment by stefhak** [comment]
> However we ended up in this situation, currently a simple video.src = URL.createObjectURL(stream) call does seem to work in Chrome, Edge and Firefox, or are there problems even there?

I would expect that to work fine. I would expect compatibility issues (if we have that) to be related to revocation.

**Comment by foolip** [comment]
It may well be web compatible for the returned `blob:` URL to effectively be a weak pointer to the `MediaStream` instance, and to make revocation a no-op. But that would make garbage collection web exposed and be inconsistent. @ShijunS, how does Edge implement `revokeObjectURL`, given that `createObjectURL` is defined in terms of `srcObject`?

**Comment by ShijunS** [comment]
@foolip, we will release the object URL when revokeObjectURL is called.  Internally, we will detach the stream object from srcObject, but I think that is just implementation detail.

**Comment by jan-ivar** [comment]
@foolip The first fallback you mention:
```js
if ('srcObject' in video) {
  video.srcObject = stream;
} else {
  video.src = URL.createObjectURL(stream);
}
```
is right IMHO, but createObjectURL *is* the fallback there, putting it in the existing srcObject (0.0003%) column, i.e. it's not a fallback that will can reduce the 0.007-0.1% breakage number.

The other one boils down to:
```js
try {
  // try old code
} catch (e) {
  // try new code
}
```
which I agree is unlikely, because I don't think people generally write fallbacks for old code. That would require them to anticipate it being removed, which they don't.

Sadly, there's no fallback for createObjectURL. I see no way to reduce breakage other than putting in deprecation warnings and waiting for srcObject adoption.

**Comment by jan-ivar** [comment]
One idea to reduce breakage some: We could make an exception to our "only-polyfill-the-spec" rule and have [adapter.js](https://github.com/webrtc/adapter) polyfill createObjectURL temporarily, then remove it again in a major version of adapter.js.

I don't have adoption numbers of adapter.js but I'm thinking that would give sites some control over when they break. That is, unless they're using adapter-latest.js of course, which seems risky on a production site.

**Comment by foolip** [comment]
@jan-ivar, I agree that any fallback is unlikely here, and that we should assume that almost all calls to `URL.createObjectURL(stream)` will result in user-visible breakage. Does adapter.js not already try `srcObject` before `URL.createObjectURL(stream)`? If it does, then anyone using adapter.js should already be gone from the stats.

Would you be willing to attempt the change in Firefox despite the risk?

**Comment by foolip** [comment]
@ShijunS, is the "detach the stream object from srcObject" bit observable to scripts if they look at `video.srcObject`? In any case, it sounds like `revokeObjectURL` does work in Edge, so presumably interoperability here is not too bad, or at least not a lost cause.

**Comment by alvestrand** [comment]
@foolip one of the reasons why I hate createObjectURL with a passion is that it's very hard to mock it. adapter.js doesn't intercept calls to createObjectURL (AFAIK), it only makes sure that setting srcObject works even if srcObject is not implemented.
So people using adapter.js and calling createObjectURL(MediaStream) will still show up in the stats.

@jan-ivar would we be able to write a createObjectURL shim that worked correctly for MediaSource and all other createObjectURL use cases, and still intercepted calls with MediaStream parameters?

I'm tempted.

**Comment by jan-ivar** [comment]
> Does adapter.js not already try srcObject before URL.createObjectURL(stream)?

@foolip As @alvestrand says, adapter only polyfills the spec now (all helpers are gone). People can use `srcObject` which is polyfilled in old browsers, so there's no obstacle switching, people just haven't.

@alvestrand A polyfill would need to intercept `.src`, basically do what @ShijunS has done.

However, polyfilling `URL.createObjectURL(mediaSource)` is blocked on srcObject support for it, which [we don't have yet](](https://bugzil.la/886194)).

**Comment by stefhak** [comment]
It seems to me like we have the following questions:
1. Will UA vendors remove support for ```URL.createObjectURL(stream)``` in the foreseeable future?
2. If not, does that mean that we should revive ```URL.createObjectURL(stream)```?

I guess that the answer to 1. can depend on whether polyfilling is possible.

**Comment by alvestrand** [comment]
This is actually related to #425 - it's a legacy piece that we decided to leave out of the spec.

**Comment by jan-ivar** [comment]
I hesitate to suggest it, but we can of course polyfill and remove `URL.createObjectURL(mediaStream)` while still leaving `URL.createObjectURL(mediaSource)` and `URL.createObjectURL(blob)` alone until we have `srcObject` or those. That's hardly pulling things off cleanly, but still an incremental improvement.

The other two may be harder to get rid of, as people using e.g. MediaRecorder may not necessarily be using adapter.js? Then again, I don't know what % of webrtc users uses adapter.js in the first place.

**Comment by foolip** [comment]
To replace `URL.createObjectURL` and `HTMLMediaElement.prototype.src` in a way that avoid calling the original `URL.createObjectURL(stream)` is of course possible, but it's very unlikely to make a decisive difference in the usage. Not everyone is going to be using adapter.js, and with other frameworks we typically see copies of old versions staying around for a very long time, so at best this is something that takes a few years to have the desired effect.

As for `URL.createObjectURL(blob)`, that has much higher usage still. Even with the auto-revoking `URL.createFor(blob)`, is there any plan to get rid of the former variant? Perhaps @inexorabletash can say.

**Comment by inexorabletash** [comment]
No plan that I'm aware of. At a SW F2F (with Microsoft, Mozilla and Google peeps in the room) there was a large collective sigh about `URL.createObjectURL(blob)` but concerns were raised that `URL.createFor(blob)` did not solve all of the problems so there was not strong vendor interest in pushing it. So I don't expect rapid action in that space.

**Comment by jan-ivar** [comment]
Is `URL.createFor(blob)` needed once we have `elem.srcObject = blob`, or does the former solve something not covered by the latter? Firefox implements neither atm.

**Comment by annevk** [comment]
@jan-ivar I think we shouldn't implement `createFor()` if we haven't already and indeed push for APIs that are object-oriented rather than string-based. I still think `createObjectURL()` was a rather big mistake and we should have just added the necessary APIs to support assigning objects to things. (The argument against that has always been that there are some places, such as CSS, where it's unlikely we'll ever get sufficient API exposure to allow for assigning of objects, but that also seems to be changing.)

**Comment by jan-ivar** [comment]
Here's a [polyfill](http://jsfiddle.net/jib1/rks19pvz/) for `URL.createObjectURL(stream)` we could put in adapter.js FWIW.

**Comment by stefhak** [comment]
@jan-ivar will you make a PR for adapter.js?

**Comment by stefhak** [comment]
@jan-ivar thanks, let's see if it can be merged.

**Comment by beaufortfrancois** [comment]
I'm not sure if that's related but it would be nice if we could also assign directly a `MediaSource` to `srcObject`. As I'm not familiar with the Media spec yet, I was wondering if you could tell me where I should file this proposal.

```diff
 var audio = document.createElement('audio');
 var mediaSource = new MediaSource();
 ...
- audio.src = window.URL.createObjectURL(mediaSource);
+ audio.srcObject = mediaSource;
```

For now, here's the error I get: 
`Uncaught TypeError: Failed to set the 'srcObject' property on 'HTMLMediaElement': The provided value is not of type 'MediaStream'.`

**Comment by foolip** [comment]
@beaufortfrancois, that's already supposed to work per spec, but hasn't been implemented yet. Star https://crbug.com/506273 and/or comment and it might get some traction.

**Comment by stefhak** [comment]
This was discussed at the January 25th 2017 meeting, and no one was in favor of reviving, while several argued strongly that we should _not_ revive. I will close this Issue once the "summary of decisions" has been sent on the list (given that objections to that summary is not received).

It can be noted that implementers said they will look into adding deprecation warnings ASAP, and that people said they will go through their (example/demo/etc.) code and change to use .srcObject.

**Comment by foolip** [comment]
Which implementers are going to be actively pursuing removal, and can links to bugs tracking that work be pasted here? I would suggest that if nobody has succeeded in a year's time, this issue be reopened.

**Comment by alvestrand** [comment]
The Chrome bug is here: https://crbug.com/591719

**Comment by jan-ivar** [comment]
The Firefox bug is here: https://bugzil.la/1334564

**Comment by eric-carlson** [comment]
The WebKit bug is here: https://webkit.org/b/167518

eric

**Comment by alvestrand** [comment]
Closing per WG consensus.

**Comment by foolip** [comment]
Thanks all, I'll check back here in a year.

**Comment by stefhak** [comment]
Thanks @foolip - and BTW any input on whether the adapter.js polyfill works, how counters are affected etc. in the meantime would be interesting.

**Comment by foolip** [comment]
I've commented on https://github.com/webrtc/adapter/pull/411 and it will be interesting to see if that rolling out has any impact on the usage. I would expect that a fair chunk of the usage will remain. If anyone is very motivated to remove this, then the top thing I would try is analyzing usage in httparchive, to see how it's typically used. If someone gives me a combination of static strings to search for, perhaps ".createObjectURL" and "etUserMedia", then I can provide a list of URLs that contain these strings.

**Comment by foolip** [comment]
> I'll check back here in a year

It's been over a year, and somewhat to my surprise, we're making some progress. @orphis has [deprecated createObjectURL(mediaStream)](https://chromium.googlesource.com/chromium/src/+/7e16825899d0362f71ff8d7585f54985d2d4c4ef), which will hopefully be followed by removal. If that works out, then there's no reason to revisit this.
