### ISSUE TITLE
Revert from "constraint" to "constraintName" in overconstrainederror?

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-main#405]
In #194 we changed how "overconstrained" is defined.
We made another change I didn't notice at the time - the old member value was "constraintName", while the new name was "constraint".

It turns out Chrome had implemented the "constraintName" attribute of the error.

If there is no implementation of "constraint" as the name, can we change it back?

**Comment by foolip** [comment]
It's `constraint` in Gecko's IDL, renamed by @jan-ivar in https://github.com/mozilla/gecko-dev/commit/3f14a4d7ce18d30145434f0e01edc81d0510f200.

https://gist.github.com/foolip/c0981826f70048755be9ff9f969cd138 has the URLs of the 1136 resources containing "constraintName" in httparchive:har.2016_09_01_chrome_requests_bodies if anyone wants to take a look at how it's used. (Many/most may be unrelated or harmless.)

**Comment by alvestrand** [comment]
Most of these mentions seem to be from parsley.js (a form validation library, which uses the term "constraint", but probably for something unrelated) and various minified Javascript thingummies that I suspect includes parsley.js among its dependencies.

**Comment by foolip** [comment]
That makes it very likely that changing from `constraintName` to `constraint` would be web compatible. https://www.chromestatus.com/metrics/feature/timeline/popularity/1601 is the use counter for this, I guess this can wait until we have data from stable?

**Comment by alvestrand** [comment]
Let's stick with "constraint" then.

**Comment by stefhak** [comment]
Let's close the issue as there seems to be agreement on not changing.
