### ISSUE TITLE
How can I get from a MediaStreamTrack to its MediaStream parent?

### ISSUE THREAD

**Issue by dandv** [w3c/mediacapture-main#406]
I'm building a polyfill for the [MediaStream ImageCapture API](https://www.w3.org/TR/image-capture/#constructors), and I've run into [this issue](https://github.com/dandv/imagecapture/issues/6): in order to create a `video` element and take a snapshot of it into a `canvas`, I need access to the MediaStream; however, the ImageCapture constructor only takes a MediaStreamTrack parameter.

How can I get from that track to its parent stream? The track was obtained via `getVideoTracks`.

**Comment by alvestrand** [comment]
You can't. A track can be a member of multiple MediaStreams.

You can, however, create a new MediaStream with "new MediaStream(yourTrack)". There's no particular reason to use the original MediaStream, unless you want access to other track inside that MediaStream.

**Comment by alvestrand** [comment]
Closing as "not a spec issue".

**Comment by dandv** [comment]
Thanks @alvestrand, [passing an array to the constructor](https://github.com/dandv/imagecapture/commit/7a9641a3b3c8f41e00340274c8da1f08b901536a#diff-d9c113894e33f2609b000e4848000c73R40) worked.
