### ISSUE TITLE
Need rules for devicechange event when devices are removed.

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-main#413]
#412 seemed to have rules for raising events when devices are added, but not when they're removed.

This needs to be checked, and possibly more text added.

**Comment by stefhak** [comment]
To me it seems like the important event is when a device is added. This could lead to the app taking action (like proposing to the end user the use of that device instead).
When a device is removed the app would get to know from a track ended event if the device was in use. If the device is not in use the app would anyway(?) do enumerate devices to see if it is available before requesting it via a gUM call.
But perhaps we should add event firing for removal of devices just to be consistent?

**Comment by alvestrand** [comment]
If an app (say) wants to keep a menu of devices available on screen, and wants to update the menu when devices are added or removed, it needs something to know when the device is gone; polling is not what we want to encourage.

**Comment by stefhak** [comment]
Yes I agree, we should add this. Reading the spec it seems like rather small changes are required, is someone willing to draft a PR?
