### ISSUE TITLE
Devicechange events when not focus - permitted or forbidden?

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-main#414]
It's not clear from the text in #412 whether firing a devicechange event on tabs without the focus or permission is a MAY or a MUST NOT.

This needs to be clear.

**Comment by alvestrand** [comment]
@jan-ivar can you please comment?

**Comment by aboba** [comment]
@ShijunS Can yuu comment?

**Comment by alvestrand** [comment]
@ShijunS we need your input here. Also @guidou

**Comment by alvestrand** [comment]
@ShijunS I would like to resolve this with MAY, which permits current behavior the way I understand edge does it. I don't feel like I have a compelling security story for why it needs to be MUST NOT; we can lay out the security issues (which come down largely to fingerprinting, I believe), and stress the need for adequate safeguards.

**Comment by ShijunS** [comment]
@Alvestrand, I'm fine with a MAY, which allows more time for all browser vendors to catch up with the specific security protection.

**Comment by jan-ivar** [comment]
@alvestrand, @ShijunS  I read it as a MUST.

I think the confusion is that *"When new media input and/or output devices are made available"* is a global event, yet the rules that follow assume that they are being applied in the context of a browsing context. In other words, there's an implicit "for each browsing context in the system" here, that perhaps needs to be explicit?

Specifically, I do not interpret "[current browsing context](https://www.w3.org/TR/2015/WD-html51-20150506/browsers.html#browsing-context)" to mean "the active tab" only, rather it refers to the current browsing context in the implicit for-loop of all browsing contexts (as best as [I can decipher](https://www.w3.org/TR/2015/WD-html51-20150506/browsers.html#browsing-context-names) this is what "current" tends to refer to when talking about browsing contexts).

When read this way, the rules cover all browsing contexts, and effectively limit firing to contexts that have either `"granted"` permission, an active stream, or active focus.

**Comment by jan-ivar** [comment]
Some clues to naming found in https://www.w3.org/TR/2015/WD-html51-20150506/browsers.html#browsing-context-names

**Comment by jan-ivar** [comment]
I.e. "current" browsing context refers to the context the script is in, vs. "parent" (if in an iframe) or "top-level" browsing context.

**Comment by jan-ivar** [comment]
Is anyone still confused by this? This is a MUST, not a MAY. Anything else is a mis-reading, as I tried to cover in a [previous comment here](https://github.com/w3c/mediacapture-main/issues/414#issuecomment-259831127).

**Comment by jan-ivar** [comment]
To clarify: The text specifies how *each* tab must react. Like all spec steps, they are written as local to a current context. When read this way, there should be no doubt each tab must respect the permission requirements that apply to it.

**Comment by jan-ivar** [comment]
That is: if you have input focus you always get the event, otherwise you need permission.

**Comment by jan-ivar** [comment]
I mean it seems odd to have to say "don't implement anything different from this", but if the group thinks it requires a "MUST NOT" to spell this out then that wfm.

**Comment by stefhak** [comment]
Removing "PR exists" label as there is none for the moment.

**Comment by stefhak** [comment]
Ah, missed #422, re-added the label.

**Comment by alvestrand** [comment]
I think we have merged all the required fixes now. @jan-ivar are we done?

**Comment by jan-ivar** [comment]
@alvestrand All good!

**Comment by stefhak** [comment]
Great. I guess we can close this one now.
