### ISSUE TITLE
Add device calibration and position (intrinsics and extrinsics) to MediaTrack

### ISSUE THREAD

**Issue by astojilj** [w3c/mediacapture-main#416]
In [mediacapture-depth](https://github.com/w3c/mediacapture-depth/issues/110#) extension, we need access to capture device (color or depth camera) intrinsics and extrinsics.
This is the data that enables compensating camera distortion and mapping pixels from different camera's capture.
Further explanation is in the [comment here.](https://github.com/w3c/mediacapture-depth/issues/110#issuecomment-259842834).
Naming and semantics of the data is fairly standardized among different device vendors:
[Microsoft Kinect2](https://msdn.microsoft.com/en-us/library/microsoft.kinect.kinect.cameraintrinsics.aspx), [Android Tango](https://developers.google.com/tango/apis/c/reference/struct/tango-camera-intrinsics) and [Intel RealSense cameras](https://github.com/IntelRealSense/librealsense/blob/master/include/librealsense/rs.h#L264) define:

**Intrinsics:**
double focalLengthX // used to calculate horizontal field of view 
double focalLengthY // used to calculate vertical field of view 
double principalPointX // coordinate on the image, in pixels.	
double principalPointY // coordinate on the image, in pixels.
string distortionModel; // name of distortion model, several different in use but with similar logic.	
double distortionParameters[5] // Kinect names 3 parameters.
width // already in MediaTrackSettings
height // already in MediaTrackSettings

**Extrinsics:**
Position of cameras to common reference position (vector with origin). Used for projecting from one camera space to another.
double[4] rotation, // quaternion defining rotation
double[3] translation // vector defining translation

MediaTrackSettings looks like it could fit these too, but we could also define additional MediaTrackCalibration or MediaTrackCaptureInfo.

**Comment by alvestrand** [comment]
Doesn't this issue belong on the mediacapture-depth extension issue tracker?
The extension may be useful to others, but that doesn't mean that it has to be part of the main specification.

**Comment by astojilj** [comment]
Thanks. Closing.
