### ISSUE TITLE
Do we update legacy methods to keep up with the spec?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#425]
Are we expected to update the legacy `navigator.getUserMedia` legacy method to spec when it breaks existing usage? Doing so seems to break the reasons for including it.

For example, here's a couple of breaking changes over the past year:
- https://github.com/w3c/mediacapture-main/pull/331. Use NotAllowedError for permission failure in getUserMedia algorithm (issue #317)
- [Bug 802326](https://bugzil.la/802326) - If video and audio is requested in gUM, but one of them fails, we should align with the spec (fixed in Firefox, but Chrome still has it)
- constraints.

**Comment by jan-ivar** [comment]
Uh, I just fixed a typo in the OP. `navigator.getUserMedia` is of course the legacy method.

**Comment by stefhak** [comment]
Discussed at the January 2017 interim, and we decided to not do this - I will close this Issue once the decisions of the meeting has been on the mail list.
