### ISSUE TITLE
Move "advanced" out of the Constrainable pattern

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#426]
As we contemplate reusing the constrainable pattern in other specs, like https://github.com/w3c/mediacapture-image/issues/124, this wart is a major detractor to ever reusing the pattern.

Also, do we feel the same about https://github.com/w3c/mediacapture-main/issues/369 now that some time has passed after Chrome switched to new constraints?

See also https://github.com/w3c/mediacapture-main/issues/425.

**Comment by alvestrand** [comment]
"Advanced" turned out to be necessary in the Chrome implementation to represent what was previously "optional", which is heavily used by applications.
Removing it would be a Bad Idea.

(Chrome usage of the new-format constraints is still microscopic.)

**Comment by jan-ivar** [comment]
@alvestrand There is no legacy web-compat issue between one use of the constrainable pattern to the next. Hence, no need for new uses unrelated to `getUserMedia` to inherit `advanced`. We should find less harmful ways of specifying legacy than pollute general purpose patterns we're actively promoting in other specs.

To your numbers, counting how many have yet to upgrade away from Chrome's `optional` to the spec is different from counting how many did upgrade but decided to just renamed `optional` to `advanced` in the process. The need for `advanced` hinges on the latter, and my guess is the latter number is equally microscopic. If anything, `advanced` arguably *hurts* uptake of modern spec constraints (that use fitness distance), so I'm not sure why we have it.

**Comment by alvestrand** [comment]
Discussed on Jan virtual interim.
Reuse of constrainable in mediacapture-image turned out to be just defining more constraints for use with MediaStreamTrack.
Decision: No change until a real use case comes up; then argue based on the use case.
