### ISSUE TITLE
Implementation Suggestions section needs review

### ISSUE THREAD

**Issue by burnburn** [w3c/mediacapture-main#428]
Once PR #395 is applied, all of section 10.6 (Implementation Suggestions) will clearly be marked as Non-normative.  There is very old text in this section, some of which I suspect we all treat today as normative requirements, and other text which may no longer be relevant (such as the permissions text).

This text needs a complete review again now that it has all been marked non-normative.

**Comment by stefhak** [comment]
I am assigned to this review, however after reading section 10.6 I realize it would probably be much better if someone involved in the implementation of these parts did the review. I would propose re-assigning this Issue.

**Comment by burnburn** [comment]
@jan-ivar, @ShijunS , @alvestrand can you please review or assign reviewers from your orgs?

**Comment by jan-ivar** [comment]
Lgtm. My concern with permissions was resolved, modulo https://github.com/w3c/permissions/pull/131#issuecomment-283285908.

**Comment by ShijunS** [comment]
LGTM

**Comment by alvestrand** [comment]
@guidou can you review this part of the spec? I'm simply not finding the round toit.

**Comment by guidou** [comment]
I'll review it.

**Comment by guidou** [comment]
lgtm

**Comment by stefhak** [comment]
Reviewers are OK with the current version. Close?
