### ISSUE TITLE
Move permissions algorithms back to getUserMedia spec

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-main#439]
The recommendation from @jyasskin was that the algorithms specific to an application domain (like getUserMedia) should be in the relevant spec.
This means that the details that are currently in the permissions spec (with the pending PR) should be pulled back into the getUserMedia spec, and a pointer inserted in permissions.

**Comment by alvestrand** [comment]
Note from @jan-ivar : perhaps we don't need to do anything. Inspect and decide.

**Comment by jan-ivar** [comment]
I'll do a PR here for https://github.com/w3c/permissions/issues/223#issuecomment-681327793 that at least moves one bit back.
