### ISSUE TITLE
Algorithm to mute/disable tracks is unclear

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-main#441]
The spec is not really clear about how to mute a track.
Let 's take the example of disabling a a gum video track.
Should it:
1. continue sending black frames at the expected frame rate?
2. Should it send a black frame and stop sending after that?
If 2, should the last black frame be sent immediately or follow the frame rate?

Note that this might be observable by a web application using the stats API through the framesEncoded value.
Looking quickly at https://webrtc.github.io/samples/src/content/peerconnection/bandwidth/, it seems as if Chrome is doing 1 and Firefox is doing 2.

2 has obviously some efficiency advantages.

**Comment by adam-be** [comment]
Ping @jan-ivar and @pthatcherg 
Can you guys comment on this?

**Comment by jan-ivar** [comment]
I wasn't able to mute using that example, but I can in [this one](https://blog.mozilla.org/webrtc/fiddle-week-spec-compliant-getstats/), and I see the same thing. Note though that if I modify that fiddle to include audio, I see Firefox only pauses packets for video, not audio, but that may be a bug.

The [spec](https://w3c.github.io/mediacapture-main/getusermedia.html#life-cycle-and-media-flow) does not appear to say one way or the other. I should try hooking it up to a mediaRecorder as well, to rule out any logic in peer connection.

**Comment by aboba** [comment]
@youennf If we are talking about "sending" then this relates to the RtpSender object (WebRTC), not media capture.

**Comment by youennf** [comment]
I think it belongs here.

Sending is a way that allows showing the difference in behavior.
MediaStream Recorder API might also show the difference.

**Comment by youennf** [comment]
Or the spec should ask each consumer to define its own behavior if we think that different consumers might have different behaviors.

**Comment by taylor-b** [comment]
I think I see where Bernard is coming from. WebRTC is ultimately responsible for defining how a MediaStreamTrack is encoded/transmitted. So WebRTC could encode 1 frame per second even while the MediaRecorder sees 30 frames per second.

But putting aside the question of which spec this should go in: I'd suggest saying that the implementation MAY lower the frame rate/increase the packetization interval/etc. when sending a muted track. And MAY cease transmitting frames altogether, after sending at least one muted frame? Though it seems like you could run into trouble if this single black frame encounters packet loss, or if the remote endpoint is not expecting media to completely stop flowing. @jan-ivar, is this why Firefox changed to sending 1fps? Or was there a different reason?

**Comment by jan-ivar** [comment]
@taylor-b I believe the change was a side-effect of us merging in a newer upstream version of webrtc.org; unintentional on our part.

WebRTC [already has language](http://w3c.github.io/webrtc-pc/#rtcrtpsender-interface) that senders may "MAY ... rescale or resample" media. This means stats don't conclusively reveal mediacapture mute behavior. The MAY also means the sender behavior is implementation-dependent (like a lot of things observable through stats).

As for observing the stream directly, [this works](https://jsfiddle.net/jib1/cfcoqdwz/) in Firefox and Chrome, though through different non-standard means. On OSX I got:

`mozPaintedFrames` in Firefox goes to 0 fps on mute.
`webkitDecodedFrameCount` in Chrome appears unfazed by mute (hovers around 21-30 fps).

The spec isn't clear about what `track.getSettings.frameRate` should show for a muted track. Firefox currently shows 30fps for me, regardless of mute.

It seems to me we generally haven't been standardizing media output. What's a case where doing so would help interop?

**Comment by youennf** [comment]
In case of local playback, there is no need to mandate anything currently.
In case of webrtc, there will be cases where the webrtc backend will stop receiving frames (track being muted, manual canvas capture stream).
My main concern is whether an implementation choice (in this case not sending redundant frames) might cause interop troubles if the infrastructure is not expecting that kind of scenario.

**Comment by jan-ivar** [comment]
Do you mean wire interop? If so, that may be more of an ietf thing. E.g. maybe that's why Firefox appears to send 1 packet/second even though the frame rate is supposedly zero (unless the zero `mozPaintedFrames` is an artifact of some local render-pipeline optimization).

**Comment by burnburn** [comment]
@jan-ivar would this benefit from TPAC discussion?

**Comment by jan-ivar** [comment]
@burnburn Maybe. The remaining concern (interop) seems like a WebRTC issue, not mediacapture.

FWIW in Firefox we're currently working on [turning off camera/microphone when all tracks are disabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1299515). Not sure yet what that will do to frame rate.

**Comment by alvestrand** [comment]
The frame rate on the wire needs to be a webrtc-pc issue.

**Comment by alvestrand** [comment]
Discussion moved to https://github.com/w3c/webrtc-pc/issues/1695

**Comment by burnburn** [comment]
Agreed.  There isn't really a notion of frames for local media.  Locally, frame rate really just tells you how often your image can change.  Identical black frames are the same as a single frame, effectively.
