### ISSUE TITLE
echoCancellation with advanced constraints

### ISSUE THREAD

**Issue by pantoin** [w3c/mediacapture-main#443]
Hi,

With webaudio if echoCancellation isn't set to false amplitude value changes after few seconds.

So constraints must be like this :
var constraints	= {
audio: {
optional: [{ echoCancellation: false }]
}
};

But with an advanced constraint (just set device id) i have this error :
navigator.getUserMedia error: TypeError: Failed to execute 'getUserMedia' on 'MediaDevices': Malformed constraint: Cannot use both optional/mandatory and specific or advanced constraints.

var constraints	= {
audio: {
deviceId: audioSource ? {exact: audioSource.id} : undefined,
optional: [{ echoCancellation: false }]
}
};

So i make the constraint like this :
var constraints	= {
audio: {
deviceId: audioSource ? {exact: audioSource.id} : undefined,
echoCancellation: false
}
};

But with this new constraint echoCancellation seems to be always active 👍 the output gain drops after few seconds.

Someone would have an idea about that?

Thank you

Using Chrome 57.0.2987.133

**Comment by jan-ivar** [comment]
@pantoin  This venue is for spec discussion, not for issues with particular implementations. I recommend posting a question on [stackoverflow](http://stackoverflow.com/questions/tagged/getusermedia) instead. Note that `optional` has been renamed `advanced`, though your latter example looks right. Consider [filing a bug on Chrome](https://crbug.com/).

**Comment by pantoin** [comment]
@jan-ivar I'm sorry for the inconvenience... 
I did not really know where to ask,
Thanks for your advice

**Comment by stefhak** [comment]
Closing based on the above.
