### ISSUE TITLE
Way to generate synthetic data for automated testing 

### ISSUE THREAD

**Issue by fluffy** [w3c/mediacapture-main#448]
Developers I were talking to want the API to support a way to generate synthetic traffic for testing on machines that do not have a microphone or camera.  (Firefox for example has the fake:true constraint).

**Comment by adam-be** [comment]
Would generating a MediaStream from a video element [1] be sufficient for these cases?

[1] https://w3c.github.io/mediacapture-fromelement/

**Comment by adam-be** [comment]
ping @fluffy

**Comment by stefhak** [comment]
Closing since @fluffy hasn't come back.

**Comment by fluffy** [comment]
Is there a way they can get an audio stream too? It might be good to have in the spec a pointer to ways they might do this.

**Comment by adam-be** [comment]
Looking at [1], an app should be able to capture audio tracks from both `<video>` and `<audio>` elements.

[1] https://w3c.github.io/mediacapture-fromelement/

**Comment by yellowdoge** [comment]
https://github.com/w3c/mediacapture-main/issues/448#issuecomment-299828589 is correct, both audio and video should appear as MediaStreamTracks.  In Chromium we use [`<canvas>.captureStream()`](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/imagecapture/MediaStreamTrack-getSettings.html?l=30) for testing.

**Comment by fluffy** [comment]
Yes, I think this meets the needs. Would it be possible to put a bit of text pointing this out in the spec? I think that would help some people
