### ISSUE TITLE
error for dismissing the getUserMedia prompt?

### ISSUE THREAD

**Issue by fippo** [w3c/mediacapture-main#451]
Chrome currently allows the user to dismiss (and this is covered by the permissions spec) the getUserMedia prompt which results in a PermissionDismissedError.

Is there a spec error this can be mapped to?
(I also found it hard to collect the list of possible errors :-/)

**Comment by burnburn** [comment]
This is a really good idea (assuming @aboba and @jan-ivar agree).

**Comment by fippo** [comment]
also tagging @guidou

**Comment by jan-ivar** [comment]
This error is specific to Chrome's permission model and UX, which uses "Allow", "Block" and "[x]", where the first two are permanent.

Apps probably use it to discern whether Chrome's users have permanently blocked them or not. Unfortunately, this doesn't generalize to other browsers' permission models.

Instead, the [spec](https://w3c.github.io/permissions/#dom-permissions-query) says apps should use:
```js
await navigator.permissions.query({name: "camera", deviceId}) == "blocked"
```
to learn whether they've been blocked (not implemented yet in any browser AFAIK).

@fippo I found one [hit](https://w3c.github.io/permissions/#status-of-a-permission) for "dismiss", but it appears to have no clear normative meaning.

**Comment by foolip** [comment]
@mounirlamouri, do specs normally explicitly hook up errors and promise rejects for denied permissions, or does https://w3c.github.io/permissions/ say something generically that would explain this?

**Comment by jan-ivar** [comment]
@foolip Explain what? The important bit here is that the [request permission to use](https://w3c.github.io/permissions/#request-permission-to-use) algorithm *"returns either `"granted"` or `"denied"`.* Nothing else.

**Comment by foolip** [comment]
@jan-ivar, sorry, I didn't read the specs first. Looks like https://w3c.github.io/mediacapture-main/#dom-mediadevices-getusermedia() explicitly invokes https://w3c.github.io/permissions/#request-permission-to-use and handles both the "granted" and "denied" return values, which would explain one way of rejecting the promise.

@guidou, if Chrome ever rejects the getUserMedia() promise with anything other than a "NotAllowedError" DOMException, can you file a bug to track that?

**Comment by guidou** [comment]
http://crbug.com/721412 tracks making return errors in Chrome spec compliant.

**Comment by foolip** [comment]
Thanks @guidou!

**Comment by aboba** [comment]
Please reopen if there is an issue to be fixed in the spec.
