### ISSUE TITLE
FR: Add a getUserMedia constraint to get a mirrored version of the video stream

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c/mediacapture-main#452]
When using { facingMode: 'user' }, it would be nice if I could also specify that I want a mirrored version of the video stream.

```js
const constraints = {
  video: { facingMode: 'user', mirrored: true }
};
myMirrorVideo.srcObject = await navigator.mediaDevices.getUserMedia(constraints);
```

**Comment by burnburn** [comment]
facingMode is about device selection, while mirroring is often a post-processing software action.  This is out of scope for the current spec.  You can usually mirror on rendering.

**Comment by stefhak** [comment]
Closing per @burnburn 's comment
