### ISSUE TITLE
Should we be clearer about what's legacy?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#454]
The WebRTC spec has a section called [4.3.3 Legacy Interface Extensions](http://w3c.github.io/webrtc-pc/#legacy-interface-extensions). This seems informative.

Would the mediacapture spec benefit from similar language?

Right now, the word "legacy" only appears in a note in [10.1 NavigatorUserMedia Interface Extensions](https://w3c.github.io/mediacapture-main/getusermedia.html#navigatorusermedia-interface-extensions).

Should we perhaps rename it to "10.1 Legacy Interface Extensions"?

**Comment by stefhak** [comment]
This proposal makes sense to me.

**Comment by stefhak** [comment]
@jan-ivar can you do a PR?

**Comment by jan-ivar** [comment]
@stefhak Done.
