### ISSUE TITLE
Mark 'advanced' constraints as legacy?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#455]
Can we mark `advanced` constraints as legacy? Doing so might help explain the redundancy in the spec, and point people toward the semantically simpler syntax the WG arrived at.

We're starting to see people using advanced constraints for things that are not advanced at all, [even in spec examples](https://github.com/w3c/mediacapture-image/pull/175#discussion_r116855344). I wanted to discourage it, but found no language to lean on. Can we add some?

**Comment by burnburn** [comment]
It's not a redundancy.  It gives different functionality than is provided via our ideal and required arguents.  And if people need it, it should not be discouraged.

**Comment by stefhak** [comment]
I agree to @burnburn here, it's not the same thing, and furthermore I think we should not start removing stuff we have agreed on.

**Comment by jan-ivar** [comment]
@burnburn Can you give me an example of where it is needed?
