### ISSUE TITLE
Revert https://github.com/w3c/mediacapture-main/pull/446

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#458]
This should be reverted. This language is redundant, as WebIDL bindings ensure that an empty dictionary is present. It's invariant by design.

**Comment by jan-ivar** [comment]
This in invariant is why it must be optional as a tail argument. [WebIDL](https://heycam.github.io/webidl/#idl-operations):

*"If the type of an argument is a dictionary type or a union type that has a dictionary as one of its flattened member types, and that dictionary type and its ancestors have no required members, and the argument is either the final argument or is followed only by optional arguments, then the argument must be specified as optional. Such arguments are always considered to have a default value of an empty dictionary, unless otherwise specified."*

**Comment by stefhak** [comment]
After reading through the discussion in #438 and the above I agree to your conclusion @jan-ivar.

**Comment by stefhak** [comment]
@jan-ivar can you do a PR?

**Comment by jan-ivar** [comment]
@stefhak done.
