### ISSUE TITLE
MediaStreamTrack.applyConstraints() should resolve the Promise with the applied constraints

### ISSUE THREAD

**Issue by yellowdoge** [w3c/mediacapture-main#462]
At https://w3c.github.io/mediacapture-main/#dom-constrainablepattern-applyconstraints(), instead of resolving with `void`, it'd be better to resolve with the applied constraints.

**Comment by yellowdoge** [comment]
+@beaufortfrancois and re. https://crbug.com723251

**Comment by burnburn** [comment]
@jan-ivar can you think of any reason why we couldn't do this?

**Comment by jan-ivar** [comment]
@yellowdoge What's the utility? You already them, and they're synchronously available at any time:
```js
await track.applyConstraints(constraints);
console.log(constraints == track.getConstraints()); // true
```

**Comment by yellowdoge** [comment]
@beaufortfrancois what was the rationale...?

**Comment by beaufortfrancois** [comment]
I'd like to know which constraints have been applied after each call as they might not be the ones currently set.

```js
track.applyConstraints(someConstraints).then(appliedConstraints => {
  console.log(appliedConstraints + ' may be different from ' + track.getConstraints());
)};
track.applyConstraints(otherConstraints).then(appliedConstraints => {
  console.log(appliedConstraints + ' may be different from ' + track.getConstraints());
)};
```

**Comment by jan-ivar** [comment]
> they might not be the ones currently set.

@beaufortfrancois That cannot happen.

**Comment by beaufortfrancois** [comment]
Chrome's implementation actually makes this happen. Go to https://beaufortfrancois.github.io/sandbox/image-capture/playground.html and execute JS code below in your console (webcam is expected):

```js
imageCapture.track.applyConstraints({advanced: [{brightness: 100}]}).then(c => {
  var appliedBrightness = imageCapture.track.getConstraints().advanced[0].brightness;
  console.assert(appliedBrightness == 100, 'applied brightness should be 100');
});
imageCapture.track.applyConstraints({advanced: [{brightness: 200}]}).then(c => {
  var appliedBrightness = imageCapture.track.getConstraints().advanced[0].brightness;
  console.assert(appliedBrightness == 200, 'applied brightness should be 200');
});
```
```
>>> Assertion failed: applied brightness should be 100
```

**Comment by guidou** [comment]
@beaufortfrancois : Chrome's implementation is not spec compliant and only works in a limited way for image capture. If applyConstraints is successful, getConstraints() should be the same (or equivalent) to the constraints that were requested.

**Comment by jan-ivar** [comment]
Isn't also behind a flag still?

**Comment by beaufortfrancois** [comment]
It is not behind a flag after Chrome 59.

**Comment by guidou** [comment]
Closing this.
I'm preparing a change in Chromium to make applyConstraints resolve promises with void for image capture, since the applied constraints and current settings can always be obtained using getConstraints() and getSettings(), respectively.

**Comment by alvestrand** [comment]
Closing. You can get the most recently applied constraints by getConstraints(), and the settings that resulted by getSettings() (and they don't mean the same thing).
