### ISSUE TITLE
[feature] [howTo] getUserMedia from plug n play USB devices

### ISSUE THREAD

**Issue by shamidrasool** [w3c/mediacapture-main#464]
I wanted to know if it is possible to use any different USB device other than camera or microphone as user input. A gaming joystick, like a standard xbox controller for PC is what I have in mind - to transmit its button pressing and joystick movements in real-time over the RTC data channel to a remote client using the webRTC standard, in sync with the video. If there is any other method, please advise. Someone also suggested building an Electron app along with writing Javascript APIs for the USB device drivers but it seems to be a lot of work.

I asked about this in a previous crowdcast and Daniel suggested to put up an issue here for everyone's input. Thanks.

**Comment by dontcallmedom** [comment]
Accessing data from a gamepad can be achieved with the [gamepad API](https://w3c.github.io/gamepad/). If you were to need access to raw data from a USB device, the [WebUSB API](https://wicg.github.io/webusb/) may help in some circumstances.

What is not possible at the moment (but would be more of a concern for the [WebRTC spec](https://github.com/w3c/webrtc-pc/) than this one) is to createa a sync'd  data stream going on the data channel with a media track. That topic was [discussed a few years ago on the WebRTC mailing list)[https://lists.w3.org/Archives/Public/public-webrtc/2013Feb/0030.html].

**Comment by aboba** [comment]
Closing as there appears to be no issue to fix.
