### ISSUE TITLE
Questions about setting belonging to source in Section 3.

### ISSUE THREAD

**Issue by guidou** [w3c/mediacapture-main#466]
I would like clarification for the following case:

Let's say the system has a single camera that can provide frames at 60Hz.
There are two getUserMedia calls. One requests an exact frame rate of 30Hz, and the other one requests an exact frame rate of 60Hz.

Chrome currently allows both calls to succeed. For the first track, Chrome drops every other frame, so the track has an effective frame rate of 30 Hz. For the second track no frames are dropped, so it has the requested 60Hz.

Section 3 says _"User Agent processing, such as downsampling, may be used to ensure that all tracks have appropriate media"_, so processing to get a 30Hz track seems compliant.

The question is what should getSettings return?
Chrome currently returns 30Hz for the first track and 60 Hz for the second track, which I think is what a user would expect.

However, the spec says that settings don't belong to the tracks, but to the source. More specifically, it says _"Sources have constrainable properties which have capabilities and settings. The constrainable properties are "owned" by the source and are common to any (multiple) tracks that happen to be using the same source (e.g., if two different track objects bound to the same source ask for the same capability or setting information, they will get back the same answer)."_

This part suggests that returning 30Hz and 60Hz could be a violation of the spec, unless one considers the source to be not the camera, but the processed 30Hz stream.

Interestingly, the definition of getSettings() says _"The getSettings() method returns the current settings of all the constrainable properties of the object, whether they are platform defaults or have been set by the applyConstraints algorithm."_, where _object_ is the track, so this part of the spec suggests that settings might belong to tracks after all.

So, should Chrome be "fixed" to return 60Hz for the track with 30Hz?
Note that this is relevant to other properties for which Chrome currently provides processing.

**Comment by stefhak** [comment]
Assigning to Dan.

**Comment by jan-ivar** [comment]
@guidou Good find, and in the terminology section! The contradicting statements again:

> "User Agent processing, such as downsampling, may be used to ensure that all tracks have appropriate media",

> "(e.g., if two different track objects bound to the same source ask for the same capability or setting information, they will get back the same answer)."

The second statement seems to assume device settings are hardware settings, and/or that hardware devices cannot do two things at once. That's artificially limiting for audio at least:
 * aec, noise-reduction, auto-gaincontrol are often not implemented at the device level.
 * low-latency, sample-rate, sample-size, channel-count are, but still trivial to decimate in software.

AFAIK there's no quality loss either. Different values per track makes sense to me here. @burnburn?

**Comment by jan-ivar** [comment]
When it comes to **video resolution and frame-rate**, I suspect some may have reservations about getting non-native modes, given the constraints-language's focus on device discovery. cc @fluffy 

That said, as Firefox's implementation shows in https://github.com/w3c/mediacapture-main/issues/465#issuecomment-320261591 there are side-effects from having no virtualization at all: Changes in one tab, end up observably affecting another, live. Not great. As a browser, we're keen to abstract away effects of other domains whenever possible, for privacy reasons as well as more deterministic behavior.

So we're looking at maybe doing some rescaling, at least to address our concurrent access situation.

But we're also concerned by an apparent rise in mininum supported resolution in at least some newer cameras (new MBP internal cams seem to offer only 640x480 and 1280x720). So we're contemplating filling in low-res gaps with "divide-by-2" virtual modes. Group thoughts?

@guidou My tests with Canary and chrome://flags/#enable-experimental-web-platform-features today seem to produce native modes when available (in a single tab at least), which is terrific!

It appears to fall back to rescaling, only failing with `OverConstraintedError` if I go above camera max. Does that match your expectation?

**Comment by jan-ivar** [comment]
Rescaling to solve concurrent access may be desirable even if we end up doing https://github.com/w3c/mediacapture-main/issues/472 (loss of quality being a preferable side-effect to unexpected rescaling IMHO).

**Comment by guidou** [comment]
@jan-ivar that is indeed the way Chrome is expected to work. That behavior is shipping already in stable (since Chrome 59). Chrome uses non-native modes only if you use an ideal non-native value, or if the requested range does not include a native mode but can be satisfied with a non-native mode. When a non--native mode is used, the camera is opened in the native mode that is closest to (and greater than) the non-native mode to be used.

**Comment by jan-ivar** [comment]
@guidou Thanks for confirming, and glad to see this!

My one comment would be that, as I recall, one of our goals behind imbuing `ideal` with gravity in the [fitness distance](https://w3c.github.io/mediacapture-main/getusermedia.html#dfn-fitness-distance) algorithm was to locate a preferred native mode among several within a range. E.g.
```js
await track.applyConstraints({height: {min: 180, max: 1024, ideal: 180}}); // lowest native
await track.applyConstraints({height: {min: 160, max: 750, ideal: 750}}); // highest native
```
This does not appear to work in Chrome. Also, `advanced` doesn't seem particularly useful. e.g.:
```js
await track.applyConstraints({advanced: [{height: 180}, {height: 200}]}); // always 180
```
I've opened https://github.com/w3c/mediacapture-main/issues/472, we can continue there. Back to "different values per track" here.

**Comment by guidou** [comment]
@jan-ivar If that was the intention was to select only native modes, it did not make it into the spec. The spec does not make any reference to native vs. non-native video modes. It only talks about settings dictionaries, and Chrome runs the SelectSettings algorithm with both native and non-native dictionaries as part of the set of valid dictionaries. If, after discarding all dictionaries that don´t satisfy the basic/advanced constraint sets, a candidate that equals ideal is present, it is selected because it will have the best fitness, as indicated by the spec. This is the correct result in Chrome with the spec as written.

With regards to the advanced example, the spec says that naked values in advanced sets mean exact, so after analyzing the first constraint set (exact 180), no candidates that satisfy exact 200 remain and the second set is ignored. Thus the result is always going to be dictionaries with height = 180. Advanced sets that contradict previous advanced sets are often not useful because in most cases they will be ignored. I see nothing incorrect in that.

**Comment by jan-ivar** [comment]
> If that was the intention was to select only native modes, it did not make it into the spec. 

@guidou I notice you didn't dispute the shortcomings I mentioned. Both Firefox and Edge let users discover best-match device modes using the [above](https://github.com/w3c/mediacapture-main/issues/466#issuecomment-320485062) examples with quite a bit of precision, with `advanced` lending even more precision.

Those browsers do it without exposing an exhaustive list of device capabilities to the JS. This is quite an accomplishment that would not have been possible without the full intent of the spec behind it.

It's why constraints is a bit of a mini-language.

This is not possible in Chrome. That seems like a shortcoming.

> The spec does not make any reference to native vs. non-native video modes.

Right, no mention of downscaling, except to "ensure that all tracks have appropriate media", this issue.

**Comment by guidou** [comment]
> @guidou I notice you didn't dispute the shortcomings I mentioned. Both Firefox and Edge let users discover best-match device modes using the above examples with quite a bit of precision, with advanced lending even more precision.
> 
> Those browsers do it without exposing an exhaustive list of device capabilities to the JS. This is quite an accomplishment that would not have been possible without the full intent of the spec behind it.
> 
> It's why constraints is a bit of a mini-language.
> 
> This is not possible in Chrome. That seems like a shortcoming.

This sounds to me more like a shortcoming of the spec than of Chrome's implementation of the spec.
Nothing in the spec suggests that the purpose of min/max/ideal was to discover native modes, even if it was the original motivation at some point.
If this is indeed important (which is not entirely clear to me, since I'm not aware of any user filing a bug for this in Chrome) then let's continue the discussion in #472 and just fix the spec.

**Comment by fluffy** [comment]
I think this native mode things is pretty confusing and would try to avoid it will change on many devices. Most CMOS sensors support only a *single* native resolutions but multiple frame rate.  Some have multiple native resolutions. This often feeds to a chip in the camera which may support many resolutions across USB bus even though none of them are the native of the sensor. This then goes to OS driver which may change the resolutions it exposes to browser. I think it gets very confusing what "native" would even mean or how a browser would mange it across multiple OS and different cameras. What a USB camera might report over typical USB profiles is very different than what would be known about a MIPI camera on a raspberry pi. A Firewire camera would be different again. I think it is reasonable to give the browsers latitude to do something reasonable as long as it gives an error if outside allowed constrain range and never creates fake data.

**Comment by jan-ivar** [comment]
> as long as it gives an error if outside allowed constrain range and never creates fake data.

@fluffy You're ok with `OverconstrainedError` solely if the camera's max abilities are exceeded?

**Comment by fluffy** [comment]
I think over constrained can happen other ways too. For example, a camera that could any frame rate up to 60fps but one stream wants exactly 24 fps and one wants exactly 30 fps. Neither stream exceeds the max but there is no way to simultaneously meet both. This type of scenario is less likely to happen with constraints on resolution as you can do that easily without creating fake data. And downscaling by frame rate by integer amounts is easy too but down scaling frame rates by non integer amounts creates fake data that really messes up algorithms that are try to track motion such as the stuff used in SLAM code in most AR/VR systems.

**Comment by jan-ivar** [comment]
@fippo I think that expectation faces a couple of hurdles:
 1. From a browser standpoint it's really undesirable to have constraints be able to detect camera use in other tabs, for privacy and security reasons. We're probably [more inclined](https://bugzilla.mozilla.org/show_bug.cgi?id=1388667#c2) to downscale in these nonoptimal edge-cases, to abstract away knowledge of other tabs.

 2. From what I've seen, frame rates fluctuate on most cameras depending on lighting etc. so it's normal for actual frame rate to dip below constrained target-`frameRate`, even with `exact`. AFAIK none of the browsers implement the [overconstrained](https://w3c.github.io/mediacapture-main/getusermedia.html#event-mediastreamtrack-overconstrained) event. How can we implement it at this point when users are already using `exact` to force rescaling? I'm pretty sure those users would complain if we suddenly began muting their tracks. The rare app that wants this is probably better off [measuring actual frame rate](https://jsfiddle.net/jib1/suLvcr3a/
), and making its decision off of that instead.

 4. Constrainable properties may be configured settings, not actual values. https://github.com/w3c/mediacapture-main/issues/470

 3. We can decimate from 60 to 24 fps without creating "fake" data, it just won't be smooth.

**Comment by jan-ivar** [comment]
Uh, I meant to respond to @fluffy above. I've edited the comment.

**Comment by fluffy** [comment]
Our stats indicate very few cameras adjust frame rate for lighting but ignoring how common it is or not .... If the camera frame rate moves below X, *and* the app has set a min rate at X, yes, there needs to be an error. If the app is OK with data below that rate it would not have set a min rate.  Very few apps should be setting min rates. 24 fps means very close to 1/24 s between frame (that is smooth) - many things rely on this including motion estimation in the video compression.  I understand the privacy issues around detecting what is happening in another tab but on a notebook computer when I look at the stream coming out of a 2nd tab trying to do compression of HD video, it's fairly clear to the first tab that some other process on the computer is using a substantial amount of the CPU - I can understand that browser would take actions to try and mask this.

**Comment by jan-ivar** [comment]
> Very few apps should be setting min rates. 24 fps means very close to 1/24 s between frame

If they're very few, I'm inclined to advise them to measure the frame rate for best result. I think there's also value in constraining UAs from picking a lower *target* frame rate *on purpose*. I fear more apps use that definition. AFAIK no browser returns actual frameRate in `getSettings()` today.

Nit: `min` is a limiter without gravity, so 1/24 is no guarantee. Maybe `{min: 24, ideal: 24}`. My point is setting constraints properly is hard. `{exact: 24}` would be a recipe for failure with that definition.

> If the app is OK with data below that rate it would not have set a min rate

I think that's an assumption. It's hard enough to pick a *target* frame rate in gUM. I could easily see the majority of apps meaning, don't give me a *target* frame rate lower than 24.

People may also be intuitively using `exact` as an enforcer, to force rescaling (as in "I don't care about native modes. Just rescale me this."). That's a model we're [considering](https://bugzilla.mozilla.org/show_bug.cgi?id=1388667#c10) as a compromise, since the alternative leaves few options for navigating the driver mode space.

Again, not sure if my new MBP is broken, but I consistently see rates ~15-30 fps varying second by second, with both [gum](https://jsfiddle.net/jib1/suLvcr3a/) and [encoded](https://jsfiddle.net/jib1/6j072zcx/) on both FF and Chrome. These fiddles would both fail instantly with that definition.

**Comment by fluffy** [comment]
We have said since the beginning that using exact is pretty much never what you want as it does not leave the browser the option of doing the best it can. The problem with measurement is AFAIC, there is not accurate way to measure every frame.

**Comment by jan-ivar** [comment]
Firefox and Chrome at least implement non-spec ways to measure frame rate. From [fiddle](https://jsfiddle.net/jib1/suLvcr3a/):
```js
let frames = v => v.mozPaintedFrames || v.webkitDecodedFrameCount;
```

**Comment by alvestrand** [comment]
Two questions:
- does getSettings() return a target value or a current value? No consensus at TPAC.
- is the getSettings() returning settings for the source or the track?
Consensus at TPAC seems to be that they return settings for the track - ie tracks from the same source can return different setting values (which is in conflict with current spec text).

**Comment by alvestrand** [comment]
TPAC consensus may have been for "target value".
