### ISSUE TITLE
Why is it important that aspect ratio be rounded to the tenth decimal place?

### ISSUE THREAD

**Issue by guidou** [w3c/mediacapture-main#467]
The spec says so [here](https://w3c.github.io/mediacapture-main/#def-constraint-aspect).

Does any implementation actually do this rounding?

**Comment by guidou** [comment]
More specifically, if a track has a resolution of 100x700, would it be a violation of the spec to have getSettings() return 0.142857142857143 instead of 0.1428571429?

**Comment by fluffy** [comment]
I find this all a bit academic but people were concerned about setting aspect ratios to numbers that are not representable in normal floating point. For example, 0.1 is not representable exactly. So if you wanted to have a 1:10 ratio,  and you wanted to exactly compare the value vs saying >0.999 and less than <0.10001 , you would need to know how 0.1 got rounded.

**Comment by aboba** [comment]
Please reopen if there is an issue to be fixed.
