### ISSUE TITLE
Does getSettings() reflect configured or actual setting?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#470]
In https://github.com/w3c/mediacapture-image/pull/182#issuecomment-308837309 there's a JS example attempting to use `getSettings()` to wait for a camera's motor to finish panning to a desired position. Does the mediacapture spec support this? It seems unclear:

From what I can tell given [this](https://w3c.github.io/mediacapture-main/getusermedia.html#dom-constrainablepattern-getconstraints()): *"To check which ConstraintSets are currently in effect, the application should use getSettings."* - the mediacapture spec guarantees:
```js
await track.applyConstraints({pan: {exact: pan}});
console.log(pan == track.getSettings().pan); // true
```
But this leaves no room for a motor to change: Even if `applyConstraints` were to wait for a motor to finish, there'd be a period of time where returned `getSettings()` might violate previous (still applied) constraints:
```js
await track.applyConstraints({pan: {exact: oldPan});
let p = track.applyConstraints({pan: {exact: newPan});
setInterval(() => is(track.getConstraints().pan == track.getSettings().pan));
await p;
```
AFAICT, the current spec leaves browsers no option other than for `getSettings()` to lie about the actual motor position, and instead return only the last configured setting. Was that the intent?

**Comment by jan-ivar** [comment]
This is perhaps a dup of https://github.com/w3c/mediacapture-image/issues/126.

**Comment by fluffy** [comment]
I assumed that the promise would not return until the constraints had been applied. Does that work ?

**Comment by jan-ivar** [comment]
@fluffy Regardless of when the promise returns, what should getSettings() return when there's a discrepancy between configured setting and actual physical setting? E.g.

Time | What happened | Applied constraints | Physical motor position | getSettings() returns
-----|--------------|-----------------|-------------------------|---------------------
0 | Starting condition |{pan: {exact: 30}} |  30 | 30
1 | applyConstraints({pan: {exact: 60}) called | {pan: {exact: 30}} |  30 | 30
2 | motor moves | {pan: {exact: 30}}   |  40 (violation) | ?
3 | motor moves | {pan: {exact: 30}}   |  50 (violation) | ?
4 | applyConstraints({pan: {exact: 60}) resolves |{pan: {exact: 60}}   | 60 | 60
