### ISSUE TITLE
Should setting MediaStreamTrack.enabled = false on a track make it muted?

### ISSUE THREAD

**Issue by guidou** [w3c/mediacapture-main#477]
The spec says "A disabled track is logically equivalent to a muted track, from a consumer point of view."

Does this mean that setting enabled = false on an unmuted live track should also result in the track becoming muted (with the corresponding firing of the muted event)? 
Is this behavior mandatory, allowed or forbidden? I did not find any explicit language in the spec about this. My interpretation of the spec as written is that this behavior is allowed, but not mandatory.

**Comment by guidou** [comment]
cc @foolip

**Comment by stefhak** [comment]
Assigning to @adam-be as he wrote these parts of the spec.

**Comment by adam-be** [comment]
I would say it's not intended. 

The enabling and disabling of a track directly updates the attribute and therefore there's no event coupled with it. The muted event is intended to notify the script about what happens with the underlying source of the track which the script normally has no control over (we have no corresponding object representing the source).

**Comment by adam-be** [comment]
@guidou, can we close this issue?

**Comment by guidou** [comment]
Yes, let's close it. I got the answers I needed.
