### ISSUE TITLE
Consider discussing content hints for MediaStreamTrack in next interrim

### ISSUE THREAD

**Issue by pbos** [w3c/mediacapture-main#478]
In WebRTC in Chromium, content is treated differently whether it's screencast or usb webcam devices. It's assumed that screencast can't be downscaled, or text will lose its intelligibility, while usb video class devices webcam content that can be downscaled to preserve frame rate under low bitrate conditions.

This assumption doesn't hold when the screencast content is of a video game, movie or other high-motion content. It doesn't either hold when the usb video device is a capture card, and the capture card is streaming a text website (downscaling this content like normal video will lose intelligibility).

To override this, I created an experimental feature (http://crbug.com/653531, https://wicg.github.io/mst-content-hint/) that permits overriding this assumption (`MediaStreamTrack.contentHint = 'motion';` is treated as "webcam video"). There's also a demo that shows the difference between detail and motion video at https://webrtc.github.io/samples/src/content/capture/video-contenthint/ (requires enabling experimental web features in Chrome). In our suggestion, this was put on the MediaStreamTrack (as opposed to RTCRTPSender) since that has the widest potential use (a MediaStreamRecorder implementation could read it, without having to rewrite the the MediaStreamRecorder standard). It also happened to be the easiest place for us to implement it in Chromium at the time.

There are also values for audio MSTs in the draft doc (music / voice) that could be used for guiding noise reduction algorithms (current noise reduction algorithms will not work well on drums etc. which looks like noise, so it might be best to turn off for music content).

I believe the next step is to hand this suggestion over to this working group (including the question of whether the property fits on MediaStreamTrack as opposed to RTCRtpSender etc.). This doesn't really fit well as a stand-alone document. Can this be discussed in the next interrim meeting? I'd like to have a plausible roadmap out of this feature being experimental, and I believe it's crucial for properly taking care of content at low bitrates (when `screencast == detail` or `usb == motion` fails as a heuristic).

**Comment by stefhak** [comment]
Hi @pbos I unfortunately think that we cannot get to this at next meeting, but plan to talk about it at a future one. In order to get prepared for the discussion I sent a mail to the list to ask about plans for implementation (https://lists.w3.org/Archives/Public/public-media-capture/2017Aug/0021.html).

**Comment by pbos** [comment]
That's alright, I mostly wanted it to be brought up in the foreseeable future to be able to hand it over for a long-term solution. FYI there's also been some discussion under https://github.com/WICG/mst-content-hint/issues/18, and https://github.com/WICG/mst-content-hint/issues/18#issuecomment-283751644 hints that there's general interest for a content hint from Mozilla (but that it's unclear in which form it should take).

**Comment by stefhak** [comment]
@pbos we put this up for discussion at the Oct 12 (on-line) meeting. Can you add a slide or two introducing this (why is perhaps more important than how) at https://docs.google.com/presentation/d/1Mfilvq56DbSqUSgMBgWvK7Zp4pLvN6KIexPtAGZhn1I/edit#slide=id.p

**Comment by pbos** [comment]
Sure, I've requested access to the doc. When do you need it? Is any time before Oct 12 fine or would a week in advance help?

**Comment by stefhak** [comment]
@aboba can you give access to the slide set?
Having the slides a few days before the meeting would be helpful. And just to be clear: we think we will have time to cover this, but getting the "Resolve before CR" Issues on webrtc-pc covered has priority.

**Comment by pbos** [comment]
Yep, got it.

That's fine, so long as it gets discussed / handed over within the foreseeable future. This meeting or the next isn't that crucial. I'll make sure something's up before that.

**Comment by stefhak** [comment]
@pbos the meeting is approaching, please don't forget doing the slides.

**Comment by pbos** [comment]
Sorry, I got swamped. I'll do them today. Do you want me present at the meeting?

**Comment by stefhak** [comment]
Great! Yes, please present them at the meeting.

**Comment by alvestrand** [comment]
@pbos and @pthatcherg - will either of you be available to talk about this at TPAC next week?

**Comment by alvestrand** [comment]
The WG decided to adopt the content-hint document as a starting point for further work.
Further issues should be raised against the now-adopted document.
