### ISSUE TITLE
Can IDL typedef for MediaStreamError be (DOMException or OverconstrainedError)?

### ISSUE THREAD

**Issue by saschanaz** [w3c/mediacapture-main#484]
https://w3c.github.io/mediacapture-main/archives/20170828/getusermedia.html#navigatorusermediaerrorcallback

```webidl
typedef object MediaStreamError;
// A MediaStreamError object is either a DOMException object or an OverconstrainedError object. 
```

Can this be a union:

```WebIDL
typedef (DOMException or OverconstrainedError) MediaStreamError;
```

**Comment by jan-ivar** [comment]
Once we do https://github.com/w3c/mediacapture-main/issues/568 I think so.

**Comment by jan-ivar** [comment]
It turns out WebIDL does not allow this, since the types are not [distinguishable](https://heycam.github.io/webidl/#dfn-distinguishable). From mozilla's webidl compiler:
```
 0:05.05 WebIDL.WebIDLError: error: Flat member types of a union should be distinguishable, DOMException (Wrapper) is not distinguishable from OverconstrainedError (Wrapper), /Users/Jan/moz/mozilla-central/dom/webidl/Navigator.webidl line 248:8
 0:05.05 typedef (DOMException or OverconstrainedError) MediaStream2Error;
```
`MediaStreamError` is used solely in the legacy callback APIs, so having it be an `object` doesn't seem like a big issue. Closing.

**Comment by saschanaz** [comment]
I think those should be distinguishable 🤔. Hi @annevk and @edgarchen, could you confirm whether this should be possible or not? The distinguishability table does not say anything about non-IDL objects like OverconstrainedError.

**Comment by saschanaz** [comment]
BTW, #568 would essentially make `MediaStreamError` an equivalent of `DOMException` so maybe not worth fixing it.

**Comment by jan-ivar** [comment]
Right, sorry I should have mentioned I meant with https://github.com/w3c/mediacapture-main/issues/568 applied.
