### ISSUE TITLE
Undefined how video dimension constraints are met

### ISSUE THREAD

**Issue by stefhak** [w3c/mediacapture-main#495]
As far as I read the spec, it is not defined _how_ constraints on (video track) width, height and aspectRatio are met. Will the video be scaled down, cropped, a combination? Will it be letterboxed/pillarboxed?

A concrete use case that has been discussed is one where square 100x100 thumbnails are to be shown (at a remote end point). Say the camera  produces a 16:9 high resolution video feed, applying constraints ```width:100, height:100``` should ideally scale down to height 100 and then crop the width to 100 in this use case. Applying (only) ```aspectRatio:1``` should crop the width to 1080 (at least for this use case).

We should discuss this at TPAC.

**Comment by jan-ivar** [comment]
> width:100, height:100 should ideally scale down to height 100 and then crop the width to 100

More than "how", the spec doesn't mandate downscaling, so this won't work across browsers.

The sole mention of downscaling in the entire spec appears in this paragraph about concurrent use:

   *"Multiple tracks can be attached to the same source. User Agent processing, such as downsampling, **MAY** be used to ensure that all tracks have appropriate media."*

We're [implementing](https://bugzilla.mozilla.org/show_bug.cgi?id=1388219) that paragraph in Firefox, to abstract away knowledge of other tabs, which is good for privacy. However, this is separate from boosting the fitness distance pool.

We're open to figuring out how to interpret rescale intent from constraints, as you can see in https://github.com/w3c/mediacapture-main/issues/472.

> thumbnails are to be shown (at a remote end point)

The only spec way to do that today is to [downscale in the encoder](https://blog.mozilla.org/webrtc/fiddle-week-downscale-video-peerconnection/), using [scaleResolutionDownBy](http://w3c.github.io/webrtc-pc/#dom-rtcrtpencodingparameters-scaleresolutiondownby).

An implementation would have to be careful to avoid rescaling twice. How sure are we we want the `track` to be the control surface for the encoder?

**Comment by stefhak** [comment]
@jan-ivar thanks for your input, I agree this is related to #472 
> An implementation would have to be careful to avoid rescaling twice. How sure are we we want the track to be the control surface for the encoder?

I think the important thing here is that we have ```contraints``` that enable constraining ```width```, ```height``` and ```aspectRatio``` for video tracks, and therefore we need to specify how an implementation must behave.

**Comment by jan-ivar** [comment]
@stefhak I think you're thinking of "constraining" = rescaling, which is not the spec definition.

For instance, If `getUserMedia` worked that way, `max` and `exact` would be redundant.

The spec defines `applyConstraints()` as a filtering function applied to a *UA-specific* pool of available [settings dictionaries](https://w3c.github.io/mediacapture-main/getusermedia.html#dom-mediastreamtrack-applyconstraints()) (instances of [MediaTrackSettings](https://w3c.github.io/mediacapture-main/getusermedia.html#dom-mediatracksettings)) for a device. A discovery API essentially.

Firefox and Edge implement discrete settings dictionaries. Chrome implements a continuous space.

**Comment by stefhak** [comment]
@jan-ivar I may very well have gotten things wrong, that happens all the time :)

Could you explain what you think should happen if 
* ```getUserMedia``` is called with ```video``` as only argument
* doing ```getSettings()```  on the resulting ```video``` track returns a ```width``` of 1920 and a ```height``` of 1080
* the app then applies mandatory constraints saying that ```width``` and ```height``` should both be 100?
* or, if the app instead of ```width``` and ```height``` puts ```aspectRatio``` constraint (mandatory) to 1?

**Comment by jan-ivar** [comment]
> The sole mention of downscaling in the entire spec appears in this paragraph about concurrent use

Correction: I found one more, in this [note](https://w3c.github.io/mediacapture-main/getusermedia.html#h-note13). One has to search for "downsampling" *and* "resampling".

**Comment by alvestrand** [comment]
#502 seems to be solving this question.
