### ISSUE TITLE
audioElement should ignore video tracks in a stream wrt ended.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#520]
Currently, our prose on HTMLMediaElement impact relies on the media stream [active](https://w3c.github.io/mediacapture-main/getusermedia.html#stream-active) attribute, which only really makes sense for video elements, which end when the total number of tracks go to zero.

For audio elements, this seems wrong. Audio elements cannot play video, and should arguably end when the total number of *audio* tracks goes to zero.

**Comment by jan-ivar** [comment]
@burnburn can you take a look? Looks like I don't have access to assign or set flags like I do in webrtc.

**Comment by jan-ivar** [comment]
FWIW here's current behavior: https://jsfiddle.net/jib1/vbf2Lqhc/

Firefox: false, false, false, true, ended, true, true (only ended once both tracks go away).
Chrome: false, false, false, false, false, false

**Comment by eric-carlson** [comment]
FWIW, in Safari the current behavior is: false, false, false, false, ended, true, true

**Comment by alvestrand** [comment]
Can this be closed based on #521 being merged?
