### ISSUE TITLE
I want enumerateDevices() filter argument. :-)

### ISSUE THREAD

**Issue by gtk2k** [w3c/mediacapture-main#522]
Like this.
```
const videoInputDevices = await navigator.mediaDevices.enumerateDevices({kind: 'videoinput'});
```

**Comment by alvestrand** [comment]
what's wrong with 
```
navigator.mediaDevices.enumerateDevices()
.then(list) { return list.filter(dev => dev.kind='videoinput') };
```
? (apologies for errors in Javascript syntax)

**Comment by gtk2k** [comment]
@alvestrand 
Thank you for the reply.
Yes, I know .filter ().
When writing enumerateDevices(), in most cases write .filter().
So it was convenient if enumerateDevices() had filtering function.

**Comment by fippo** [comment]
i suspect the effort of specifying this is (for example: does enumerateDevices('videoinput') try to enumerate video devices and the kind is only run as a filter afterwards?) is much higher than the impact.

Its pretty easy to shim so there wouldn't be that many backward compability issues at least.

**Comment by alvestrand** [comment]
closing as "not worth the specification effort, usefulness can be achieved by other means".
