### ISSUE TITLE
Volume attributes for audio MediaStreamTracks?

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-main#523]
Discussion in various places, including https://github.com/w3c/webrtc-stats/issues/353, https://github.com/w3c/webrtc-stats/issues/271 and others, lead to the conclusion that we have a legitimate need to get the audio level of an audio track, with or without the track being connected to an RTCPeerConnection (so getStats is inappropriate).

Use cases for both the input audio level (choosing the track, detecting clipping) and output audio level (displaying level after AGC and echo cancellation) for the track have been made.

Audio level is not a simple concept (need to specify sampling interval, decay rate if averaged and so on); we might want to consider using TotalAudioEnergy as the webrtc-stats does, or we might want to find an EBU (or other) recommendation that gives us a precedent to follow.

Tagging @henbos @vr000m @huibk @fsolenberg

**Comment by henbos** [comment]
The problem with instantaneous values is audio level could change in-between polling. Audio level is, at least conceptually, a continuum over time and you can't get around discrete polling, but the total audio energy allows you to, by polling it twice, calculate the average audio level by looking at the difference and diving by time, similar to how polling a total counter of bytes twice and dividing the difference with time gets you bps. I don't fully understand the math when it comes to audio energy but it might be a good idea.

On the other hand if audio level is something we always have access to maybe polling frequently is not an issue for performance (unlike RTCPeerConnection.getStats() which is expensive) and it's better to have something easy-to-use and easy-to-grasp.

In any case the metrics of interest might be...
1. The volume of the data produced by the device (browser level).
2. The volume of the data coming in to the track.
3. The volume of the data after track-specific processing, e.g. constraints, removing noise, etc.

If no processing happens between 1 and 2 and they are the same, or if 1 is not of interest, we are just talking about "inputAudioLevel" (2) and "outputAudioLevel" (3).

**Comment by jan-ivar** [comment]
Is this not covered by web audio? https://webrtc.github.io/samples/src/content/getusermedia/volume/

**Comment by alvestrand** [comment]
The volume attribute has been deleted, so this is OBE.

**Comment by alvestrand** [comment]
I'm misunderstanding my own issue; it was not about the "volume control" attribute. But I think this can be done adequately by webaudio. Closing.
