### ISSUE TITLE
applyConstraints algorithm threading issues (editorial)

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#530]
The [applyConstraints algorithm](https://w3c.github.io/mediacapture-main/getusermedia.html#dfn-applyconstraints-algorithm) is called both from the method of the same name, and *getUserMedia*.

Problem is, it's called from main-thread in the first case, and off-main-thread in the second, and the error handling in the second case is busted:

The algorithm returns a promise which goes unused, which means errors are dropped.

Promises have built-in main-thread semantics we should avoid off-main-thread.

**Comment by alvestrand** [comment]
Assumed fixed by #53
