### ISSUE TITLE
Clarification about ended event and attribute on HTML media elements.

### ISSUE THREAD

**Issue by guidou** [w3c/mediacapture-main#536]
The spec says:

> If the element is an HTMLVideoElement, then when the MediaStream state moves from the active to the inactive state, the User Agent MUST raise an ended event on the HTMLVideoElement and set its ended attribute to true. 

My first observation is that setting the ended attribute of a media element seems to be in conflict with the definition of that attribute in the HTML spec. The ended attribute in HTML is not defined as something that can be arbitrarily set, but in terms of duration and current playback position as follows:
> A media element is said to have ended playback when:
> 
> The element's readyState attribute is HAVE_METADATA or greater, and
> Either:
> 
> * The current playback position is the end of the media resource, and
> * The direction of playback is forwards, and
> * The media element does not have a loop attribute specified.
> Or:
> 
> * The current playback position is the earliest possible position, and
> * The direction of playback is backwards.
> * The ended attribute must return true if, the last time the event loop reached step 1, the media element had ended playback and the direction of playback was forwards, and false otherwise.

About infinite streams, the HTML spec says:
> If an "infinite" stream ends for some reason, then the duration would change from positive Infinity to the time of the last frame or sample in the stream, and the durationchange event would be fired. Similarly, if the user agent initially estimated the media resource’s duration instead of determining it precisely, and later revises the estimate based on new information, then the duration would change and the durationchange event would be fired.

Should the madiacapture-main  spec be more explicit either about overriding the ended attribute or redefining what should happen in terms of current playback position and duration?

I would also like clarification about the following:

> Note that once ended equals true the HTMLVideoElement will not play media even if new MediaStreamTracks are added to the MediaStream (causing it to return to the active state) unless autoplay is true or the web application restarts the element, e.g., by calling play().

Is the part about not playing media when the stream becomes active a description of what will happen, given how HTML elements work, or is this mandating that the element must be paused when it becomes ended? If the latter, I think this must be mentioned more explicitly.

I noticed that Firefox and Edge pause the element. In addition, Firefox fires the pause event (which I think is required by the HTML spec if the element becomes paused). If play() is invoked on the element before the stream becomes active, the element plays the stream automatically when it becomes active. Chrome does not pause the element and the stream is played automatically when it becomes active again.
My conclusion is that if the intent of the spec is that playback should not resume, it must explicitly state that the element must be paused. Otherwise, the text saying that the element will not automatically play a stream that becomes active should be removed.

I would also like clarification about what should happen to the duration and currentTime fields in the HTML element.
Based on the HTML spec, it looks like duration should change from infinity to the time of the last frame. The mediacapture-main spec says nothing about duration, and, in practice, Firefox, Edge and Chrome always keep it as Inifinity, even if the stream has ended.

With regards to currentTime, the spec says  the initial value is 0 and the values increments linearly in real time whenever the stream is playing. Can it be reset to zero if the stream ends (and possibly restarts)? 
In practice, Edge and Chrome reset to zero and start increasing currentTime again when the stream becomes active. The version of Firefox I tried (61.0b13) does not reset to zero, but it seems to have a bug since it does not continue increasing currentTime after the stream becomes active again.

**Comment by jan-ivar** [comment]
I believe we have a couple of issues filed for this already:
 * https://github.com/w3c/mediacapture-main/issues/518 covers *"[overriding] the condition for when the media element has ended playback to support MediaStreams, we'd get the algorithm with events and state for free."* (first questions here)
 * https://github.com/w3c/mediacapture-main/issues/519 is the corollary for states and events when resuming playback from tracks added to a stream.
 * https://github.com/w3c/mediacapture-main/issues/453 is similar to https://github.com/w3c/mediacapture-main/issues/519 but also covers tracks added to a `.srcObject` stream for the first time.

Let's move discussion to the above issues where appropriate, and discuss remaining questions here:

>  ... is this mandating that the element must be paused when it becomes ended?

I believe so. [html](https://html.spec.whatwg.org/multipage/media.html#paused-for-in-band-content) already pauses at the end: *"When the current playback position reaches the end of the media resource when the direction of playback is forwards, ... If the media element has ended playback, the direction of playback is forwards, and paused is false, then ... Fire an event named pause at the media element. ... Fire an event named ended at the media element."*

So it seems reasonable that the playback-ending behavior of a track ending or being removed should have that effect as well.

Unfortunately, an impedance mismatch is the html spec derives a lot of its states from playback position, a concept missing with streams and tracks).

We probably either need to provide alternate prose for all these things, unless we can somehow map stream and track actions to playback position somehow?

> Can it be reset to zero if the stream ends (and possibly restarts)?

Seems sensible to me.

**Comment by alvestrand** [comment]
Seems like moving currentTime to zero when a stream resumes is bad semantics, because it gives two meanings to "the content at position zero" (old and new).
It's more consistent to continue from current position.
(Besides, someone might some day implement a scrollback buffer on the HTML Media element when fed from MediaStreams...)

**Comment by guidou** [comment]
Closing this issue since the language of the spec has been changed and it no longer talks about setting the ended attribute, but redefines the concept of "ended playback" when the media element plays a MediaStream.
