### ISSUE TITLE
Should getUserMedia be functional in SecureContext only?

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-main#540]
Following on https://github.com/w3c/webrtc-pc/issues/1945, we might want to update the spec according browser behavior. Currently getUserMedia is rejecting for non secure origins in most (all?) browsers.

A follow-up question might be whether we can further tighten this, for instance:
- Make getSupportedConstraints return an empty dictionary on non secure origins.
- Make enumerateDevices reject on non secure origins.
- Make getUserMedia SecureContext
- Make mediaDevices SecureContext

**Comment by jan-ivar** [comment]
> * Make getSupportedConstraints return an empty dictionary on non secure origins.

Constrainable properties is a lateral concept, but so far *getUserMedia* is alone in using `min`, `exact` (and sometimes `max`) constraints for discovery, which truly requires this feature detection mechanism.

All future features of this caliber will likely be limited to secure contexts in some way, so yes.

> * Make enumerateDevices reject on non secure origins.

enumerateDevices is also used by [*setSinkId*](https://w3c.github.io/mediacapture-output/#dom-htmlmediaelement-setsinkid), which we should limit as well, so yes.¹

> * Make getUserMedia SecureContext

Means `("getUserMedia" in navigator.mediaDevices) == false`, i.e. `TypeError` on attempted calls.²

> * Make mediaDevices SecureContext

Means `("mediaDevices" in navigator) == false`, i.e. `TypeError` on attempted calls.
Means `("getUserMedia" in navigator.mediaDevices) == false` would *trigger* (!) `TypeError`.

In an ideal world, yes. I think all these methods are beyond http.

This would obviously break some sites in http, but maybe that's ok?

<sub>1. Firefox still supports *getUserMedia* in http, but we agree to [fix that](https://bugzilla.mozilla.org/show_bug.cgi?id=1335740).</sub>
<sub>2. I found this out in https://github.com/w3c/mediacapture-screen-share/issues/77#issuecomment-421006931</sub>

**Comment by cynthia** [comment]
Ping if there was any consensus/decision on this.

**Comment by youennf** [comment]
The minutes are at https://www.w3.org/2018/10/22-webrtc-minutes#item02
The consensus is to make MediaDevices (including getUserMedia, enumerateDevices, getDisplayMedia) SecureContext.
I'll write a PR for that.

**Comment by cynthia** [comment]
Awesome! We'll close the issue on our side when the PR lands then. Thanks a lot.

**Comment by cynthia** [comment]
One more thing.

https://github.com/w3c/webrtc-pc/issues/1945 is about peer connections requiring secure context, was there strong disagreement on this? If this doesn't look like it would break a lot of live web content we would want to know if that is also doable.

Considering that most fundamental building blocks of RTC require a secure context, I think this should be safe to do, but if you think otherwise please let us know.

**Comment by youennf** [comment]
> [w3c/webrtc-pc#1945](https://github.com/w3c/webrtc-pc/issues/1945) is about peer connections requiring secure context, was there strong disagreement on this? If this doesn't look like it would break a lot of live web content we would want to know if that is also doable.

I do not think this was explicitly discussed at TPAC.
This is point 4 of https://github.com/w3c/webrtc-pc/issues/1945#issuecomment-420510604
I would suggest continuing the discussion on that specific point there.

**Comment by youennf** [comment]
Filed PR https://github.com/w3c/mediacapture-main/pull/550
It also includes legacy navigator.getUserMedia.
Will write WPT tests once we agree on the PR.

**Comment by alvestrand** [comment]
WG meeting at TPAC approved this change, which was merged in #550.
