### ISSUE TITLE
enumerateDevices() doesn't mention how to handle OS device permissions

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#541]
Android apps (including browsers) need OS device permissions—which trigger a user prompt—in order to enumerate devices. The spec needs to mention how to deal with this.

[enumerateDevices()](https://w3c.github.io/mediacapture-main/getusermedia.html#dom-mediadevices-enumeratedevices) mentions permission only wrt labels, and cannot fail.

Having this method [trigger prompts](https://bugzilla.mozilla.org/show_bug.cgi?id=1493318) seems undesirable.

What should the method do in this case? What should it return?

**Comment by youennf** [comment]
WebKit is not providing real device information until getUserMedia access is granted.
By default, enumerateDevices will provide default configurations for a given device, typically a microphone and a camera for a laptop.

Provided device ids are not persistent (maybe there should be no device ID in that case) and labels are hidden.

This should give the minimum meaningful information for a web application to decide whether to call getUserMedia and with which constraints.

A devicechange event can be used to convey to the web application that the full information is available.

**Comment by jan-ivar** [comment]
Firefox in its default configuration does provide real device info before getUserMedia access is first granted, minus labels. I believe this is to spec.

While those deviceIds are not persistent *at that moment*, they're immediately usable in getUserMedia constraints and *become* persistent *if* the user grants getUserMedia in that session. If the user doesn't grant anything, the ids expire at the end of the session.

> WebKit [...] enumerateDevices will provide default configurations for a given device, typically a microphone and a camera for a laptop.

Firefox can be configured with [privacy.resistFingerprinting=true](https://wiki.mozilla.org/Security/Fingerprinting) that does this, but persistently and it also ignores constraints.

**Comment by jan-ivar** [comment]
That said, I like the idea of solving the lack of OS permissions the way @youennf suggests. I.e. barring more information, return one default mic and one default camera with deviceIds.

But I think once OS permissions are granted, we should honor those deviceIds to open the real devices the UA would have chosen if unconstrained.

I also agree it's appropriate to fire a *devicechange* event once we learn what the user has, unless the user happens to have exactly one mic and one camera perhaps?

**Comment by alvestrand** [comment]
Pinging @guidou - what do we currently do in Chrome?

**Comment by alvestrand** [comment]
@dom, we can't assign this issue to @youennf. Can you help out?

**Comment by dontcallmedom** [comment]
done

**Comment by jan-ivar** [comment]
I may be coming around to @henbos's suggestion today that perhaps *enumerateDevices* should just reject with an error in this case. `NotAllowedError` maybe?

**Comment by youennf** [comment]
There are a couple of options here:
- throw NotAllowedError
- return an empty set
- return a filtered set of devices: typical device configuration, MediaDeviceInfo only containing kind

**Comment by guidou** [comment]
> Pinging @guidou - what do we currently do in Chrome?

If I disable all permissions for Chrome and call enumerateDevices, I get a list of real devices without labels, as per the spec. I never get a prompt requesting permission to enumerate devices. 
The same happens with Brave, Opera and other Chromium-based browsers.

Maybe Chrome uses some API to enumerate devices that does not require permissions.

**Comment by jan-ivar** [comment]
Thanks, @guidou I've tested those now and can confirm. I'll reach out to our Android folks to see what the problem is.
