### ISSUE TITLE
NotAllowedError or SecurityError over Feature Policy?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#545]
https://github.com/WICG/feature-policy does not mention "Error", but it's [explainer document](https://docs.google.com/document/d/1k0Ua-ZWlM_PsFCFdLMa8kaVTo32PeNZ4G7FFHqpFx4E/edit#) does:

*"The way that features get disabled varies from feature-to-feature. Permission-like features, such as geolocation, already fail sensibly and return error values when the permission to use it is missing. When such a feature is disabled by Feature Policy, it would be* ***equivalent to a denied permission*** *and would exercise a similar code path (perhaps* ***returning a different error code*** *)."*

But then [WPT](https://github.com/web-platform-tests/wpt/blob/master/mediacapture-streams/MediaStream-default-feature-policy.https.html#L40
) tests for `NotAllowedError`, which works in Chrome.

But then [getUserMedia](https://w3c.github.io/mediacapture-main/getusermedia.html#dom-mediadevices-getusermedia) says: *"If the current settings object's responsible document is NOT allowed to use the feature indicated by attribute name allowusermedia, return a promise rejected with a DOMException object whose name attribute has the value `SecurityError`."* (which is outdated and needs to point to the right place which is not `allowusermedia`)
 
But then Firefox Nightly [just merged](https://bugzilla.mozilla.org/show_bug.cgi?id=1497141) with `NotAllowedError` today, to match Chrome.

But then Chrome team just filed [issue 892042](https://bugs.chromium.org/p/chromium/issues/detail?id=892042) to switch to `SecurityError`.

What's best practice here? cc @annevk @alvestrand @guidou @bakulf

**Comment by guidou** [comment]
I'm fine with changing the spec to NotAllowedError to match Chrome and Firefox.
Based on wpt.fyi, Edge and Safari don't implement this yet.

**Comment by jan-ivar** [comment]
Follow-up question: In an iframe, is there a Feature Policy way to learn what's allowed? Or do we plan on overloading `navigator.permissions.query` with this?

**Comment by youennf** [comment]
Safari implements part of it and use NotAllowedError.
I would vote to keep it this way.

**Comment by henbos** [comment]
Let's go with NotAllowedError

**Comment by alvestrand** [comment]
"me too".
Editors consensus: Stay with NotAllowedError. Jan-Ivar to go around closing all the bugs.
