### ISSUE TITLE
Typo in sink label

### ISSUE THREAD

**Issue by katranci** [w3c/mediacapture-main#547]
Under [The model: sources, sinks, constraints, and settings section](https://www.w3.org/TR/mediacapture-streams/#the-model-sources-sinks-constraints-and-settings), the spec mentions two sinks Y and Z but the sinks are labeled as X and Z in the illustration.

![image](https://user-images.githubusercontent.com/61077/46913521-6b71fd80-cf86-11e8-90e8-26d042eefc79.png)

**Comment by henbos** [comment]
Should be: assigned to armax00. What do we have to do to make him assignable and have the rights to change labels?
