### ISSUE TITLE
Clarify that enumerateDevices must not expose devices that a given context cannot use through getUserMedia

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-main#549]
getUserMedia access to camera/mics/speakers can be controlled by FeaturePolicy.
In case, feature policy disables camera access, enumerateDevices should not enumerate camera devices. Ditto for other types of devices.

From my reading of the spec, this is the required behavior.
I haven't found a WPT test though and I am unsure whether browsers are actually implementing that.

A WPT test would be good if this is actually not covered.
Maybe a note in the spec if we see browsers not implementing this (although a test might be more effective than a note).

**Comment by jan-ivar** [comment]
I think this is a good idea. It'd mean *enumerateDevices* would resolve empty from cross-origin iframes unless either `allow="camera"`, `allow="microphone"`, `allow="speaker"`, or any combination of those were specified, and even then you'd only get the relevant info.

> From my reading of the spec, this is the required behavior.

It seems to hinge on the definition of "available". I think this deserves more specific mention. I'll work on a PR.
