### ISSUE TITLE
Specify a way for WebDriver to add/remove/setup capture devices

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-main#554]
As discussed during the WPT F2F at 2018 TPAC, the way to go might be to specify a way to add/remove/setup capture devices through WebDriver.
This might first be implemented as test runner APIs available only in browser CI and later within browser web driver implementations. These test runner APIs will be called within resources/testdriver-vendor.js.
This should allow us to improve WPT test coverage in areas such as ondevicechange, getUserMedia constraints...

**Comment by youennf** [comment]
We could probably author a separate document for now and merge it as an "automation" chapter later on if it proves to be easier this way.

**Comment by dontcallmedom** [comment]
+1 to @youennf - this would allow us in particular to assess if/when the automation part would get implemented in a way that's compatible with our Recommendation track requirements.

**Comment by agouaillard-cosmo** [comment]
I mentionned the automation chapter because that s what the WebDriver spec authors mentionned as the mechanism to add webdriver command in the future. We do not extend the webdriver doc itself, but we should add an automation chapter in the corresponding feature doc.

**Comment by alvestrand** [comment]
Some months back I added a fake-device API in Chromium:

https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/mediastream/testing/internals_media_stream.idl?type=cs&sq=package:chromium&g=0

Never got around to wiring it up to the actual fake-device driver. But it was a start.

**Comment by agouaillard-cosmo** [comment]
I believe it should be orthogonal to the permission automation. Permission
should only deal with the prompt.

the tricky part for the fake-device / mock capturer is that it should be
able to understand all the GUM constraints.

**Comment by armax00** [comment]
I would say that it is the case that the API should allow to set supported constrainable properties, though I would imagine that this API should expose a way to set capabilities (which means that at least the syntax should be a subset of GUM, avoiding advanced and ideal values).

@agouaillard-cosmo I guess the "tricky part" you are pointing at is the difficulty to track all the extensions that define their own GUM constrainable properties?

**Comment by guest271314** [comment]
> Some months back I added a fake-device API in Chromium:
> 
> https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/mediastream/testing/internals_media_stream.idl?type=cs&sq=package:chromium&g=0
> 
> Never got around to wiring it up to the actual fake-device driver. But it was a start.

If read the code and intent correctly, would that allow a `<video>` (or any other HTML) element to be selected as a "capture device" (where capture could continue even where the `src` is changed)?

**Comment by youennf** [comment]
I wrote an initial draft at https://youennf.github.io/media-capture-automation/media-capture-automation.html.
Comments most welcome.

**Comment by jan-ivar** [comment]
Closed with the adoption of [mediacapture-automation](https://w3c.github.io/mediacapture-automation/#extension-commands).
