### ISSUE TITLE
MediaStream in HTMLMediaElement: Does it have a first frame?

### ISSUE THREAD

**Issue by Pehrsons** [w3c/mediacapture-main#555]
I originally filed this issue on the media element spec: https://github.com/whatwg/html/issues/4215.

I'm filing an issue here since I reckon the editors here should have a say on that issue's resolution.

**Comment by Pehrsons** [comment]
whatwg/media seems to say that MediaStreams do indeed have a first frame, and there are other types of streams that can be real-time and still have a first frame.

This makes sense to me, and the logic checks out. Yet no major browser engine seems to load the first frame before playing, see https://github.com/whatwg/html/issues/4215#issuecomment-446558960.

Do people here know whether there's a rationale behind the current behavior, or if it's an oversight in the implementations?

Firefox's behavior predates my time at Mozilla, so I cannot comment on the reasoning there. I'd be curious to hear the other vendors' arguments.

**Comment by eric-carlson** [comment]
> whatwg/media seems to say that MediaStreams do indeed have a first frame, and there are other types of streams that can be real-time and still have a first frame.
> 
> This makes sense to me, and the logic checks out. Yet no major browser engine seems to load the first frame before playing, see [whatwg/html#4215 (comment)](https://github.com/whatwg/html/issues/4215#issuecomment-446558960).
> 
I agree that a stream logically has a first frame, and I can't think of a reason to not render it. 


> Do people here know whether there's a rationale behind the current behavior, or if it's an oversight in the implementations?
> 
> Firefox's behavior predates my time at Mozilla, so I cannot comment on the reasoning there. I'd be curious to hear the other vendors' arguments.

WebKit's behavior is an oversight. I have filed bug [192629](https://bugs.webkit.org/show_bug.cgi?id=192629) to change the behavior.

**Comment by Pehrsons** [comment]
Thanks for the input everyone. I'm about to fix this in Firefox in [bug 1306999](https://bugzilla.mozilla.org/show_bug.cgi?id=1306999). I consider this issue closed.
