### ISSUE TITLE
Clarify request for permission is for both audio *and* video (editorial).

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#556]
The [getUserMedia](https://w3c.github.io/mediacapture-main/getusermedia.html#dom-mediadevices-getusermedia) algorithm says: *"[Request permission to use](https://w3c.github.io/permissions/#request-permission-to-use) a PermissionDescriptor with its name member set to the permission name associated with *kind* (e.g. "camera", "microphone")"*

But it's a bit buggy what *kind* refers to here, since we're outside the for-loop of *requestedMediaTypes*. I suspect this used to be in the loop at some point.

We either need to move it back in, or phrase it such that it is clear that UAs are encouraged to use a combined permission prompt when requesting permission for both camera and microphone at the same time, in spite of the permission specification's algorithm not having an accommodation for this.

**Comment by alvestrand** [comment]
We have language in the spec already that encourages combining permission requests that occur in a single event loop execution: https://w3c.github.io/mediacapture-main/getusermedia.html#implementation-suggestions - "Best Practice 3: Handling multiple devices"

The easiest thing to do is probably to move "request permission" into the FOR loop, with a pointer to the relevant best practice section.
