### ISSUE TITLE
Add note on applicability of constraints to tracks in other specs

### ISSUE THREAD

**Issue by henbos** [w3c/mediacapture-main#578]
Attempting to interpret how constraints defined in this spec, which was written with MediaStreamTracks generated by getUserMedia() in mind, apply to MediaStreamTracks generated in the contexts of other specs (such as webrtc-pc or mediacapture-screen-share), leads to confusion.

The solution to this under-specificity was to explicitly define what constraints do in the respective specs.

To make this even more clear, let's add a note to mediacapture-main spec clarifying that the constraints defined in this spec are only applicable to MediaStreamTracks generated by getUserMedia(), unless otherwise specified in other specs.

**Comment by youennf** [comment]
I agree this should be clarified to know which constraints are to be supported and which are not.
If we think some properties should be/can easily be supported for all sources of a given track type (say video), requirements should be put here and not repeated in each sub spec.
