### ISSUE TITLE
Travis is failing git checkout with "reference is not a tree"

### ISSUE THREAD

**Issue by henbos** [w3c/mediacapture-main#581]
We tried with three different PRs and get (#576, #579 and #580 ):

> Unhandled rejection Error: Command failed: /usr/bin/git checkout 7b144b3b83ce296d5b29c5e4fc2ea2a65e9d3f32
> fatal: reference is not a tree: 7b144b3b83ce296d5b29c5e4fc2ea2a65e9d3f32

The last one was uploaded from a different checkout of a different fork on a different machine.

@dontcallmedom are you the right person to take a look at Travis failures?

**Comment by alvestrand** [comment]
The usual reason is that someone's done a history rewrite on the repo (often a bad idea).
This is the reason why it's often more convenient to check out tags than to check out hashes.

**Comment by dontcallmedom** [comment]
once #592 is merged, Travis CI should be happy again (existing pull requests would need to be rebased)
