### ISSUE TITLE
Remove or rename 'volume'

### ISSUE THREAD

**Issue by armax00** [w3c/mediacapture-main#585]
The 'volume' constrainable property is defined as being a multiplier applied to the linear audio samples. This means that this property does not control the volume of the audio device capture (which can be adjusted by the user and determined by the OS/HW) but rather the gain. More precisely, since the range allowed is between 0 and 1, this constrainable property controls the loss (gain between 0 and 1).

I propose that this property should be renamed from volume to either gain or loss.

Further, the description of volume in https://www.w3.org/TR/mediacapture-streams/#def-constraint-volume should be clearer in identifying it as gain/loss.

**Comment by alvestrand** [comment]
Seems to not be implemented in Safari or Firefox at the moment.

**Comment by guidou** [comment]
My interpretation of the spec is not that it is a multiplier applied to the samples, even though the word multiplier is used. I interpret that the value of the property is a value between 0 to 1 such that the value, when multiplied by a constant (or maybe a function) results in the maximum volume and 0 the minimum. 
This said, I would instead propose to remove this from the spec. No browser implements it, and there seems to be little demand for it.

**Comment by armax00** [comment]
Based on a chat with alvestrand, it was clarified that this constrainable property was meant to determine loss, more precisely an additional layer of processing on a track to lower the volume of the track. I am not sure about the initial intention and use-case for such a constraint, but it looks to me the constrainable property should either be removed or renamed.

**Comment by henbos** [comment]
Shall we remove it? ;)

**Comment by guidou** [comment]
+1 to remove it

**Comment by eric-carlson** [comment]
WebKit implements 'volume', but we won't object to removing it.

**Comment by alvestrand** [comment]
seems that only Safari has implemented it, and don't object to removing it.
Marking "ready for PR".

**Comment by armax00** [comment]
Anything missing on the PR/bug?

**Comment by foolip** [comment]
@eric-carlson is there a WebKit bug tracking the removal of this? There's an [Intent to Deprecate and Remove: volume property](https://groups.google.com/a/chromium.org/d/msg/blink-dev/8-Qn7pu41Kk/BWl_CjilBAAJ) on blink-dev now, which ought to leave WebKit as the only engine supporting it.

**Comment by eric-carlson** [comment]
> @eric-carlson is there a WebKit bug tracking the removal of this? There's an [Intent to Deprecate and Remove: volume property](https://groups.google.com/a/chromium.org/d/msg/blink-dev/8-Qn7pu41Kk/BWl_CjilBAAJ) on blink-dev now, which ought to leave WebKit as the only engine supporting it.

@foolip yes, I filed [[MediaStream] remove 'volume' constraint](https://bugs.webkit.org/show_bug.cgi?id=198295)

**Comment by foolip** [comment]
Thanks Eric!

**Comment by pavelserbajlo** [comment]
I understand the intent here, but removal of this has caused a regression for us as we'd rely on this in order to normalize our comparative audio pipeline processing in Chrome. Since decision has been made to remove this, what are the other ways to read the microphone input gain for the developers?
