### ISSUE TITLE
Clarification needed on HTMLMediaElement attributes that carry over

### ISSUE THREAD

**Issue by Pehrsons** [w3c/mediacapture-main#599]
Imagine the following code:

```
let v = document.createElement("video");

v.playbackRate = 0.5;
console.log(v.playbackRate);

v.srcObject = new MediaStream();
console.log(v.playbackRate);

v.srcObject = null;
console.log(v.playbackRate);
```

Per the spec the first two logged lines will be `0.5` and `1`, respectively. But what should be returned the third time? Does it keep `1`, or is it reset to `0.5` which it had before the `MediaStream` was assigned?

The same applies to the `defaultPlaybackRate` and `preload` attributes.

The spec also says to not fire `ratechange` on setting `playbackRate` or `defaultPlaybackRate`. That makes sense since the value doesn't change. But shouldn't `ratechange` reasonably be fired if the attribute was changed to `1` when the `MediaStream` was assigned, and (possibly) when it changes back after being unassigned?

**Comment by Pehrsons** [comment]
I eventually found this in the HTMLMediaElement spec:

> The media element load algorithm consists of the following steps.
> 1.   Abort any already-running instance of the resource selection algorithm for this element.
> 2.   Let pending tasks be a list of all tasks from the media element's media element event task source in one of the task queues.
> 3.   For each task in pending tasks that would resolve pending play promises or reject pending play promises, immediately resolve or reject those promises in the order the corresponding tasks were queued.
> 4.   Remove each task in pending tasks from its task queue
> 
> Basically, pending events and callbacks are discarded and promises in-flight to be resolved/rejected are resolved/rejected immediately when the media element starts loading a new resource.

That takes care of my "ratechange" concern. But the question remains of what values `playbackRate`, `defaultPlaybackRate` and `preload` should have when changing to a non-MediaStream source after having had a MediaStream source..

**Comment by jan-ivar** [comment]
> But what should be returned the third time?

`0.5`, because [html](https://html.spec.whatwg.org/multipage/media.html#dom-media-playbackrate) says *"on getting it must return the last value it was set to, ..."*, which was `0.5`.

[Mediacapture](https://w3c.github.io/mediacapture-main/getusermedia.html#mediastreams-in-media-elements) says: *"On setting: ignored. On getting: return 1.0"*. It doesn't say *"set [state] to 1"*.

This might have been clearer had the HTML spec used internal slots, but I think the principle still holds, that mediacapture does not say to alter any (internal and implicit) state.

So as soon as the element is no longer associated with a stream, we should revert to html.

Now, it continues: *"Therefore, this attribute MUST always have the value 1.0 and any attempt to alter it MUST be ignored. Note that this also means that the ratechange event will not fire."* - but taken together, this appears to be talking about the "attribute" as an API, i.e. net-JS-observable requirements.

That's my reading of the current language, but I agree could be clearer. Thoughts?

**Comment by jan-ivar** [comment]
A suggestion was made to test existing behavior before deciding on a PR to merge here.

**Comment by jan-ivar** [comment]
So here's my brief test with https://jsfiddle.net/jib1/avr1w8k0/ basically:
```
    video.onratechange = () => console.log("ratechange");
    video.playbackRate = 0.5;
    console.log(video.playbackRate);
    video.srcObject = await navigator.mediaDevices.getUserMedia({video: true});
    console.log(video.playbackRate);
    video.playbackRate = 0.7;
    console.log(video.playbackRate);
    video.srcObject = null;
    console.log(video.playbackRate);
```
The results show variance and that none are to spec. They all fire ratechange when they shouldn't, and none of them preserve the non-stream value.

Firefox:
```
0.5
ratechange
1
0.7
1
ratechange
```
Chrome: 
```
0.5
ratechange
1
1
1
ratechange
```
Safari:
```
0.5
ratechange
1
0.7
1
ratechange
```
Edge:
```
0.5
ratechange
1
InvalidStateError
```

From my reading of the spec, clarified by https://github.com/w3c/mediacapture-main/pull/600 it should be:
```
0.5
1
1
0.5
```
Is there one we prefer? @youennf @Pehrsons

**Comment by youennf** [comment]
It seems all browsers set the ratechange to 1 when setting a srcObject MediaStream.
It seems Chrome, Firefox and Safari all keep/set it to 1 when setting srcObject to null.
I would tend to keep these two behaviors.

The fact that the setter does nothing in case of media stream has the small benefit of allowing an application to detect that setting a ratechange is a no-op. This should also preclude the second range change event. This is Chrome behavior and I think this is also the intended behavior of Safari.
That would mean something like: 0.5, 1, 1, 1

As of the ratechange events, there should be one whenever changing the value, right?

**Comment by jan-ivar** [comment]
So I think you're saying
```
0.5
ratechange
1
1
1
```

**Comment by youennf** [comment]
One option would be to say that:
1. setting a MediaStream srcObject sets the rate to 1 (not in the spec right now)
2. once a MediaStream srcObject is set, setting the rate is a no-op (in the spec right now)
Step 1 should then say whether setting the rate triggers a ratechange event or not. I would tend to allow a ratechange event there.
Your test case would give something like:
`0.5
ratechange
1
rate change
1
1`

**Comment by jan-ivar** [comment]
@youennf I've updated the PR. PTAL.

**Comment by Pehrsons** [comment]
> So here's my brief test with https://jsfiddle.net/jib1/avr1w8k0/ basically:
> 
> ```
>     video.onratechange = () => console.log("ratechange");
>     video.playbackRate = 0.5;
>     console.log(video.playbackRate);
>     video.srcObject = await navigator.mediaDevices.getUserMedia({video: true});
>     console.log(video.playbackRate);
>     video.playbackRate = 0.7;
>     console.log(video.playbackRate);
>     video.srcObject = null;
>     console.log(video.playbackRate);
> ```
> 
> The results show variance and that none are to spec. They all fire ratechange when they shouldn't, and none of them preserve the non-stream value.
> 
> Firefox:
> 
> ```
> 0.5
> ratechange
> 1
> 0.7
> 1
> ratechange
> ```
> 
> Chrome:
> 
> ```
> 0.5
> ratechange
> 1
> 1
> 1
> ratechange
> ```
> 
> Safari:
> 
> ```
> 0.5
> ratechange
> 1
> 0.7
> 1
> ratechange
> ```
> 
> Edge:
> 
> ```
> 0.5
> ratechange
> 1
> InvalidStateError
> ```
> 
> From my reading of the spec, clarified by #600 it should be:
> 
> ```
> 0.5
> 1
> 1
> 0.5
> ```
> 
> Is there one we prefer? @youennf @Pehrsons

You're fooling yourself, because the [media element load algorithm](https://html.spec.whatwg.org/multipage/media.html#media-element-load-algorithm) contains this:
> 7. Set the playbackRate attribute to the value of the defaultPlaybackRate attribute.

My initial example is equally bad.

Setting both `defaultPlaybackRate` and `playbackRate` will give a better view of the current state.

That said, this example's tracking of "ratechange" provides insight into the corner case where `playbackRate` gets set to `defaultPlaybackRate` after having just set `srcObject` to a `MediaStream`. Should that update of `playbackRate` dispatch a "ratechange"? Not per the above (well, before the fiddle anyway).

**Comment by Pehrsons** [comment]
I've updated your test fiddle to https://jsfiddle.net/pehrsons/pk8mo36d/

The async waiting for gUM also let one "ratechange" slip through that would otherwise have been cancelled (per [my 2nd comment](https://github.com/w3c/mediacapture-main/issues/599#issuecomment-496561453)).

```
    let stream = await navigator.mediaDevices.getUserMedia({video: true});
    video.onratechange = () => console.log("ratechange");
    video.defaultPlaybackRate = 0.5;
    video.playbackRate = 0.5;
    console.log(video.playbackRate);
    video.srcObject = stream;
    console.log(video.playbackRate);
    video.defaultPlaybackRate = 0.7;
    video.playbackRate = 0.7;
    console.log(video.playbackRate);
    video.srcObject = null;
    console.log(video.playbackRate);
    for (let t of stream.getTracks()) {
      t.stop();
    }
```

Firefox:
```
0.5
0.5
0.7
0.7
```

Chrome:
```
0.5
1
1
0.5
```

Safari:
```
0.5
0.5
0.7
0.7
```

Unfortunately I'm not able to test Edge.

It seems to me that only chrome attempted to implement this part of the spec, and their implementation seems to agree with what [jib outlined above](https://github.com/w3c/mediacapture-main/issues/599#issuecomment-496562096).

**Comment by jan-ivar** [comment]
Thanks Andreas! In light of those findings, I propose reverting the PR to what I had originally, based on my first https://github.com/w3c/mediacapture-main/issues/599#issuecomment-496562096.

**Comment by youennf** [comment]
> video.defaultPlaybackRate = 0.5;
>     video.playbackRate = 0.5;

We should change the example to:
```
video.defaultPlaybackRate = 0.5;
video.playbackRate = 0.6;
```

In that case, I would expect the results to be:
```
0.5
1
1
0.6
```
Do we agree on this?

**Comment by jan-ivar** [comment]
Yes, or maybe what Chrome [gives me](https://jsfiddle.net/jib1/kga04vLt/)
```
0.6
1
1
0.5
ratechange
```

The [media element load algorithm](https://html.spec.whatwg.org/multipage/media.html#media-element-load-algorithm) says:
> 7. Set the playbackRate attribute to the value of the defaultPlaybackRate attribute.

Which is *after* step 3-4 which clears old tasks (silencing events for changes up to that point).

On the one hand, there's no step 8 here that says to fire the `ratechange` event. However, elsewhere it says:

> When the defaultPlaybackRate or playbackRate attributes change value (either by being set by script or by being changed directly by the user agent, e.g. in response to user control) the user agent must queue a task to fire an event named ratechange at the media element.

Do explicit algorithms invoke other algorithms implicitly in that spec?

**Comment by youennf** [comment]
Here is my take on jsfiddle: https://jsfiddle.net/sdjq3Laf/ adding a bunch of setTimeout everywhere.
Chrome and Safari have the same behavior in that case. Safari checks for detecting a MediaStream srcObject is not kicking synchronously.

When setting srcObject to MediaStream, the playbackRate is changed from 0.6 to 1, but no corresponding ratechange event is fired.
This seems to go well with your initial interpretation.

It seems simpler to me to just state that on setting srcObject, playbackRate is set to 1, which would then trigger an event (though the html media spec is fuzzy there) if it was not equal to 1 initially.

**Comment by jan-ivar** [comment]
Yeah I think it makes sense to say the event should to fire both for `0.6`→`1` and `1`→`0.5`, or not at all.

**Comment by jan-ivar** [comment]
To clear up the fuzziness, [all browsers](https://jsfiddle.net/jib1/kuzptma2/9/) appear to interpret the html media spec to mean events should fire from the load algorithm for `0.6`→`0.5` from `video.src="foo"`, so that points to firing events.

We just have to figure out prose for that.

**Comment by Pehrsons** [comment]
> Here is my take on jsfiddle: https://jsfiddle.net/sdjq3Laf/ adding a bunch of setTimeout everywhere.
> Chrome and Safari have the same behavior in that case. Safari checks for detecting a MediaStream srcObject is not kicking synchronously.

We should define when this check for a MediaStream starts and stops being valid. I suggest we make it synchronous in the srcObject setter, because of this example:
```
let v = document.createElemenet("video");
v.srcObject = await navigator.mediaDevices.getUserMedia({video: true});
v.play();
await new Promise(r => setTimeout(r, 1000));
v.srcObject = null;
v.src = mediaFileUrl;
v.load(); // runs the load algorithm, which synchronously sets playbackRate to defaultPlaybackRate
```

> When setting srcObject to MediaStream, the playbackRate is changed from 0.6 to 1, but no corresponding ratechange event is fired.
> This seems to go well with your initial interpretation.
> 
> It seems slightly better to state that on setting srcObject, playbackRate is set to 1, which would then trigger an event (though the html media spec is fuzzy there) if it was not equal to 1 initially.

I don't find it fuzzy. If you set `playbackRate` to a new value and then run the load algorithm, the "ratechange" event is cancelled. If you set it after having run the load algorithm, "ratechange" is not cancelled (unless the load algorithm runs again before "ratechange" is dispatched). Setting `srcObject` synchronously runs the load algorithm, so if we want to refer to setting these attributes in the `srcObject` setter, we need to say whether they should be set before or after running the load algorithm. Note that doing it after the load algorithm could lead to 3 "ratechange" events:
1) playbackRate = defaultPlaybackRate per the load algorithm
2) defaultPlaybackRate = 1
3) playbackRate = 1

How much trouble would it be to define the special cases of these attributes in the media element spec instead?

**Comment by jan-ivar** [comment]
After discussing with @Pehrsons, the simplest approach was to revert the PR (https://github.com/w3c/mediacapture-main/pull/600) to what I had originally as of https://github.com/w3c/mediacapture-main/issues/599#issuecomment-496562096, as that's the only version that naturally reverts to pre-stream values.

This should match Chrome behavior. I added a note about the edge case where `ratechange` is fired.
