### ISSUE TITLE
Remove "The relative order of the tracks in the set is User Agent defined and the API will never put any requirements on the order.", et al.

### ISSUE THREAD

**Issue by guest271314** [w3c/mediacapture-main#611]
Specify that when there is both an audio and a video track in a `MediaStream` the order of the `id` must be audio `0`, video `1`. 

Relevant specification language

>  The relative order of the tracks in the set is User Agent defined and the API will never put any requirements on the order.

> The conversion from the track set to the sequence is User Agent defined and the order does not have to be stable between calls.

> Since the order in the MediaStream 's track set is undefined, no requirements are put on how the AudioTrackList and VideoTrackList is ordered

If a `MediaStream` contains only a single track of kind audio or video nothing can be done, besides creating a complementary track for each missing track in the next file.

If a `MediaStream` contains both audio and video then the order described at the first sentence should be applied.

The reason for the change is for post-record editing, which becomes tedious when the order of the tracks is arbitrary.

Consider two `webm` files output by `MediaRecorder` at Chromium

```
$ ./mkvmerge -J 1.webm
{
  "attachments": [],
  "chapters": [],
  "container": {
    "properties": {
      "container_type": 17,
      "is_providing_timestamps": true,
      "muxing_application": "Chrome",
      "writing_application": "Chrome"
    },
    "recognized": true,
    "supported": true,
    "type": "Matroska"
  },
  "errors": [],
  "file_name": "1.webm",
  "global_tags": [],
  "identification_format_version": 12,
  "track_tags": [],
  "tracks": [
    {
      "codec": "Opus",
      "id": 0,
      "properties": {
        "audio_bits_per_sample": 32,
        "audio_channels": 1,
        "audio_sampling_frequency": 48000,
        "codec_id": "A_OPUS",
        "codec_private_data": "4f707573486561640101000080bb0000000000",
        "codec_private_length": 19,
        "default_track": true,
        "enabled_track": true,
        "forced_track": false,
        "language": "eng",
        "minimum_timestamp": 119000000,
        "number": 1,
        "uid": 40889044785409303
      },
      "type": "audio"
    },
    {
      "codec": "VP8",
      "id": 1,
      "properties": {
        "codec_id": "V_VP8",
        "codec_private_length": 0,
        "default_track": true,
        "display_dimensions": "1046x588",
        "display_unit": 0,
        "enabled_track": true,
        "forced_track": false,
        "language": "eng",
        "minimum_timestamp": 0,
        "number": 2,
        "pixel_dimensions": "1046x588",
        "uid": 17593832491204014
      },
      "type": "video"
    }
  ],
  "warnings": []
}

$ /mkvmerge -J 2.webm
{
  "attachments": [],
  "chapters": [],
  "container": {
    "properties": {
      "container_type": 17,
      "is_providing_timestamps": true,
      "muxing_application": "Chrome",
      "writing_application": "Chrome"
    },
    "recognized": true,
    "supported": true,
    "type": "Matroska"
  },
  "errors": [],
  "file_name": "2.webm",
  "global_tags": [],
  "identification_format_version": 12,
  "track_tags": [],
  "tracks": [
    {
      "codec": "VP8",
      "id": 0,
      "properties": {
        "codec_id": "V_VP8",
        "codec_private_length": 0,
        "default_track": true,
        "display_dimensions": "320x240",
        "display_unit": 0,
        "enabled_track": true,
        "forced_track": false,
        "language": "eng",
        "minimum_timestamp": 0,
        "number": 1,
        "pixel_dimensions": "320x240",
        "uid": 33743719209670163
      },
      "type": "video"
    },
    {
      "codec": "Opus",
      "id": 1,
      "properties": {
        "audio_bits_per_sample": 32,
        "audio_channels": 2,
        "audio_sampling_frequency": 48000,
        "codec_id": "A_OPUS",
        "codec_private_data": "4f707573486561640102000080bb0000000000",
        "codec_private_length": 19,
        "default_track": true,
        "enabled_track": true,
        "forced_track": false,
        "language": "eng",
        "minimum_timestamp": 8000000,
        "number": 2,
        "uid": 56209065175931709
      },
      "type": "audio"
    }
  ],
  "warnings": []
}
```

Not only does the number of channels need to be adjusted, though also, to merge the two files the developer needs to map which next track to append to the current track. For only two tracks that can be simple, for multiple tracks in arbitrary order, the task can become meticulous. 

This change will also provide uniformity for all implementations, for example, the ability to merge a `webm` file output by Chromium/Chrome and a `webm` file output by Firefox, setting aside for the moment that Chrome sets `audio_sampling_frequency` to `48000`, while Firefox sets the property to `44100`.

**Comment by youennf** [comment]
This seems like an issue to mediacapture-record spec, not media capture-main.

There was a similar issue with the order of tracks for addStream and adapter.js did a fix (https://bugs.webkit.org/show_bug.cgi?id=198402). I wonder whether this could cause trouble elsewhere.

**Comment by guest271314** [comment]
@youennf This specification is controlling as to track order, not `MediaRecorder`, correct? `MediaRecorder` specification authors could simply refer to the current language of this specification and state that  "the API will **never** put any requirements on the order."  As mentioned at OP the order the tracks appear in the actual WebM file is arbitrary, as demonstrated by the output of `mkvmerge -J`. 

Consistent track order is one part of the issue. As yet have not found or been successful with a workaround to set the `audio_sampling_frequency` at Chromium to any value, thus the default `48000` is always set. 

Chrome authors have deviated from the spirit of the WebM specification leading to this issue Issue [980822: MediaRecorder can generate invalid webm files](https://bugs.chromium.org/p/chromium/issues/detail?id=980822) being filed by a Firefox developer

> I will put this to the Media working group agenda at the next TPAC

stemming from this Firefox bug [Webm support for h.264 codec](https://bugzilla.mozilla.org/show_bug.cgi?id=1562862)  and a precursor bug [[Rethink] Support mkv|matroska|video/x-matroska in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1422891).

Essentially this issue is attempting to provide a venue to arrive at a tentative "consensus" as to whether specification authors and implementers of `MediaStream` and resulting WebM files are actually interested in producing consistent output that is, to an appreciable, "interoperable". Chrome authors of `MediaRecorder` had no issue implementing `h264` (openh264) and `avc1` codecs in a WebM container; Firefox developers are evidently not in accord with that decision, hence the Chromium issue. Have not tried Safari implementations, here.

While the topic is at hand the relevant stakeholders _could_ actually make an effort to agree upon 1) consistent track order; 2) which codecs could optionally be used, or explicitly not be used in a WebM container; 3) which `audio_sampling_frequency` should be used; 4) and if none of the above can be agreed upon by specification authors and implementers, then at least provide a _means_ for front-end users to agree upon how _they_ will proceed and implement the methods necessary for front-end developers to set track order, `audio_sampling_frequency`, for the purpose of interoperability.

**Comment by guest271314** [comment]
@youennf Own interest in the track order stems from the yet unmet task of porting `mkvmerge` to JavaScript. In lieu of a full port of the program written by hand and/or using Emscripten and/or `WebAssembly`, composed code that uses Native Messaging and Native File System in order to effectively use `mkvmerge` in the browser. While doing so encountered several issues with how the WebM files of browsers are output. When arbitrary track order exists, it is necessary to write code to determine the current and previous tracks. AFAIK there is no standardized means to do so, though there is an algorithm that can be adhered to [mkvmerge prints error when merging webm files from MediaRecorder at Chromium and MediaRecorder at Firefox. Why?](https://www.reddit.com/r/mkvtoolnix/comments/cdi824/mkvmerge_prints_error_when_merging_webm_files/etwhugs/). To merge two files there are only two choices. To merge four, twenty or a hundred files the algorithm _should_ be the same, though since there is no standardized roadmap of how to check that the map for appending is correct for all cases 

https://github.com/guest271314/native-messaging-mkvmerge/blob/master/app/native-messaging-mkvmerge.js#L187

```
    // https://www.reddit.com/r/mkvtoolnix/comments/cdi824/mkvmerge_prints_error_when_merging_webm_files/etwhugs/
    // 1. run `mkvmerge -J` file.webm on each input file
    // 2. determine which tracks go together
    // 3. create an appropriate --append-to argument from the algorithm in 2
    let filesMetadata = [];
    for (const fileName of fileNames) {
       await new Promise(resolve => {
         const getMetadata = ({body}) => {        
           port.onMessage.removeListener(getMetadata);
           filesMetadata.push(JSON.parse(body));
           resolve();
         };
         port.onMessage.addListener(getMetadata);
         port.postMessage({
           "message": "metadata",
           "body": `${cmd} ${metadata} ${fileName}`
         });
       });
    };
    // construct `--append-to` option for merging files where
    // tracks are not in consistent order; for example, WebM
    // files output by Chromium, Firefox MediaRecorder implementations 
    // Chromium => Opus: "id": 0, Firefox => Opus: "id": 1,
    // Chromium => VP8: "id": 1, Firefox => VP8: "id": 0 
    for (let i = 0; i < filesMetadata.length; i++) {
      const {tracks:currentTracks} = filesMetadata[i];
      const currentAudioTrack = getTrack(currentTracks, "audio").id;
      const currentVideoTrack = getTrack(currentTracks, "video").id;
      if (filesMetadata[i + 1]) {
        const {tracks:nextTracks} = filesMetadata[i + 1];
        const nextAudioTrack = getTrack(nextTracks, "audio").id;
        const nextVideoTrack = getTrack(nextTracks, "video").id;
        appendTo += `${i+1}:${nextAudioTrack}:${i}:${currentAudioTrack},${i+1}:${nextVideoTrack}:${i}:${currentVideoTrack},`;
      } 
      else {
        const {tracks:previousTracks} = filesMetadata[i - 1];
        const previousAudioTrack = getTrack(previousTracks, "audio").id;
        const previousVideoTrack = getTrack(previousTracks, "video").id;
        appendTo += `${i}:${currentAudioTrack}:${i-1}:${previousAudioTrack},${i}:${currentVideoTrack}:${i-1}:${previousVideoTrack}`;
      }
    };   
    // check if tracks are ordered AV,AV...AV or arbitrarily AV,VA,AV,AV,VA...AV
    const orderedTracks = filesMetadata.map(({tracks}) => tracks).every(([{type}]) => type === "audio");
    console.log(JSON.stringify({filesMetadata, orderedTracks, appendTo}, null, 2));
    port.onMessage.addListener(onNativeMessage);
    const message = {
      "message": "write",
      // if tracks in files are not ordered use `--append-to` option, else do not
      "body": `${cmd} ${options} ${outputFileName} ${!orderedTracks ? appendTo : ""} '[' ${fileNames.join(" ")} ']'`
    };
```
How to determine that the implementation of the algorithm is correct for any conceivable ordering tracks  of _N_ WebM files created by Chromium/Chrome, Firefox and Safari?

Would prefer to not have to ask the author of `mkvmerge` if the `--append-to` mapping is correct for every merging of files over two, for example, for a total of 10 files created at both Firefox and Chromium there could be various ways the order of the resulting map needs to be arranged - and, though outside the scope of this issue, then it must be determined if the audio have `1` or more channels, and adjust the audio tracks to be consistent among all files to be merged.

If the ordering of tracks was specified, and adhered to, that would be one less item to be concerned with when merging WebM (or Matroska) files created by using `MediaStream` and `MediaRecorder`. If the `audio_sampling_frequency` was also specified to be consistent among implementers, then we would have a semblance of consistency, or "interoperablity" at the front-end. Specifying tracks be ordered in a consistent, agreed upon sequence should not break the web at all; in fact such specificity would improve interoperabilty and provide an web environment where the web will be less likely to break, that is, if implementers stay in accord with the specification, as at least one Firefox developer apparently contends Chrome authors did not even though Chrome (*oogle) initially pushed for WebM for, ostensibly, similar reason.

**Comment by alvestrand** [comment]
Deep in the beginning of the group, people were arguing for various forms of ordering of tracks within a stream (first-added et al). In the end we decided that no agreement was to be reached on how order could be defined, and that applications would just have to be explicit about which tracks were active. (The place it mattered at the time was when playing into an HTML media element.)

I think the Right Solution is to make MediaRecorder have a method that allows you to specify which tracks go with what number in the container-dependent ordering.
