### ISSUE TITLE
Why does unmute event take between 30 to 60 seconds to dispatch? Does a canonical procedure exist to estimate when unmute will be dispatched?

### ISSUE THREAD

**Issue by guest271314** [w3c/mediacapture-main#614]
**Background**

At Chromium 78 neither `VP8` nor `VP9` codecs passed to `mimeType` of `MediaRecorder` result in the correct `width` and `height` of the underlying `MediaStreamTrack` are recorded and encoded into the resulting media file https://bugs.chromium.org/p/chromium/issues/detail?id=972470, https://bugs.chromium.org/p/chromium/issues/detail?id=983777. Chromium also has a bug where the `MediaRecorder` outputs a `Blob` with `size` set to `0` when the `MediaStream` is not set as `srcObject` of a `<video>` element https://bugs.chromium.org/p/chromium/issues/detail?id=952700, which could contribute to the issue of `MediaRecorder` not recording the correct `width` and `height`, as the pixel dimensions of the underlying encoded frames appear to be related to the `width` and `height` of the HTML `<video>` element where `srcObject` is set to the `MediaStream` to be recorded.

Chromium supports `avc1` and `h264` codecs at `MediaRecorder` which does record the correct `width` and `height` of the `MediaStreamTrack`, though the code necessary to achieve that requirement is not obvious, and would probably not be reached without a fair amount of testing multiple configurations of code not directly under the Media Streams and Capture specification

Steps to reproduce

1) Set mimeType of MediaRecorder to video/x-matroska;codecs=avc1 or video/x-matroska;codecs=h264; neither VP8 nor VP9 record correct width and height for all each replaced MediaStreamTrack
2) Attach canplay event to <video> element where the MediaStreamTrack of kind video is captured from
3) Within canplay event attach resize event to <video> element where MediaStream to be recorded is set as srcObject
4) Within resize event check if <video> element where the MediaStreamTrack of kind video is captured from width and height are equal to width and height values from MediaStreamTrack of kind video width and height
5) If width and height of <video> where the MediaStreamTrack of kind video is captured from width and height are equal to width and height values from MediaStreamTrack of kind video width and height attach unmute event to the original MediaStreamTrack, not the remote MediaStreamTrack after track event of RTCPeerConnection is dispatched
6) Await unmute event of initial MediaStreamTrack of kind video, approximately 30 seconds
7) When unmute event is dispatched to initial video MediaStreamTrack pass the MediaStream from track even of RTCPeerConnection to MediaRecorder, execute play() on <video> element that where the MediaStreamTrack will be replaced using RTCRtpSender.replaceTrack(), execute start() method of MediaRecorder

Code in pertinent part

```
      const videoStream = document.createElement("video");
      videoStream.onloadedmetadata = e => {
        const {
          videoWidth: width,
          videoHeight: height
        } = e.target;
        videoStream.width = video.width = width;
        videoStream.height = video.height = height;
      }
      const ms = videoStream.captureStream();
      ms.onaddtrack = async e => {
        console.log(e.track.getSettings());
        if (e.track.kind === "audio") {
          await audioSender.replaceTrack(e.track);
        } else {
          const {
            width, height
          } = e.track.getSettings();
          await videoSender.replaceTrack(e.track);
        }
      }
      for (const blobURL of urls) {
        await new Promise(resolve => {
          videoStream.addEventListener("pause", async _ => {
            await audioSender.replaceTrack(audioTrack);
            await videoSender.replaceTrack(videoTrack);
            resolve();
          }, {
            once: true
          });
          videoStream.addEventListener("canplay", async _ => {
            if (!recorder) {
              await new Promise(resizedPromise => {
                const handleResize = async _ => {
                  const {
                    width, height
                  } = ms.getVideoTracks()[0].getSettings();
                  console.log(video.width, width);
                  if (video.width === width && video.height === height) {
                    console.log(video.width, width);
                    video.removeEventListener("resize", handleResize);
                    await new Promise(unmutePromise => {
                      const [track] = mediaStream.getVideoTracks();
                      let now = performance.now();
                      console.log(video.currentTime);
                      track.addEventListener("unmute", async _ => {
                        console.log(_.type, (performance.now() - now) / 1000, video.currentTime);
                        unmutePromise(await videoStream.play());
                      }, {
                        once: true
                      })
                    });
                    recorder = new MediaRecorder(stream, {
                      mimeType: "video/x-matroska;codecs=h264"
                    });
                    recorder.onstart = _ => {
                      console.log(_.type);
                    }
                    result = new Promise(resolve => {
                      recorder.addEventListener("dataavailable", ({
                        data
                      }) => {
                        resolve(data);
                      }, {
                        once: true
                      })
                    });
                    recorder.start();
                    resizedPromise();
                  }
                }
                video.addEventListener("resize", handleResize);
              });
            } else {
              await videoStream.play();
            }
          }, {
            once: true
          });
          videoStream.src = blobURL;
        });
      }
      recorder.stop();
```

plnkr reproducing the issue https://plnkr.co/edit/Axkb8s.

The portion of the code where the developer would need to simply wait for an unknown output, if any, is **6)**, which is the topic of this issue.

Both of the `RTCPeerConnection` instances are "local". No server is involved. 

AFAICT `getStats()` does not provide a value for future events, in this case, `unmute`.

When attempting to record a possibly "infinite" `MediaStream` where the `MediaStreamTrack` of `kind` `"video"` potentially has variable pixel dimensions (`width` and `height`) due to the initial track being replaced using `RTCRtpSender.replaceTrack()` `unmute` event of the initial `MediaStreamTrack` (`CanvasCaptureMediaStreamTrack`) takes between 30 and 60 seconds for `unmute` event to be dispatched. Why?

Does a canonical procedure exist to estimate when `unmute` event attahced to a `MediaStreamTrack` will be dispatched?

**Comment by guest271314** [comment]
Just ran the code at the linked plnkr. `unmute` event took over 3 minutes to be dispatched according to `performance.now()` 

`188.17474499996752/60 // 3.1362457499994587`

Is `unmute` expected to take between 30 seconds and 3 minutes to be dispatched?

**Comment by alvestrand** [comment]
Why is this filed as a specification bug?
Is there anything that needs changing or clarifiication in the specification based on what you're writing?

If not - please refile as a Chrome bug. https://crbug.com/

**Comment by guest271314** [comment]
@alvestrand Am asking for clarification as to the mechanism which dispatches `unmute` event at a `MediaStreamTrack` of `kind` `"video"`. 

Why does the process take up to 3 minutes? 

Is that question considered an implementation detail? 

Is there a canonical procedure defined by the specification to estimate or determine the length of time that is required for `unmute` to be dispatched?

Without any guidance from the specification could have simply refreshed the tab without ever reaching `unmute` event being dispatched due to the length of time that it takes for the track to reach the `unmute` state. Though because the code is based on testing waited. If the code was deployment at large it would be helpful for the developer and users that are waiting on the `MediaStreamTrack` to reach `unmute` state to have some form of standardized timeline for the process. A user might wait 10 to 15 seconds for a procedure to potentially change state, though some users might not wait 3 minutes for `unmute` as there is no certainty that media will ever be unmuted. How would they technically know?

`chrome://webrtc-internals` does provide some statistics, though it is not clear how to extrapolate an estimation of when `unmute` will be dispatched.  



> The muted/unmuted state of a track reflects whether the source provides any media at this moment.

> Muted is out of control for the application, but can be observed by the application by reading the muted attribute and listening to the associated events mute and unmute. There can be several reasons for a MediaStreamTrack to be muted: the user pushing a physical mute button on the microphone, the user toggling a control in the operating system, the user clicking a mute button in the browser chrome, the User Agent (on behalf of the user) mutes, etc.

In this case frames are constantly being drawn onto a captured `canvas`. `replaceTrack()` replaces the canvas track with a track from a video capture. Therefore the expectation is that there should not be a span of 30 seconds to 3 minutes where either the canvas track or the video track are muted. Though that is the case. Am asking how to determine when the track will be unmuted given those criteria.

Not sure how the specification question as to `unmute` timing is a Chrome bug? 

Filed the issue because considered 30 to 60 seconds being a substantial amount of time to await `unmute` event when no server is involved.

If the inquiry, in your view, is not related to the specification, can simply close this issue, leaving the matter of how to determine how to estimate when a track is unmuted unanswered.

**Comment by guest271314** [comment]
@alvestrand Another way to ask the question is what steps can a developer takes, relevant to the specification language, in order to reduce the time it takes for `unmute` to dispatch?

Are there no measures a developer can take to decrease the time it takes for `unmute` to be dispatched? Could be 30 seconds, could be 3 minutes, could be 3 hours?

Is `mute`/`unmute` literally _completely_ out of the control of the developer WebRTC

> Muted is out of control for the application

meaning, users just have to wait for an indeterminate amount of time for `unmute` to be dispatched, even when they are providing video frames constantly and replacing a track with another live track?
