### ISSUE TITLE
enumerateDevices should only provide device info permission for granted device types

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-main#645]
The spec allows to expose devices through enumerateDevices after a successful getUserMedia call.
It makes sense to restrict it to either device or device type.
Per-device would be good to have but might depend on the actual browser implementation.

Per device type seems like the minimum bar.
In particular, if a user agent is asking "Allow access to camera", it does not make real sense to leak microphones.

**Comment by bradisbell** [comment]
I often work with several cameras and audio devices simultaneously.  In these scenarios, I don't think a per-device info grant makes sense, as that prohibits the application from showing a list of devices to the user to choose from.

We already have the problem of prompting the user what initial device they'd like to use.  While for many video conferencing style applications, leaving the default device is appropriate, more advanced use cases really do require this device information exposed to the application.  It's my understanding that the upcoming Permissions API will help with this, as we will be able to request what's needed up-front?

In either case, I think the suggestion of limiting to device type would be fine.

**Comment by youennf** [comment]
Issue specific to enumerateDevices. Might want to consider devicechange as a separate issue.

**Comment by jan-ivar** [comment]
[Consensus](https://www.w3.org/2020/10/20-webrtc-minutes.html#t04) is to [restrict devices by granted types](https://docs.google.com/presentation/d/1gxTvUTlJT9xUrb2uWIQaTuiA_rINwho80hXJ9_UWkNk/edit#slide=id.g9bb5e84ab8_0_60).
