### ISSUE TITLE
prohibit multiple getUserMedia() calls sharing the same capture device

### ISSUE THREAD

**Issue by ShijunS** [w3c/mediacapture-main#67]
The spec should explicitly prohibit multiple getUserMedia() calls sharing the same source/capture device.  If multiple objects from the same source are needed, apps must clone the MediaSteeam or MediaStreamTrack instead .

Section 4.3 of the current draft has the following - 
"Several MediaStreamTrack objects can represent the same media source, e.g., when the user chooses the same camera in the UI shown by two consecutive calls to getUserMedia()".

There is no algorithm defined explicitly on how to resolve conflict in constraints when sharing capture device with a consecutive getUserMedia() call.

**Comment by stefhak** [comment]
Adding the "list discussion needed" label. There is no text now prohibiting a page doing multiple gUM calls, and they could result in the same source being used. We must discuss if this is something we should prohibit.

**Comment by jan-ivar** [comment]
I think this request is invalid. Our model is that a user cannot reasonably know what source they're going to get given a set of constraints. Specifically, a user may specify different constraints and end up with the same source twice. Disallowing that would raise questions such as what to return in that case. A rats' nest.

What's the reasoning behind adding such a limitation? Given that track.applyConstraints pretty much exists to arbitrate multiple concurrent access, limiting concurrent access from the same tab seems arbitrary and counterproductive. It would complicate testing, some apps and even our model.

**Comment by ShijunS** [comment]
Since the gUM() call is async, having consecutive calls might lead to a racing condition.  It is fine to allow consecutive calls as long as the algorithm can be clearly defined.

**Comment by stefhak** [comment]
Shijun, do you mean the race condition if two consecutive gUM call are made, in the same app, targeting the same input device (they could even use deviceId as one constraint) with incompatible constraints? So one would fail.
Would not the natural thing be to resolve them in the order they are called (I'm assuming we're on a single thread)?

**Comment by ShijunS** [comment]
Yes, this can be an implementation decision.  It's fine for the user agent to resolve the gUM() calls in order.  It'd be nice to state that in the spec if that is the right expectation.

**Comment by jan-ivar** [comment]
There's no order determinism whatsoever. The UA (and ultimately the user) may arbitrarily reject or allow either or both or neither call, and do so in any order. Why is this a problem? Also, a spec cannot outlaw apps making calls, people will make calls. All it can do is mandate an implementation outcome. However, even if there's a problem here, I fail to understand the prescription: how will outlawing two compatible calls from succeeding have any effect on how two incompatible calls behave where both cannot obviously succeed, other than to make more of them by effectively making all subsequent calls into incompatible calls?

It is up to the UA how to resolve conflict in constraints when sharing capture devices, whether from different tabs or from consecutive getUserMedia() calls. I don't see a problem with that.

**Comment by adam-be** [comment]
Proposed patch (based on @alvestrand's comment):
https://github.com/w3c/mediacapture-main/commit/195153707024fc044c6238aebd69b4d692a04cd7
