### ISSUE TITLE
error message may require language/direction metadata

### ISSUE THREAD

**Issue by aphillips** [w3c/mediacapture-main#673]
_The I18N WG found [this issue](https://github.com/w3c/i18n-activity/issues/79) was never submitted in github (it was previously the topic of an email thread) during general housekeeping in our teleconference of 2020-03-26 and I was actioned with filing it._

Original thread: http://www.w3.org/Mail/flatten/index?subject=i18n-ISSUE-465&list=public-media-capture
Found originally in: http://www.w3.org/TR/2015/WD-mediacapture-streams-20150414/#widl-MediaStreamError-message

_Original comment:_
The 'message' value of MediaStreamError has no associate language or base direction information. Multiple 'message' values in different languages are not provided for. Since the message is generated by the user-agent, this may already be appropriately localized, but what about remote cases? And having the language and direction metadata may be useful when presenting the string in JS alerts or in an HTML context.

##

In examining the CR version of mediacapture-streams, I see that this section has been hugely edited and the original specific text is no longer applicable. However, I do see that section 7.2 "OverconstrainedError Object" still takes a `message` argument, which is a string. I expect that this message is intended to be human readable, i.e. a natural language string. It is a best practice to associate language and direction metadata with any natural language string and. It is also nice to provide a means of localizing messages into multiple languages where possible.

**Comment by dontcallmedom** [comment]
#746 has made it even clearer that `OverconstrainedError` is just an extension to `DOMException` which is where the localization of the `message` attribute would need to be addressed (i.e. in the WebIDL spec).
