### ISSUE TITLE
respec 25.4.2 upgrade: errors

### ISSUE THREAD

**Issue by aboba** [w3c/mediacapture-main#684]
The upgrade to respec in PR https://github.com/w3c/mediacapture-main/pull/677 has resulted in 39 errors.

See: https://w3c.github.io/mediacapture-main/

**Comment by dontcallmedom** [comment]
I can't see any errors - can you double check and/or give me a sense of what the listed errors are?

**Comment by aboba** [comment]
Everything looks fine now.
