### ISSUE TITLE
Only fire devicechange event when devices physically added/removed

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#688]
The primary use case for `devicechange` may potentially be undermined by https://github.com/w3c/mediacapture-main/pull/632.

**Primary use case:** Inserting a USB device or enabling a bluetooth headset (e.g. putting on AirPods) during a call, is a **strong signal** users want to switch to it, that many apps want, like a key press.

Unfortunately, with https://github.com/w3c/mediacapture-main/pull/632 Safari is firing `devicechange` immediately upon `getUserMedia` success, for all users with more than one camera and microphone, because the list technically changed.

Problem: as a web developer, I can no longer differentiate between:
 1. The user just inserted or enabled a headset, which I want to switch to immediately.
 2. The user did not insert or enable anything, and I _shouldn't_ switch to a secondary device.

Today, [devicechange](https://w3c.github.io/mediacapture-main/getusermedia.html#event-mediadevices-devicechange) says: *"The set of media devices, available to the User Agent, has changed."*

Note is says: _"available to the **User Agent**"_, not _"the application"_.

The latter would support firing the event whenever the JS-exposed list changes. The former not.

The spec requires there be a change in device availability _to the user agent itself_.

I read that to mean the `devicechange` event MUST NOT fire solely from user agent decisions.

Do we need to clarify the language around this to ensure web compat?

**Comment by jan-ivar** [comment]
Updated with the right link.

**Comment by youennf** [comment]
Thanks for the raising issue.

I am not aware of any compat issue with Safari current behavior.

This is done as you described in Safari to limit compat risks with other browsers that were not doing the filtering. It seems the right time now that the spec mandates the filtering to get consistency here.

Some web applications may buffer enumerateDevices result and only update it based on the device change event. Firing the event after the first successful getUserMedia call ensures that web applications do not stick with a filtered list of devices.

As of detecting whether there is a new device or not, this is easy to determine.
In the new device detection algorithm, if the previous list of devices is empty or devices have empty device ids, there is no new device.

As of whether the spec can mandate to not fire an event, I am not sure it actually can.
Before the first successful getUserMedia call, there is no need for the user agent to retrieve and store the full list of devices when enumerateDevices is called.

**Comment by guest271314** [comment]
`devicechange` is fired when setting a fake media stream at Chromium, without inserting a physical device to the machine. That is useful. The user is notified that the stream is Fake.

Should `devicechange` _not_ be fired for _code_ at the front-end or native applications that create one or more fake, mock, virtual devices; or even simply renames an existing "physical" device, perhaps applying custom attributes and functionality of the forked default-to-custom device?

**Comment by jan-ivar** [comment]
> As of detecting whether there is a new device or not, this is easy to determine.
In the new device detection algorithm, if the previous list of devices is empty or devices have empty device ids, there is no new device.

That seems incorrect for detecting insertion both _before_ & _during_ (shortly after) getUserMedia:
 1. **Before:** event fires ([works](https://jsfiddle.net/jib1/nj0w2sq1/) in Edge; Chrome, Safari & [Firefox](https://bugzil.la/1397977) are non-compliant)
 2. **During:** How can you know the device wasn't just inserted? (may have gone from 0 to 1 device)

The _"new devices detection"_ algorithm for most years of this spec has been a simple subtract:
```js
let old = await navigator.mediaDevices.enumerateDevices();
navigator.mediaDevices.ondevicechange = async () => {
  const devices = await navigator.mediaDevices.enumerateDevices();
  const newDevices = devices.filter(d => !old.find(o => o.deviceId == d.deviceId));
  old = devices;
};
```
Expecting web devs to do more than that seems ambitious. As I recall, the use-cases are:
 1. **Pre-gUM:** User inserts a device for which they had none before, qualifying them for feature.
 2. **Post-gUM:** User inserts a device (e.g. headset) preferred over the one they have now.

We should not break those IMHO. How do you propose we support those?

> Some web applications may buffer enumerateDevices result and only update it based on the device change event.

That would be a silly thing to do when _enumerateDevices_ already buffers (see [storedDeviceList](https://w3c.github.io/mediacapture-main/getusermedia.html#ref-for-dfn-storeddevicelist-3)). 

But it does point to a spec problem: The list is [not allowed to be updated](https://w3c.github.io/mediacapture-main/getusermedia.html#ref-for-dfn-storeddevicelist-1) without an event.

So we broke something when we went:
 1. from a simpler world where the list only changed when devices were inserted/pulled, and the event signified both
 2. to a world where the event can no longer mean both. 

It's now unclear what the event means. It's lost it's meaning.

**Comment by jan-ivar** [comment]
**Proposal A:**
* Allow the list to change without event.
* Only fire `devicechange` on insertion/removal by user.

**Proposal B:**
* Fire `devicechange` on any list change.
* Fire a new `newdevice` event if change was due to a device being inserted by user.

**Comment by youennf** [comment]
> Expecting web devs to do more than that seems ambitious.

I think there will be some adoption needed whatever proposal we come up with.

I know some websites that identify insertion of devices and seem to work fine in Safari.
I haven't looked what is done for that purpose.
Maybe the algorithm you quoted is being used with two fixes:
- Also include a device.kind check to at least fix pre-gum case
- Call the same snippet at getUserMedia resolution time / reinitialise 'old' with all information (including deviceIds, labels and capabilities)

> That would be a silly thing to do when _enumerateDevices_ already buffers (see [storedDeviceList](https://w3c.github.io/mediacapture-main/getusermedia.html#ref-for-dfn-storeddevicelist-3)).

The web app needs to buffer the list of devices to detect new devices, the only question is whether the web app will use this list for other purposes. I do not see why that would be silly to do.

Let's say we implement either of these proposals.
The above code snippet would still break in some cases:
- User has a builtin camera and a USB camera
- User grants getUserMedia access and uses the builtin camera
- User removes the USB camera as it is not used
- A devicechange event fires, web app is falsely made aware of a new device, the built-in camera given it has now a non empty deviceId.

That does not mean Safari behavior cannot change. Reducing the number of events to fire is a good thing in general. It seems a good plan for browsers that have not yet shipped the filtering to try not firing the event at first getUserMedia resolution.

**Comment by jan-ivar** [comment]
> A devicechange event fires, web app is falsely made aware of a new device, the built-in camera given it has now a non empty deviceId.

Sigh, that's another thing we broke by removing deviceIds pre-gUM.

Then I see no way around apps being cognizant of the fact that they'll need to call enumerateDevices() again on gUM success to update their cached list, if they're going to do device detection properly.

The remaining question is whether it makes sense to fire the `devicechange` event then.

Doing so would seem to trigger their detection code, which we just deduced will produce false positives.

**Comment by jan-ivar** [comment]
I think we also need to solve this race: user inserts a device while getUserMedia is happening. We should make sure apps can distinguish that.

**Comment by guest271314** [comment]
@jan-ivar Is `devicechange` intentionally not applicable to programmatic changes to devices, thus not covered by this issue?

**Comment by jan-ivar** [comment]
@guest271314 What's the use case for a page responding dynamically to programmatic changes? 

From today's meeting, the plan is a PR for **proposal A**, but written to make an exception for getUserMedia success instead of defining or relying on "user action".

Additionally, limit firing of the event pre-permission to transitions to/from 0 devices of a kind.

As such, I would expect programmatic additions/removals to continue to count.

**Comment by guest271314** [comment]
> @guest271314 What's the use case for a page responding dynamically to programmatic changes?

Some are listed at https://github.com/w3c/mediacapture-main/issues/688#issuecomment-619603541.

> As such, I would expect programmatic additions/removals to continue to count.

Ok. 

Not sure how the `getUserMedia()` or any application would be able to tell the difference from a physical jack being connected and a programmatic device being connected?

**Comment by jan-ivar** [comment]
It wouldn't, but that seems appropriate.

**Comment by youennf** [comment]
> Additionally, limit firing of the event pre-permission to transitions to/from 0 devices of a kind.

Filed a specific issue at https://github.com/w3c/mediacapture-main/issues/690

**Comment by guest271314** [comment]
Then such language should be included in any relevant PR so that implementers and user at the front-end understand that there is no difference from "physically" inserting a cable to the device, blueooth pairing, or creating and deploying a virtual, mock, or fake device, e.g.,

"For the purposes of `devicechange` event being fired there is no difference between a programmatically created device and a phyical cable being connected to a device."

**Comment by guest271314** [comment]
The title of the issue and 

> - Only fire devicechange on insertion/removal by user.

infers that somehow a human must "insert" a cable to a machine "physically" for `devicechange` to be fired. A hamster or robot could be trained to perform "insertion" of a cable to a machine. No insertion of a cable is necessary for a new device to be brought online at the machine. The term insertion involves the case of the human, animal or robot inserting a cable. Those are not the only cases where a camera or microphone device can be created or deployed at the machine. 

The term "insertion" is not observable.
