### ISSUE TITLE
enumerateDevices() should print correct MediaDeviceInfo

### ISSUE THREAD

**Issue by guest271314** [w3c/mediacapture-main#693]
When `getUserMedia({audio:true})` is executed at Chromium it is possible to change the device at native audio control application during recording from "device" to "Monitor of device". That setting remains for any subsequent calls to `getUserMedia()`, which is the expected result for the workaround no support for "Monitor of device" at UI prompt at Chromium. However, the device label does not reflect the captured device when `enumerateDevices()` is executed after permission is granted. The device being captured is "Monitor of device" set manually, not "device" at that point. `enumerateDevices()` should be dynamic, and always print the correct device, not the name or label of the device that might have been initially selected at prompt, even if the implementation does not directly support capturing that named device.

**Comment by youennf** [comment]
The spec is a bit vague in how dynamic changes of device characteristics can be exposed to a web page. This could for instance be mimicked by a quick 'remove/add device' emulation.
I am sympathetic to the idea of allowing a page to know a device characteristics have changed.
On the other hand, with regards to labels, we want to get rid off them as much as possible so I do not think we want the spec to prescribe anything for label.

It would be interesting to know what Firefox is doing since they are using labels both for their prompt as well as expose the labels to the page.

**Comment by guest271314** [comment]
@youennf Firefox provides a means to select the "Monitor of device" at the UI prompt. The text of the label is not paramount. The ability to select the required device and verify that selection is what am describing. Although Chromium does not officially support selection of "Monitor of device" it is nonetheless still possible with an unofficial workaround to select a device not listed in browser UI prompt and for that selection to remain persistent across sessions; once the device is selected at PulseAudio sound settings GUI subsequent calls to `getUserMedia()` use that selection. 

Chromium does not provide a means to select "Monitor of device" at UI prompt. In spite of that fact and that this specification has declined to clearly specify capturing "Monitor of a device" a device other than "Default" _can_ be selected. This lack of coverage leads to Chromium printing the incorrect device for all subsequent call to `enumerateDevices()` once a user changes the device natively and does not change the device back to "Default" or "Built-in" audio device later.

Certainly do not want the workaround for Chromium sealed off, that is the only way have been able to record audio output using `getUserMedia()`. Would have to find another workaround.

It would perhaps make sense, as have suggested in several previous issues, to specify what is technically possible, recognize that `getUserMedia()` _can_ be used to capture audio output, or precisely, "Monitor" ("What U Hear") of a device, and then Chromium could just list the device at the UI prompt, to avoid the potential for listing the incorrect device for the duration.

**Comment by guest271314** [comment]
> On the other hand, with regards to labels, we want to get rid off them as much as possible so I do not think we want the spec to prescribe anything for label.

Another way to look at the issue is: How to verify which device is is being captured?

If screenshots can help illustrate what is occurring with Chromium printing a list a devices that does not include the device being captured, can post those here so that you can see for yourself what happens.

**Comment by guest271314** [comment]
Video illustrating selecting a different device than selected at UI prompt and result of `enumerateDevices()` _after_ that subsequent selection. 

It should be possible to simply select "Monitor of device" at UI prompt for all implementations, instead of creating and using workarounds.

`enumerateDevices()` is listing "Built-in Audio Analog Stereo" however in this case no matter how loud the input to microphone is, microphone input _will not be_ and _is not_ captured, "What-U-Hear" https://wiki.archlinux.org/index.php/PulseAudio/Examples will be captured, which is the intended result of the workaround, `enumerateDevices()` is not listing all devices, and the initial selection is not being captured at that point.

[builtin_to_monitor_enumerate_devices.webm.zip](https://github.com/w3c/mediacapture-main/files/4575098/builtin_to_monitor_enumerate_devices.webm.zip)
```
[
  {
    "deviceId": "default",
    "kind": "audioinput",
    "label": "Default",
    "groupId": "6fe6f271fba7a948a3b8220c738015030bdb472c974cdea5988b5983baf1884e"
  },
  {
    "deviceId": "789cb9a31a628682abb878989a01bba1b566b2df9946c396dce74bc288c9b110",
    "kind": "audioinput",
    "label": "Built-in Audio Analog Stereo",
    "groupId": "406f767177516481725c53a4c7abfbefd23a01a66af61c1f3ee1dd2e197fb902"
  },
  {
    "deviceId": "",
    "kind": "videoinput",
    "label": "",
    "groupId": "31f9ad250b1102a12cac822980473eba017158bfbc76bd3639d05769b3f31e3e"
  },
  {
    "deviceId": "default",
    "kind": "audiooutput",
    "label": "Default",
    "groupId": "default"
  },
  {
    "deviceId": "667f58d66146ddca9a33b986df5793fe52c0417b86912e177ba02200c318e9d6",
    "kind": "audiooutput",
    "label": "Built-in Audio Analog Stereo",
    "groupId": "406f767177516481725c53a4c7abfbefd23a01a66af61c1f3ee1dd2e197fb902"
  }
]
```

**Comment by guest271314** [comment]
Note that `devicechange` is not fired in this case, where the device being captured is changed at OS native application.

**Comment by guest271314** [comment]
@youennf Incorporated a means to launch `pavucontrol -t 2` (Recording tab) when `getUserMedia()` is executed into https://github.com/guest271314/captureSystemAudio in order to resemble the selection option of Firefox for the ability of the user to "seamlessly" toggle the device being captured during the capture ![Screenshot_2020-06-12_13-54-55](https://user-images.githubusercontent.com/4174848/84510203-59dd7d80-acb4-11ea-8626-2864d36446ba.png)

chromiumGetUserMediaSelectAudioDevice.js

```
async function chromiumLinuxSetAudioCaptureDevice() {
  try {
    const requestNativeScript = new Map();
    const mediaStream = await navigator.mediaDevices.getUserMedia({audio: true});
    requestNativeScript.set(
      'wait',
      (ms = 50) => new Promise(resolve => setTimeout(resolve, ms))
    );
    requestNativeScript.set(
      'dir',
      await self.chooseFileSystemEntries({ type: 'open-directory' })
    );
    requestNativeScript.set(
      'status',
      await requestNativeScript.get('dir').requestPermission({ writable: true })
    );
    // inotifywait does not fire events for getFile(), or file with no content, add space character to text file
    // FileSystemFileHandle.getFile() does not open file https://bugs.chromium.org/p/chromium/issues/detail?id=1084840
    requestNativeScript.set(
      'start',
      await (
        await requestNativeScript
          .get('dir')
          .getFile('openpavucontrol.txt', { create: false })
      ).getFile()
    );
    requestNativeScript.set(
      'stop',
      await (
        await requestNativeScript
          .get('dir')
          .getFile('closepavucontrol.txt', { create: false })
      ).getFile()
    );
    // Execute File.arrayBuffer() to read file for inotifywait to fire access or open event
    // alternatively <input type="file">.click() does fire inotifywait open event
    
    const executeNativeScript = await requestNativeScript
      .get('start')
      .arrayBuffer();
    return {requestNativeScript, mediaStream};
  } catch (e) {
    throw e;
  }
}
chromiumLinuxSetAudioCaptureDevice()
.then(({
  requestNativeScript, mediaStream
}) => {
  console.log(mediaStream, requestNativeScript);
});
```

notify.sh

```
openPavuControl() {
  inotifywait -m -e open $HOME/localscripts/openpavucontrol.txt | while read file; 
  do 
    echo "$file" | grep "openpavucontrol.txt OPEN" && $HOME/localscripts/openpavucontrol.sh
  done
}
closePavuControl() {
  inotifywait -m -e open $HOME/localscripts/closepavucontrol.txt | while read file;
  do 
    echo "$file" | grep "closepavucontrol.txt OPEN" && $HOME/localscripts/closepavucontrol.sh
  done
}
openPavuControl & closePavuControl
```

chromiumGetUserMediaSelectAudioDevice.sh

```
#!/bin/bash
chromiumLinuxGetUserMediaSelectAudioDevice() {
  pavucontrol -t 2
}
chromiumLinuxGetUserMediaSelectAudioDevice
```

closepavucontrol.sh
```

#!/bin/bash
killall -9 pavucontrol
```

Since neither `getUserMedia()` nor `getDisplayMedia()` specifications unambiguously detail the procedure for capturing system audio what would be the correct way to proceed creating a specification to do precisely that: capture system audio?

**Comment by guest271314** [comment]
Chromium issue https://bugs.chromium.org/p/chromium/issues/detail?id=1114422

**Comment by youennf** [comment]
Closing in favour of a reduced scope issue: https://github.com/w3c/mediacapture-main/issues/730
