### ISSUE TITLE
GetDisplayMedia don't capture the audio from microphone

### ISSUE THREAD

**Issue by athina635** [w3c/mediacapture-main#694]
Hello, I already read a lot of comments here about this topic but I really got more confused about that and how to use this.

I already use the getDisplayMedia() to share my screen and that worked as well but I just capture the audio from the system like audio from youtube ..etc but I couldn't capture the audio from the microphone.

any clear answer about that?
any suggestions on how to capture the microphone sound?

thank you.

**Comment by guest271314** [comment]
> but I just capture the audio from the system like audio from youtube ..etc 

Do you mean `getDisplayMedia()` _does_ capture audio, only in certain cases?

> but I couldn't capture the audio from the microphone.
You should be able to capture audio with `getUserMedia()`, add the corresponding track to the other `MediaStream`, if necessary add the tracks to a new `MediaStream`.

**Comment by athina635** [comment]
> Do you mean getDisplayMedia() does capture audio, only in certain cases? Or, getDisplayMedia() does not capture audio at all? 

no, but fetDisplayMedia() can capture all audio from the system and not from the microphone.

**Comment by guest271314** [comment]
> No, but getDisplayMedia() can capture all audio from the system and not from the microphone.

Can you kindly cite the primary source which lead you reach that conclusion? 

> I will test what you suggested to me.

> can I play around the audio and the video? I mean when I would stop the video and let the audio play or the opposite?

Yes, that  is the purpose of defining `audioTrack` and `videoTrack` at the first line of the code, see comment.

**Comment by athina635** [comment]
that is my code as you suggest i just modify a little bit on it!

i arrived to share the video but not the audio! am I right?

```
let audioTrack, videoTrack, stream;

            navigator.mediaDevices.getDisplayMedia({
                    video: true
                })
                .then(displayStream => {


                    videoTrack = displayStream.getVideoTracks();

                    navigator.mediaDevices.getUserMedia({
                        audio: true
                    }).then((audioStream) => {
                        audioTrack = audioStream.getAudioTracks();
                        stream = new MediaStream(videoTrack, audioTrack);

                        mediaStreamObj = stream;
                        video.srcObject = stream;
                        video.play();
                        video.volume = 0;
```

**Comment by guest271314** [comment]
> am I right for what I did?

Not sure, it is your requirement.

> what I notice is the audio in somehow in slow motion mode just a little bit.

This is probably not the best venue for that issue. That is probably not all of the code, correct? Both Firefox and Chromium have issues with audio or video synchronization when `MediaSource` is used with `MediaStream` (in brief see https://github.com/guest271314/MediaFragmentRecorder/issues/8#issuecomment-520309183, https://gist.github.com/guest271314/c38042935db4e0131c1e0b68ca59f4ac#gistcomment-3241753). If you start a gist will try to help there.

**Comment by guest271314** [comment]
@athina635 

> No, but getDisplayMedia() can capture all audio from the system and not from the microphone.

What document precisely gave you that impression?

**Comment by athina635** [comment]
@guest271314 

> What document precisely gave you that impression?

when I use that getDisplayMedia() in Chrome and select the option of sharing audio when a pop up appears to ask you which screen do you want to capture (Tab screen, fullscreen...etc). with that, I could display the audio for the other peer (the system audio and not the microphone).

**Comment by guest271314** [comment]
Which OS? AFAICT `getDisplayMedia()` does not include an audio track for any case at *nix.

**Comment by athina635** [comment]
> Which OS? 

on windows chrome navigator with `audio: true` i could capture the audio of the system like i mean when i launch something on the PC i could stream that sound

**Comment by guest271314** [comment]
Is this issue resolved?

**Comment by athina635** [comment]
i resolved the issue by tracking the audio alone and the video alone too like that i could capture the audio from the microphone and that what i want. but now if i want to stop the video track in any moment how can i do that?

PS: I'm using this code:

```
[videoTrack] = displayStream.getVideoTracks();

                    navigator.mediaDevices.getUserMedia({
                        audio: true
                    }).then((audioStream) => {
                        [audioTrack] = audioStream.getAudioTracks();
                        stream = new MediaStream([videoTrack, audioTrack]);
```

**Comment by jan-ivar** [comment]
Hi @athina635 this place is for reporting issues with the spec. For user problems, please post a question on sites like https://stackoverflow.com/questions/tagged/webrtc instead. Thanks!

**Comment by jigarshah13** [comment]
@athina635 Can you please tell me how have your recorded audio and video both using getDisplayMedia()?

I am able to record only video after selecting chrome tab where video is playing but audio from that video is not being recorded.

Can you give your code or any hint to record both audio and video from selected screen?

**Comment by andersoonluan** [comment]
> > but I just capture the audio from the system like audio from youtube ..etc
> 
> Do you mean `getDisplayMedia()` _does_ capture audio, only in certain cases? Or, `getDisplayMedia()` _does not_ capture audio at all?
> 
> > but I couldn't capture the audio from the microphone.
> 
> You should be able to capture audio with `getUserMedia()`, add the corresponding track to the other `MediaStream`, if necessary add the tracks to a new `MediaStream`.
> 
> ```
> let audioTrack, videoTrack, stream; // define initial variable here for ability to call stop() on each track
> navigator.mediaDevices.getDisplayMedia({video: true})
> .then(async displayStream => {
>     [videoTrack] = displayStream.getVideoTracks();
>     const audioStream = await navigator.mediaDevices.getUserMedia({audio: true}).catch(e => {throw e});
>     [audioTrack] = audioStream.getAudioTracks();
>     // displayStream.addTrack(audioTrack); // do stuff
>     // or 
>     // stream = new MediaStream([videoTrack, audioTrack]); // do stuff
> })
> .catch(console.error);
> ```

It really helped me, thank you very much!

**Comment by AntonioMing** [comment]
> i resolved the issue by tracking the audio alone and the video alone too like that i could capture the audio from the microphone and that what i want. but now if i want to stop the video track in any moment how can i do that?
> 
> PS: I'm using this code:
> 
> ```
> [videoTrack] = displayStream.getVideoTracks();
> 
>                     navigator.mediaDevices.getUserMedia({
>                         audio: true
>                     }).then((audioStream) => {
>                         [audioTrack] = audioStream.getAudioTracks();
>                         stream = new MediaStream([videoTrack, audioTrack]);
> ```

====
Hi， When the two sides communicate, the system’s playing voice will be mixed with the remote speaker’s voice at the same time. 
How to eliminate the remote speaker’s voice in the system’s playing voice in order to Let the remote speaker do not hear his own voice.

**Comment by kfes50509** [comment]
Modify
>     // displayStream.addTrack(audioTrack); // do stuff
To
`displayStream.addTrack(audioTrack[0])`

**Comment by kfes50509** [comment]
try it

**Comment by kfes50509** [comment]
try it!
`navigator.mediaDevices.getDisplayMedia({ video: true })
      .then(async (videoStream) => {
        const audioStream = await navigator.mediaDevices.getUserMedia({ audio: true, video: false }).catch((e) => { throw e; });
        const audioTrack = audioStream.getAudioTracks();
        videoStream.addTrack(audioTrack[0]);
      })
      .catch((e) => {
        console.log(e);
        this.startScreenRecording();
      });`

**Comment by MaciejWebWolf** [comment]
You can always set a microphone as a speakers output:

Go to [Control Panel] > [Hardware and Sound] > [Sound].
Find [Recording] tab > select [Microphone] > click [Properties] to access to the detail setting.
Click [Listen] tab and check [Listen to this device].
Tap [OK] or [Apply] to activate.

remember to check "share audio from computer"  when a pop up appears
