### ISSUE TITLE
Export "constrainable object"

### ISSUE THREAD

**Issue by hober** [w3c/mediacapture-main#695]
I tried to use [this term](https://w3c.github.io/mediacapture-main/getusermedia.html#dfn-constrainable-object) in Bikeshed by typing `[=constrainable object=]`, but it turns out it's not exported.

**Comment by jan-ivar** [comment]
May I ask what you're referencing it for, so I can dissuade you from using it? 😉

**Comment by hober** [comment]
> May I ask what you're referencing it for,

w3ctag/design-principles#152

> so I can dissuade you from using it? 😉

Please, tell me more.

**Comment by jan-ivar** [comment]
Oh carry on then. I thought was for a new API.

> Please, tell me more.

I think in it has some baggage (doesn't define defaults, legacy `advanced` keyword, the mentioned [privacy issue](https://github.com/w3ctag/design-principles/issues/152#issuecomment-577914533)), and in hindsight was over-designed for how most browsers ended up implementing it (as a generic software downscaler more than a discovery API, which ironically is better for privacy).

I have low confidence the pattern generalizes well outside of MediaStreamTrack.

**Comment by hober** [comment]
> > Please, tell me more.
> 
> I think in it has some baggage (doesn't define defaults, legacy `advanced` keyword, the mentioned [privacy issue](https://github.com/w3ctag/design-principles/issues/152#issuecomment-577914533)), and in hindsight was over-designed for how most browsers ended up implementing it (as a generic software downscaler more than a discovery API, which ironically is better for privacy).
> 
> I have low confidence the pattern generalizes well outside of MediaStreamTrack.

Thanks, this is really helpful to know.

I ended up not needing to reference the term in w3ctag/design-principles#180, so I'll close this issue. Thanks again!
