### ISSUE TITLE
Do we need MediaStreamError.constraintName?

### ISSUE THREAD

**Issue by ShijunS** [w3c/mediacapture-main#71]
If we remove “constraintName”, the MediaStreamError will be consistent with DOMError.

UA can potentially use the "message" property to deliver the constraintName or constraintNames to the apps and developers.  

This is a compromise the EME spec has taken recently for a similar problem in that spec.

**Comment by dontcallmedom** [comment]
The purpose of exposing specifically constraintName is a machine readable property was to allow developers to react to an overconstrained event by e.g. relaxing the said constraint in a new call.

**Comment by stefhak** [comment]
I think that what Dom says is where the group is regarding this topic. ShijunS, re-open if you think we need to revisit.
