### ISSUE TITLE
Is onended event only applicable to a MediaStreamTrack from getUserMedia()?

### ISSUE THREAD

**Issue by guest271314** [w3c/mediacapture-main#710]
Consider navigating to https://upload.wikimedia.org/wikipedia/commons/a/a4/Xacti-AC8EX-Sample_video-001.ogv to avoid cross-origin request and running this code

```
      var video = document.createElement('video');
      video.autoplay = true;
      video.onplay = e => {
        const ms = video.captureStream();
        const [audioTrack] = ms.getAudioTracks();
        console.log(audioTrack);
        audioTrack.onended = e => console.log(e);
        audioTrack.stop();
        console.log(audioTrack.ended);
      }
      video.src = 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Xacti-AC8EX-Sample_video-001.ogv';
```

and also running this code 

```
    var ac = new AudioContext();
    var msd = new MediaStreamAudioDestinationNode(ac);
    var {stream} = msd;
    var [audioTrack] = stream.getAudioTracks();
    audioTrack.onended = e => console.log(e);
    audioTracl.stop();
    console.log(audioTrack.ended);
```

[`onended` ](https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-onended) is never fired.

Is onended event only applicable to a `MediaStreamTrack` from `getUserMedia()`?

**Comment by guidou** [comment]
onended should not fire because of a call to stop()

**Comment by guest271314** [comment]
Under what conditions should `onended` fire?

**Comment by guest271314** [comment]
In the cases above Chromium does fire `oninactive` event. Nightly 81 freezes when running the code that requests and plays the `.ogv` file.

**Comment by guidou** [comment]
onended should fire when the track stops for any reason other than the stop() method. See https://w3c.github.io/mediacapture-main/#life-cycle-and-media-flow

onactive/oninactive are nonstandard and should be removed from Chromium. See https://crbug.com/649328
