### ISSUE TITLE
What happens for live tracks in case permission is revoked

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-main#711]
Spec seems to indicate that if permission is revoked, corresponding tracks get ended.
> When a MediaStreamTrack object ends for any reason (e.g., because the user rescinds the permission for the page to use the local camera...

There is no MUST statement though.
In the case permission API exposes a change of the policy (from grant to deny) to the page, the tracks should probably get ended (or muted maybe) for consistency with the policy change.

**Comment by riju** [comment]
I noticed a [Chromium CL](https://chromium-review.googlesource.com/c/chromium/src/+/2352790) to stop media streams if users revokes consent. cc @guidou

**Comment by youennf** [comment]
Will draft a PR accordingly.

**Comment by youennf** [comment]
https://w3c.github.io/permissions/#ref-for-permission-revocation-algorithm① explicitly says that tracks should be stopped.
I do not think we need to say anything in mediacapture-main.
Permissions API spec should ideally add a link to the exact algorithm (https://w3c.github.io/mediacapture-main/#ends-nostop).
It is unclear to me which of MediaStreamTrack ended event or permission change event is supposed to be fired first.

**Comment by youennf** [comment]
Filed https://github.com/w3c/permissions/issues/223.
Closing the issue.
