### ISSUE TITLE
[Feature] registerStream(deviceId = '0', stream = MediaStream)

### ISSUE THREAD

**Issue by guest271314** [w3c/mediacapture-main#712]
Created a workaround for https://bugs.chromium.org/p/chromium/issues/detail?id=931749 and https://bugs.chromium.org/p/chromium/issues/detail?id=1013881 to capture system audio output at Chromium. 

The issue now is that in order to achieve the workaround am using localhost where CORS, COOP, COEP are factors.

Am not sure precisely how to use signaling for WebRTC to access the `MediaStream` at any origin.

One solution would be a function that registers a `MediaStream` to be listed in `enumerateDevices()` then the user can select by `deviceId` at any origin.

At localhost

`await registerStream('0', mediaStream)` // registered

At any origin

`await navigator.mediaDevices.getUserMedia({audio: {deviceId: {exact: '0'}}})` // registered stream

**Comment by jan-ivar** [comment]
This seems out of scope for mediacapture-main, given the type of problem it appears to be trying to solve. Taking any kind of MediaStream and draping it in the camera and microphone-specific `getUserMedia` API seems unnecessary.

I'd suggest creating a peer connection to transfer the tracks locally to a different origin. Closing.

**Comment by guest271314** [comment]
@jan-ivar To that end when you find the time can a minimal, complete, verifiable example of the required signaling exchange between remote peers be included at WebRTC repository?

`WebAssembly.Memory` and `TypedArray` and `SharedArraytBuffer` have limitations. Not certain how to get a `MediaStreamTrack` from raw PCM without using `AudioWorklet` and `MediaSTreamAudioDestinationNode`, where the pattern am using to do so requires some form of linear memory. 

Am able to get access to the output of a media device. How to connect that raw PCM directly to WebRTC to get a `MediaStreamTrack`?

Tried to incorporate your data channel example into WebRTC, both using `addStream()` and transceivers, though the first attempts yielded only a silent track https://github.com/w3c/webrtc-pc/issues/2564#issuecomment-678641430.

**Comment by guest271314** [comment]
@jan-ivar 

> I'd suggest creating a peer connection to transfer the tracks locally to a different origin.

That was on the list of TODO: workarounds.

https://gist.github.com/guest271314/04a539c00926e15905b86d05138c113c
