### ISSUE TITLE
MediaStreamTrack object can also be consumed directly

### ISSUE THREAD

**Issue by ShijunS** [w3c/mediacapture-main#72]
MediaStreamTrack object can be consumed directly, for example, by the ORTC RTCRtpSender object.  With the object model being introduced into WebRTC 1.0, there will give us another example for this.

[Section 4.1] has the following, "Both MediaStream and MediaStreamTrack objects can be cloned. This allows for greater control since the separate instances can be manipulated and consumed individually".

We should add MediaStreamTrack explicitly, so this becomes, “…the separate instances **of MediaStream and MediaStreamTrack** can be…”

**Comment by stefhak** [comment]
I agree to your assessment Dom. Closing this issue.
