### ISSUE TITLE
Mandate implementations to support video frame subsampling

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-main#723]
It would be nice to get interoperability for width and height constraints amongst browsers.
We should be able to get consistent behavior for such simple example as:
const stream = await navigator.mediaDevices.getUserMedia({ video : true });
await stream.getVideoTracks()[0].applyConstraints({ width : 160, height : 160 });
// or await stream.getVideoTracks()[0].applyConstraints({ width : { exact : 160 }, height : { exact : 160 });

Currently, some browsers will not produce a 160x160

**Comment by youennf** [comment]
The same question could be asked for frame rate as well.
If 30fps is natively supported, but 5fps is not by the camera, the User-Agent can reasonably implement frame rate adjustment  instead of throwing an OverConstrained error.

**Comment by youennf** [comment]
The general issue is for numerical constraints for which a range [min, max] is provided as part of getCapabilities but some values between min and max are not allowed. It seems the spec should ask implementations to do a best effort to support the whole [min, max ] range.

**Comment by henbos** [comment]
Is this an issue of not specifying a default value for crop and scale?

**Comment by alvestrand** [comment]
The incompatibility between Chrome and Firefox modes led to the introduction of https://w3c.github.io/mediacapture-main/getusermedia.html#def-constraint-resizeMode - the spec has no default for this value, which allows the two browsers to behave differently, but the user can ask about which mode is in use and can influence the choice (if both modes are supported).

**Comment by alvestrand** [comment]
note - frame rate adaption can be rather expensive when it's not an integral frame-drop; for instance, adapting from 30 to 29.97 would require pretty massive interpolation operations.

**Comment by youennf** [comment]
> frame rate adaption can be rather expensive when it's not an integral frame-drop

Agreed, the idea would be to go with something simple enough like integral frame-drop, which is what Safari does (maybe Chrome as well?).
Also, even though the setting is 30fps, actual measurements might show that the real fps might be different though hopefully not too far. Idea here is to target good enough interoperability.

> the spec has no default for this value,

This seems like a common enough interop issue.
Is there a way we could agree on an interoperable solution here?
Can the spec mandate supporting both resizeMode values?

**Comment by bradisbell** [comment]
> It seems the spec should ask implementations to do a best effort to support the whole [min, max ] range.

I feel that it would be much better if the specific resolutions or ranges supported were provided.  As a web developer, I have to make a great deal of effort now to try to get the most raw original form of what is captured.  I don't want the user agent resizing, resampling, or doing anything to the video.

> If 30fps is natively supported, but 5fps is not by the camera, the User-Agent can reasonably implement frame rate adjustment instead of throwing an OverConstrained error.

I think having an OverConstrained error is much better.  Again, any sort of media processing happening transparently is harmful.  We want the cleanest form of whatever the video is, as close to the original as we can get it.

Of course, I have no objection to opting in to some sort of dynamic resize or frame interpolation, but I don't think it should be automatic.  Minimally, there needs to be a way to opt out.

**Comment by youennf** [comment]
> Minimally, there needs to be a way to opt out.

resizeMode is probably what you want as opt out, or opt in.
Would you like the same for frame rate and if so what gain do you expect?
How do you handle this in current browsers supporting frame rate decimation?

> I have no objection to opting in to some sort of dynamic resize or frame interpolation

For frame rate, we are not really talking about frame interpolation, more something like frame skipping.
So you still get the exact output of the camera, except only part of it.

> I think having an OverConstrained error is much better.

getCapabilities does not tell what the native frame rate values are at the given resolution (since different native resolutions may lead to different native frame rates).
I am not sure OverConstrained error is the best way to surface that information if it proves to be useful.
OS APIs provide this information in a more straightforward manner.

**Comment by guest271314** [comment]
> (since different native resolutions may lead to different native frame rates).

Different pixel dimensions do require different frame rates. Greater pixel dimensions requires less frames per second than lesser pixel dimensions. That fact becomes immediately obvious when creating a video containing variable with and height frames, frame by frame. In that case a constant frame rate is not the goal, to avoid greater pixel dimension frames (less total frames required per second) to appear on screen rendered as fast as lesser pixel dimension frames (more total frames required per second), for example, see `console` at https://plnkr.co/edit/4Tb91b?preview note the different between the number of frames comparing index 0 and index 1, each set of frames being similar duration

`[Array(40), Array(194), Array(67), Array(102), Array(34), Array(32), Array(40)]`

using

```
const frames = await (await fetch(url)).json();
    console.log(frames);

    const rs = new ReadableStream({
      async pull(controller) {
        for (const frame of frames) {
          const [{
            duration, frameRate, width, height
          }] = frame;
          const framesLength = frame.length - 1;
          const frameDuration = Math.ceil((duration * 1000) / framesLength);
          for (let i = 1; i < framesLength; i++) {
            const response = await (await fetch(frame[i])).arrayBuffer();
            controller.enqueue({
              response, frameDuration
            });
          }
        }
        controller.close();
      }
    });

    const reader = rs.getReader();
    const processStream = async({
      value, done
    }) => {
      if (done) {
        await reader.closed;
        return "stream done";
      }
      const {
        response, frameDuration
      } = value;
      channel.postMessage({
        response
      }, [response]);
      await new Promise(resolve => setTimeout(resolve, frameDuration));
      return processStream(await reader.read());
    }
    const done = await processStream(await reader.read());
    postMessage(done);
  } catch (e) {
    console.error(e);
  }
```

which can also be done dynamically, frame by frame 

```
const
  flushFrame = (video) => {
    let
      now = video.currentTime;

    if (frameStartTime) {
      WebmWriter.addVideoFrame(
        canvas.toDataURL("image/webp").split(",").pop()
      , (now - frameStartTime) * 1000
      );
    }

    frameStartTime = now;
  };
  // ...
  frameStartTime = 0;
  const captureFrame = () => {
    captureTimer = null;
    flushFrame(video);
    ctx.drawImage(video, 0, 0);
    captureTimer = setTimeout(captureFrame, 1000 / inputSampleRate);
  };
  captureFrame();
```

https://plnkr.co/edit/ThXd9MKYvEYq2kKyh8oc?p=preview&preview

If variable width and height frames are not expected that setting a constant value for `width` and `height` is a possible viable feature, else would suggest testing the outcome of, for example setting `width` and `height` to `100`, respectively, where the input frame is `680` by `480`. What is the expected result?

There needs to be a clear distinction between _resizing_ and selecting _only part_ of the original frame - which does not appear to be be possible using any of the specified constaints.

**Comment by guest271314** [comment]
Note also, relevant to dynamic input of _variable_ `width` and `height` frames that are intended to be displayed at an `HTMLVideoElement` and, or streamed to a different peer using `RTCPeerConnection` it might be necessary to await `resize` event of `<video>` element before transmitting or recording the frame to avoid displaying a frame in between the previous frame dimensions and expected frame dimensions - resizing of the frame is not instantaneous and `MediaStreamTrack` does not have a `resize` event, and `unmute` event needs to be checked - particularly at Chromium and particularly when replacing a track in mid-stream

```
for (const blobURL of urls) {
        await new Promise(resolve => {
          videoStream.addEventListener("pause", async _ => {
            recorder.pause();
            resolve();
          }, {
            once: true
          });
          videoStream.addEventListener("canplay", async _ => {
            if (!recorder) {
              await new Promise(resizedPromise => {
                const handleResize = async _ => {
                  const {
                    width, height
                  } = ms.getVideoTracks()[0].getSettings();
                  console.log(video.width, width);
                  if (video.width === width && video.height === height) {
                    console.log(video.width, width);
                    video.removeEventListener("resize", handleResize);
                    await new Promise(unmutePromise => {
                      const [track] = mediaStream.getVideoTracks();
                      let now = performance.now();
                      console.log(video.currentTime, track.muted, stream.getVideoTracks()[0].muted, ms.getVideoTracks()[0].muted);
                      track.addEventListener("unmute", async _ => {
                        console.log(_.type, (performance.now() - now) / 1000, video.currentTime, video.width, video.videoWidth, track.getSettings().width);
                        unmutePromise(await videoStream.play());
                      }, {
                        once: true
                      })
                    });
                    recorder = new MediaRecorder(stream, {
                      mimeType: "video/x-matroska;codecs=h264"
                    });
                    recorder.onstart = _ => {
                      console.log(_.type);
                    }
                    result = new Promise(resolve => {
                      recorder.addEventListener("dataavailable", ({
                        data
                      }) => {
                        resolve(data);
                      }, {
                        once: true
                      })
                    });
                    recorder.start();
                    resizedPromise();
                  }
                }
                video.addEventListener("resize", handleResize);
              });
            } else {
              await videoStream.play();
              recorder.resume();
            }
          }, {
            once: true
          });
          videoStream.src = blobURL;
        });
      }
```

see https://plnkr.co/edit/Axkb8s?preview.

**Comment by jan-ivar** [comment]
Firefox is planning to add downscaling and decimating of framerates in response to constraints. This is [bug 1286945](https://bugzilla.mozilla.org/show_bug.cgi?id=1286945).

**Comment by guest271314** [comment]
> Currently, some browsers will not produce a 160x160

Which browsers?

Chromium 87 and Nightly 83 both produce a 160x160 video.

```
navigator.mediaDevices.getUserMedia({video: true})
.then(async stream => {
  const video = document.createElement('video');
  document.body.appendChild(video);
  video.autoplay = true;
  video.srcObject = stream;
  const recorder = new MediaRecorder(stream);
  recorder.ondataavailable = ({data}) => console.log(URL.createObjectURL(data));
  recorder.start();
  setTimeout(async _ => {
    await stream.getVideoTracks()[0].applyConstraints({ width : 160, height : 160 });
    setTimeout(_ => recorder.stop(), 5000);
  }, 5000);
});
```

[chromium_87_apply_constraints_width_height.webm.zip](https://github.com/w3c/mediacapture-main/files/5277571/chromium_87_apply_constraints_width_height.webm.zip)
[nightly_83_apply_constraints_width_height.webm.zip](https://github.com/w3c/mediacapture-main/files/5277574/nightly_83_apply_constraints_width_height.webm.zip)

> It would be nice to get interoperability for width and height constraints amongst browsers.

> The incompatibility between Chrome and Firefox modes

While testing the claims made found that when two (2) different USB cameras are connected to the machine Chromium and Firefox select different devices as the default camera. That is definitely an interoperabilty and incompatibility issue.

**Comment by guest271314** [comment]
While further testing the claims made the OS froze. Before freezing `getSettings()` and `getConstraints()` logged `160` for `width and `height` after `applyConstraints()`.

Re-installing the OS and playing the videos from https://github.com/w3c/mediacapture-main/issues/723#issuecomment-698445978 at `mpv`

```
$ mpv nightly_83_apply_constraints_width_height.webm
 (+) Video --vid=1 (*) (vp8 640x480)
VO: [gpu] 640x480 yuv420p
V: 00:00:04 / 00:00:06 (77%)
VO: [gpu] 176x144 yuv420p
V: 00:00:10 / 00:00:10 (99%)


Exiting... (End of file)
```

```
$ mpv chromium_87_apply_constraints_width_height.webm
 (+) Video --vid=1 (*) (vp8 640x480)
VO: [gpu] 640x480 yuv420p
V: 00:00:04 / 00:00:06 (73%)
VO: [gpu] 240x240 yuv420p
V: 00:00:09 / 00:00:09 (99%)


Exiting... (End of file)
```

which means `getSettings()` and `getConstraints()` are not reporting accurate values; and  in fact the `MediaStreamTrack` is not being set to the constraints with `applyConstraints()`. Will continue testing.

**Comment by guest271314** [comment]
The closest have been able to get to 160x160 is 176x144 using any combination of constraints. 

To create a 160x160 `MediaStreamTrack` from original `MediaStreamTrack`, this can be done at Chromium, not at Firefox or Nightly, where `resizeHeight` and `resizeWidth` are not defined at `createImageBitmap()` and `ImageCapture` is not supported, and `OffscreenCanvas` is behind a flag and has implementation issues. Nonethess a workaround is till possible for Mozilla browsers


```
navigator.mediaDevices.getUserMedia({video: true})
.then(async stream => {
  const video = document.createElement('video');
  document.body.appendChild(video);
  video.autoplay = true;
  const [track] = stream.getVideoTracks();
  const {width, height} = track.getSettings();
  const canvas = document.createElement('canvas');
  const ctx = canvas.getContext('bitmaprenderer');
  const canvasStream = canvas.captureStream();
  const [canvasTrack] = canvasStream.getVideoTracks();
  video.srcObject = canvasStream;
  const imageCapture = new ImageCapture(track);
  console.log('before constraints:', track.getSettings(), await track.getConstraints());
  let controller;
  const rs = new ReadableStream({
    start(_) {return controller = _},
    async pull() {
      const frame = await imageCapture.grabFrame();
      const bitmap = await createImageBitmap(frame, 0, 0, width, height, 
                                 {resizeWidth: 160, resizeHeight: 160}
                               );
      controller.enqueue(bitmap);
      // adjust frame rate manually or dynamically here, e.g.,
      // await new Promise(resolve => setTimeout(resolve, 1000/30));
    }
  })
  .pipeTo(new WritableStream({
    write(bitmap, c) {
      ctx.transferFromImageBitmap(bitmap);
    }
  }));
  const recorder = new MediaRecorder(canvasStream);
  recorder.ondataavailable = ({data}) => console.log(URL.createObjectURL(data));
  recorder.start();
  setTimeout(async _ => {
    recorder.stop(); 
    controller.close();
    track.enabled = false; 
    canvasTrack.stop();  
  }, 10000);
});
```

**Comment by guest271314** [comment]
Re

> Currently, some browsers will not produce a 160x160

it is not clear if `getSettings()` and `getConstraints()` are returning the incorrect values or if `MediaRecorder` is not adjusting `width` and `height` to `160`, or both.

**Comment by guest271314** [comment]
Firefox version, where `ReadableStream.pipeTo()` is not supported and `requestFrame()` is still defined at `MediaStream` rather than `CanvasCaptureMediaStreamTrack`, to record 160x160 video from source `MediaStreamTrack`, the key parameters being the last two to `drawImage()`, from MDN https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage

> **dWidth** Optional
>     The width to draw the image in the destination canvas. This allows scaling of the drawn image. If not specified, the image is not scaled in width when drawn.
> **dHeight** Optional
>     The height to draw the image in the destination canvas. This allows scaling of the drawn image. If not specified, the image is not scaled in height when drawn.

```
navigator.mediaDevices.getUserMedia({video: true})
.then(async stream => {
  const video = document.createElement('video');
  document.body.appendChild(video);
  video.autoplay = true;
  const [track] = stream.getVideoTracks();
  const {width, height} = track.getSettings();
  const canvas = document.createElement('canvas');
  canvas.width = canvas.height = 160;
  document.body.appendChild(canvas);
  const ctx = canvas.getContext('2d');
  const canvasStream = canvas.captureStream(0);
  const [canvasTrack] = canvasStream.getVideoTracks();
  video.srcObject = stream;
  let controller;
  const rs = new ReadableStream({
    start(_) {return controller = _},
    async pull() {
      ctx.drawImage(video, 0, 0, video.videoWidth, video.videoHeight, 0, 0, 160, 160);
      canvasStream.requestFrame();
      controller.enqueue(null);
    }
  });
  const reader = rs.getReader();
  reader.read().then(async function processStream({value: bitmap, done}) {
    if (done) return;
    await new Promise(resolve => setTimeout(resolve, 1000/30));
    return reader.read().then(processStream);
  });

  const recorder = new MediaRecorder(canvasStream);
  recorder.ondataavailable = ({data}) => console.log(URL.createObjectURL(data));
  recorder.start();
  setTimeout(async _ => {
    recorder.stop(); 
    controller.close();
    track.enabled = false; 
    canvasTrack.stop();  
  }, 10000);
});
```

If gather the Issue correctly, this is how `applyConstraints()` should work, instead of reporting incorrect values and not throwing error or exception.
