### ISSUE TITLE
getUserMedia() from local files?

### ISSUE THREAD

**Issue by ShijunS** [w3c/mediacapture-main#73]
The current spec mentions that MediaStream object can be generated from a local file, and use the "local file" example in multiple places.  I’d suggest removing the “local file” scenario from the main spec.  It is undefined otherwise.  

The scenario can be addressed in a separate spec when indeed needed.  It seems that the new spec effort for getting Media Stream from the MediaElement will be able to address most of the need.

**Comment by alvestrand** [comment]
Closed because relevant text removed (we don't pull from files any more).
