### ISSUE TITLE
getSupportedConstraints is not prescribing any mandatory to implement constraints

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-main#732]
Looking at Chrome, Firefox and Safari, it seems some constraints are consistently supported: deviceId, echoCancellation, facingMode, frameRate, groupId, height, width.
Can we make these constraints mandatory to implement?

Note also that two constraints (latency and resizeMode) are only implemented by Chrome at the moment.

**Comment by jan-ivar** [comment]
Aren't they all mandatory to implement?

**Comment by jan-ivar** [comment]
I would argue they are based on the [webidl](https://w3c.github.io/mediacapture-main/getusermedia.html#dom-mediatracksupportedconstraints#idl-def-mediatracksupportedconstraints):
```js
dictionary MediaTrackSupportedConstraints {
  boolean width = true;
  boolean height = true;
  boolean aspectRatio = true;
  boolean frameRate = true;
  boolean facingMode = true;
  boolean resizeMode = true;
  boolean sampleRate = true;
  boolean sampleSize = true;
  boolean echoCancellation = true;
  boolean autoGainControl = true;
  boolean noiseSuppression = true;
  boolean latency = true;
  boolean channelCount = true;
  boolean deviceId = true;
  boolean groupId = true;
};
```

**Comment by youennf** [comment]
> Aren't they all mandatory to implement?

If they are all mandatory, we could probably remove getSupportedConstraints().
Feature detection could use navigator.mediaDevices or ImageCapture instead.

> I would argue they are based on the [webidl](https://w3c.github.io/mediacapture-main/getusermedia.html#idl-def-mediatracksupportedconstraints):

How is this WebIDL definition prescribing supporting these constraints?

**Comment by dontcallmedom** [comment]
The idea as I recall is that they are all mandatory, but the `getSupportedConstraints()` pattern allowed for adding new constraints over time while retaining feature detection.

**Comment by alvestrand** [comment]
The theory was that you wanted to know what constraints the browser would ignore because WebIDL removed it from the list, not what constraints the browser would do nothing special with because it didn't support the relevant action.

**Comment by youennf** [comment]
Closing since specs are clear enough or at least I am clear enough about the intent now.

**Comment by jan-ivar** [comment]
Everything in WebIDL is mandatory to implement.
