### ISSUE TITLE
Make fitness distance a SHOULD instead of MAY on device delection.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#735]
I think we should strengthen this to ensure web compat around constraints use in `getUserMedia`.

Sites are going to do things like:
```js
await navigator.mediaDevices.getUserMedia({video: {deviceId: deviceFromLastVisitId, height: 1080}});
```
...and expect comparable results across browsers (same device if available, or comparable 1080p cam if not).

I suspect implementations already comply, but right now this hinges on a **MAY** in the spec which seems too weak.

On the **MAY**: Firefox is the lone implementation to allow users to override the (ideal) device choice in its permission prompt, but I think that's a valid exception (if the user explicitly chose a device, the site should probably honor it!)

But that shouldn't stand in the way of improving web compat of the automated device selection process where the user does _not_ override.

So I'm proposing a **SHOULD** instead of **MAY** here, with a mention of _"user preference"_ as an example of a valid exception.

**Comment by guest271314** [comment]
> Sites are going to do things like:
> 
> ```js
> await navigator.mediaDevices.getUserMedia({video: {deviceId: deviceFromLastVisitId, height: 1080}});
> ```
> 
> ...and expect comparable results across browsers (same device if available, or comparable 1080p cam if not).

Well, that expectation would be misplaced. Currently there is zero consistency with regard to browsers and video device selection: Firefox and Chromium proffer different devices as default https://github.com/w3c/mediacapture-main/issues/727. 

Chromium does not support capture of monitor devices and uses the label `"audiooutput"` when in fact that is the exact same device as the microphone, and neither this specification nor Audio Output Devices API actually define capture of headphones or speakers. 

"SHOULD" is still not strong enough for these billigerent implementers. Am skeptical that "MUST" is even strong enough language, yet with "MUST" there is no ambiguity with regard to intent of the authors.
