### ISSUE TITLE
MediaStream: 'input", "output", and number of "consumers"

### ISSUE THREAD

**Issue by ShijunS** [w3c/mediacapture-main#75]
[Section 4.1] has the following, "A MediaStream object has an input and an output that represent the combined input and output of all the object's tracks. The output of the MediaStream controls how the object is rendered".

First, the “input” and “output” concepts are not defined explicitly.  They are not part of the MediaStream object directly.  

Secondly, the consumer should be the object that controls the rendering not the "output".  

More important, the spec should be explicit if a MediaStream object can be assigned to more than one consumers simultaneously.  The block diagrams in this section currently shows 2 "outputs".

**Comment by stefhak** [comment]
Text clarifying needed.

**Comment by dontcallmedom** [comment]
I think the clarification was already brought in via https://github.com/w3c/mediacapture-main/commit/55d8d7220f167941cfd8740ecc6b3f183a8ab0d9

**Comment by stefhak** [comment]
You're right Dom, closing again.
