### ISSUE TITLE
Editorial: "muted" attribute refers to itself

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-main#754]
The "muted" attribute

https://w3c.github.io/mediacapture-main/getusermedia.html#dom-mediastreamtrack-muted

points to itself for the definition of "muted".

It should probably have pointed to one of:
* https://w3c.github.io/mediacapture-main/getusermedia.html#life-cycle-and-media-flow
* https://w3c.github.io/mediacapture-main/getusermedia.html#track-muted

**Comment by dontcallmedom** [comment]
#743 addresses this (among other things)
