### ISSUE TITLE
resizeMode: "none" should imply native frame rates

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#762]
The one part we missed is I think `resizeMode: "none"` doesn't make a lot of sense if it doesn't also yield native frame rates, which is what Firefox does.

I propose we just specify this. Apps that want a mix (e.g. native res + decimated framerate) can achieve this with two `applyConsteaints` calls: essentially locating the native mode first,  then applying the non-native constraint second.

**Comment by youennf** [comment]
> resizeMode: "none"

I understand the desire to patch the current API in the least invasive way.
That said, resizeMode, by its name and its values (crop-and-scale) is clearly meant to resolution, not frame rate.
It seems cleaner to add a separate nativeFrameRate.

> Apps that want a mix (e.g. native res + decimated framerate) can achieve this with two `applyConsteaints` calls

I think we want to avoid this, given the desire to be able to do the camera setup in one single call.
nativeFrameRate would solve this.

There have also been talks in the past to add further values to resizeMode.
Adding frame rate into the mix might make this more difficult.

**Comment by jan-ivar** [comment]
> resizeMode, by its name and its values (crop-and-scale) is clearly meant to resolution, not frame rate.

I agree about the name, but that seems superficial compared to its intended use and history.

`resizeMode` was introduced as a compromise between Firefox's spec-intent-driven _discovery_ model of discrete modes (`"none"`) and Chrome's _opaque_ yet admittedly more useful auto-adapt interpretation (`"crop-and-scale"`). We couldn't agree on a default between the two browsers, so we didn't, and defined a new constraint instead, so apps could pick.

But I think we failed to recognize that the difference between those models (discovery vs opaque) runs deeper, affecting the triumvirate of tradeoffs that traditionally make up "modes" in the first place in cameras: `width`, `height` and `frameRate`.

This is evident in two ways:
 1. It's possible today to discover/polyfill native presets for width, height and frameRate in Firefox but only width and height in Chrome.
 2. Apps can pick native width, height and frameRate using `advanced` in Firefox, but not Chrome:
    ```js
    await getUserMedia({video: {width: 640, height: 480, advanced: [
      {resizeMode: "none"},
      {width: 1280, height: 768, frameRate: 5},
      {width: 1280, height: 768, frameRate: 15},
      {width: 640, height: 480, frameRate: 60},
    ]}});
    ```
With my Logitech, this might yield 1280x1024x15 native in Firefox, but 1280x758x5 decimated in Chrome.
With my built-in cam, this might yield 640x480x60 native in Firefox, but 1280x768x5 decimated in Chrome.

Adding a new constraint would not solve this. Assuming usage of `advanced` in combination with `resizeMode: "none"` is low (which I think it is), I'd rather we fix this in the algorithm to be cross-browser compatible while we can.

**Comment by jan-ivar** [comment]
> It's possible today to discover/polyfill native presets for width, height and frameRate in Firefox

This is an obstacle to Firefox adding frame decimation, because once we add settings dictionaries for those interpolated modes into the pool, Firefox will either have to stop letting apps discover native frame rates, or stop being spec-compliant.

**Comment by alvestrand** [comment]
I don't understand the initial "two applyConstraints calls" comment - are you suggesting:

track.applyConstraints({resizeMode: "none", width: 1280, height: 768}) => pick HD with native frame rate
settings = track.getSettings()
applyConstraints({resizeMode: "crop-and-scale", width: {exact: settings.width}, height: {exact: settings.height}, frameRate=5});

that is - you have to change the resize mode (and therefore be precise about the width and height) if you want decimation,
or are you suggesting something else?

**Comment by jan-ivar** [comment]
@alvestrand Yes, I'm making the point that if someone for some reason wants native res + decimated framerates it is achievable that way, which means we don't need a new `nativeFrameRate` constraint.
