### ISSUE TITLE
Aren't not understood constraints ignored?

### ISSUE THREAD

**Issue by stefhak** [w3c/mediacapture-main#78]
In section 10.2.1 it is said:
"If the constraint is not supported by the browser, jump to the step labeled Constraint Failure below."
I may be confused, but isn't the situation now that constraints the browser does not support/understand are just ignored?

**Comment by dontcallmedom** [comment]
with the new algorithm for applyConstraints, I think this is moot

**Comment by stefhak** [comment]
Agreed (it is said that "unknown properties are discarded by WebIDL, which means that unknown/unsupported required constraints will silently disappear"). Closing.
