### ISSUE TITLE
Allow enumerateDevices() to again return audiooutput devices exposed via `selectAudioOutput()` even when "device information can be exposed" is false

### ISSUE THREAD

**Issue by karlt** [w3c/mediacapture-main#800]
This was achieved by https://github.com/w3c/mediacapture-main/issues/703, but regressed unintentionally as of https://github.com/w3c/mediacapture-main/pull/721

"Device information can be exposed" represents microphones and cameras and so should not always be required for exposure of speakers.

**Comment by youennf** [comment]
Thanks for the report @karlt, I uploaded https://github.com/w3c/mediacapture-main/pull/801.
Could you take a look?
