### ISSUE TITLE
MediaStreamTrack frame rate: configured versus actual?

### ISSUE THREAD

**Issue by henbos** [w3c/mediacapture-main#826]
MediaStreamTrack.getSettings().frameRate is either an exact frame rate or a frame rate range.

> The exact frame rate (frames per second) or frame rate range. If video source's pre-set can determine frame rate values, the range, as a capacity, should span the video source's pre-set frame rate values with min being equal to 0 and max being the largest frame rate. The User Agent MUST support frame rates obtained from integral decimation of the native resolution frame rate. If this frame rate cannot be determined (e.g. the source does not natively provide a frame rate, or the frame rate cannot be determined from the source stream), then this value MUST refer to the User Agent's vsync display rate.

I don't find it very clear if this is current frame rate - which could vary depending on lighting conditions etc - or configured frame rate. E.g. let's say the camera was opened in 30 fps but the actual frame rate is ~22. What is reported?

I believe that Chromium is implemented as follows:

> If we do frame decimation we report a measured frame rate, and if we don't, we report the frame rate the camera is configured with.

Issues:
1. Do we need to clarify what frameRate should be reported?
2. Both the actual and configured frame rates are useful pieces of information - do we need two APIs?

**Comment by henbos** [comment]
Ping. Is this something we want to fix? :) What does other browsers do? @jan-ivar @youennf

**Comment by henbos** [comment]
Filed two sub-issues, one here on mediacapture-main to tweak/clarify the existing setting (https://github.com/w3c/mediacapture-main/issues/906) and one on mediacapture-extension to propose two new attributes (https://github.com/w3c/mediacapture-extensions/issues/76).

**Comment by youennf** [comment]
actual frame rate may change a lot, and need some averaging anyway. Settings does not seem the best place.
Given this can be computed by web apps using mediacapture-transform, do we need to expose it?

**Comment by henbos** [comment]
I don't think applying a transformation should be required to obtain a frame rate. Besides, I want both the FPS achieved and the FPS of dropped frames and for that we need a new API. Adding framesDropped without also adding framesEmitted seems incomplete.

**Comment by henbos** [comment]
What I propose are total counters, let the app worry about averaging.

**Comment by youennf** [comment]
We also have rvfc which covers actual frame rate computation as well.

**Comment by henbos** [comment]
Use case is diagnosing why we are not getting the FPS of the settings.
- Are they never produced by the camera (actual less than setting, but no drops)?
- Are they produced but dropped by the browser pipeline so they never reach their destination?

Lastly you have potential frame drops at the destination, but I believe that is covered by other APIs. E.g. the destination could be an RTCPeerConnection (we have getStats) or it could be some application defined processing step. A processing step could know how many frames it received as input, but could not know if it did not receive more frames due to camera not producing them or due to them being dropped somewhere.

We've seen several issues of browser buffer pools being exceeded and frames getting dropped which is very different than "the camera isn't producing any frames"

**Comment by henbos** [comment]
The camera not producing any frames is not actionable, but could be explained by the user.
The camera producing frames but frames getting dropped could be a sign that the processing pipeline is not able to keep up or it could be a sign of a browser bug.

**Comment by henbos** [comment]
RVFC is useful for render FPS of a tag. Capture FPS != render FPS != encoder FPS.
The track should be able to speak for itself, we shouldn't need to attach it to a video tag or attach it to a peer connection to try to measure what FPS is later in the pipeline in order to guesstimate what the camera is capturing at (which would be inaccurate if drops occur).

**Comment by dontcallmedom** [comment]
with the 2 sub-issues https://github.com/w3c/mediacapture-main/issues/906 and https://github.com/w3c/mediacapture-extensions/issues/76 closed, is there any reason to leave this issue open?

**Comment by henbos** [comment]
No let's close this since we've already covered actual versus configured frame counters with video `track.stats`.
