### ISSUE TITLE
Add documentation to when firing muted/unmuted events

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-main#837]
There are scenarios where muted/unmuted events should be fired and it would be good to document these.
One such use case is for OSes where microphone access may get stolen from an application.
This is the case on Android and iOS when a page is capturing microphone, a phone call happens and page will no longer receive microphone samples.

**Comment by eladalon1983** [comment]
**nit, pre-existing but touched by this commit:**

Where the document says:
> Muted is out of control for the web application

I suspect it means one of these:
> Muted is outside the control of Web applications
> Web applications cannot control muted
> Muted it beyond Web applications to control

Or something similar.

"X is out of control" puts me in mind of "X has gone wild."

**Comment by youennf** [comment]
> Muted is outside the control of Web applications

This phrasing reads better to me but I am no native speaker.
Seems worth a PR.

**Comment by eladalon1983** [comment]
> Seems worth a PR.

#840

**Comment by youennf** [comment]
Closed by PR 838 and PR 840
