### ISSUE TITLE
devicechange should fire when enumerateDevices works

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#842]
[enumerateDevices()](https://w3c.github.io/mediacapture-main/getusermedia.html#dom-mediadevices-enumeratedevices) says the _"User Agent MAY wait to proceed to the next step until document is fully active and has focus"_, but [devicechange](https://w3c.github.io/mediacapture-main/getusermedia.html#dfn-device-change-notification-steps) doesn't.

The point of the event is to alert JS to call enumerateDevices, so firing it when the method will just block seems pointless.

Moving the _MAY_ into the [device enumeration can proceed](https://w3c.github.io/mediacapture-main/getusermedia.html#device-enumeration-can-proceed) algorithm should fix this.

**Comment by tonyherre** [comment]
As currently written, the devicechange event steps MUST only happen when device enumeration can proceed, so the current behaviour is that events are only fired for active & focussed pages, but moving the "MAY wait" into "device enumeration can proceed" would mean events are now fired on focus.
Sounds like a better way to me, but is this what you intended?

**Comment by alvestrand** [comment]
The interesting version of devicechange with backgrounded tabs is if someone unplugs his headset while the tab is backgrounded, and expects sound to automagically switch to speakers without having to foreground the tab first.

**Comment by jan-ivar** [comment]
> As currently written, the devicechange event steps MUST only happen when [device enumeration can proceed](https://w3c.github.io/mediacapture-main/getusermedia.html#device-enumeration-can-proceed), so the current behaviour is that events are only fired for active & focussed pages

@tonyherre Not quite. That algorithm returns true if [device information can be exposed](https://w3c.github.io/mediacapture-main/getusermedia.html#device-information-can-be-exposed), which is effectively [[[canExposeCameraInfo]]](https://w3c.github.io/mediacapture-main/getusermedia.html#dfn-canexposecamerainfo) || [[[canExposeMicrophoneInfo]]](https://w3c.github.io/mediacapture-main/getusermedia.html#dfn-canexposemicrophoneinfo), which get set to true on gUM success.

I.e. the spec mandates firing the event on background tabs that have called gUM successfully at least once since opened.

As mentioned in the OP, it's only enumerateDevices that has an additional _"MAY ... wait ... until ... focus"_. We'd like to fix this.

> ... moving the "MAY wait" into "device enumeration can proceed" would mean events are now fired on focus.

This is [already required](https://w3c.github.io/mediacapture-main/getusermedia.html#dfn-device-change-notification-steps): _"Additionally, if a MediaDevices object that was traversed comes to meet the device enumeration can proceed criteria later (e.g. gains focus), the User Agent MUST execute the device change notification steps ... at that time."_

**Comment by jan-ivar** [comment]
> The interesting version of devicechange with backgrounded tabs is if someone unplugs his headset while the tab is backgrounded, and expects sound to automagically switch to speakers without having to foreground the tab first.

@alvestrand good observation. But that problem seems unique to `"audiooutput"` devices, so we could say user agents MUST fire the `devicechange` event on background tabs (only) in that specific situation. @youennf WDYT?

How to write that though is another matter.

**Comment by youennf** [comment]
On audioouptut device removal, audio is paused, as per spec:
`When the audio device identified by the sinkId attribute is no longer available, the user agent must take no action`

In that situation, it is as if we try starting playing audio from a background page. I am not sure we actually want this.
In any case, this seems worth filing an issue in https://github.com/w3c/mediacapture-output.

As a side note, we could also separate the case of exposing all device information on a background page, from exposing on that same background page the information that a specific device that a user granted is now inactive.
MediaDeviceInfo could be a place where we could expose the latter information.

**Comment by jan-ivar** [comment]
> if someone unplugs his headset while the tab is backgrounded

I've filed https://github.com/w3c/mediacapture-output/issues/129 on that. That issue shouldn't block this one which is about aligning devicechange with enumerateDevices. If a user agent MAY defer enumerateDevices it makes sense to defer devicechange as well.
