### ISSUE TITLE
Raising a concern regarding community members.

### ISSUE THREAD

**Issue by Franklin5EN** [w3c/mediacapture-main#845]
Dom and members,

As a member here, I have very serious concerns regarding this that could legally disrail the whole project.

I would rather do this in private or get the ICO involved.

I've had a horrid time getting in with community members intercepting my login via boiler-plating. Please advise the security members to halt immediately via a companion device session.

**Comment by alvestrand** [comment]
If you have a problem that might have legal implications, please contact W3C staff.
This class of concern is not something that should be handled via Github spec bugs.
