### ISSUE TITLE
Identify if a device listed in MediaDevices.enumerateDevices() is virtual

### ISSUE THREAD

**Issue by satri85** [w3c/mediacapture-main#895]
For legal requirements in some streaming services it is mandatory that the video and audio captured come from real physical devices on the user device. 
The https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo does not identify virtual devices.

Is it possible to add the functionality to identify virtual devices?

**Comment by bradisbell** [comment]
Related: https://github.com/w3c/mediacapture-main/issues/896
