### ISSUE TITLE
Device enumeration spec-ed to hang

### ISSUE THREAD

**Issue by eladalon1983** [w3c/mediacapture-main#903]
> 2. The [User Agent ](https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/900/e84ad3e...youennf:c5e716a.html#dfn-user-agent)MUST wait to proceed to the next step until [device enumeration can proceed ](https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/900/e84ad3e...youennf:c5e716a.html#device-enumeration-can-proceed)is true .

But the `device enumeration can proceed` check can return false, in which case... we should hang indefinitely? This does not seem to match the implementation in Chromium, Safari or Firefox. It also seems unreasonable. Am I misreading this?

**Comment by karlt** [comment]
This is a parallel step, so the browser doesn't hang.  The promise is just not settled yet.

Firefox waits until "the relevant global object's associated Document is fully active" and [the browser window has OS-level focus](https://github.com/w3c/mediacapture-main/issues/752).

**Comment by eladalon1983** [comment]
Not settling the promise means the following code would "hang", in that it never continues execution past `await`:
```js
const devices = await navigator.mediaDevices.enumerateDevices();
doUsefulThings(devices);
```

No implementation I aware of actually follows this algorithm. The promise is settled in all of them.

**Comment by alvestrand** [comment]
Seems like we need to have an UMA to figure out whether this anti-tracking feature will break websites.

**Comment by jan-ivar** [comment]
Firefox implemented this [a year ago](https://bugzil.la/1732410).

Not continuing execution past `await` is not a "hang", so there is no issue here, nor is this new information to reopen our previous decision. I suggest closing it.

**Comment by youennf** [comment]
I filed https://bugs.webkit.org/show_bug.cgi?id=245864 to keep track of this work in WebKit.

**Comment by alvestrand** [comment]
Substantive discussion seems to be occuring in #905. Closing this as a duplicate thread.
