### ISSUE TITLE
EnumerateDevices() Returns Multiple GroupId for Bluetooth Devices on Windows

### ISSUE THREAD

**Issue by jsoon049** [w3c/mediacapture-main#904]
Hi there! I am using the enumerateDevices() to list out all possible audio output devices connected to a computer. One issue I am running into is that for Bluetooth devices, the method is returning different groupIds for the same device, thus returning duplicates. Normally I am using groupIds to filter duplicates but with this I am unable to do so. This seems to be a Windows specific issue as I do not see the same issue on Mac. Does anyone know as to why this occurs?

**Example1:**
kind: audiooutput,
label: Headset (Galaxy Buds (6198) Hands-Free AG Audio (Bluetooth),
deviceId: 5327a1673eb0a1cd2406c0d4e80282e0d8333a13fdae2b32d4b6eff7a15dad9c,
groupId: b53795e90cfa75533fbc841f2ce6ac0b5c0e6168b557b26f6dcac6eb59603e14

kind: audiooutput 
label: Headphones (Galaxy Buds (6198) Stereo) (Bluetooth),
deviceId: dab6333ff89aa24b09f3ef3dee7d29602487102d0109ce5e75a67455cb6d9622,
groupId: ee8cf03490a4282e4ed3ed43bc9993fd2715ed99bedc8f6c1677d9b5ac051f55"}

**Example2:**
kind: audiooutput
label: Headphones (PLT_BBFIT Stereo) (Bluetooth)
deviceId: b8202ed1f4cd532c7eecf7884dd6bf308da679cf0b8de71cca37b10c85a8d067
groupId: 3ac3eae253e0316db14023d3e3cf5ef29c3248a7298416697f0150c343c8e46f

kind: audiooutput
label: Headset (PLT_BBFIT Hands-Free AG Audio) (Bluetooth)
deviceId: f519cfc7a947f619e5290f993e19419dd744546ae720e7465aa565830340e511 
groupId: 3959b1c75f29dc542c80b0fc8d017bee59709251f18ffe82fbda104417ae2050

**Comment by guidou** [comment]
That would be a chromium bug, not a spec problem. Please file a bug at crbug.com.
