### ISSUE TITLE
MediaStreamTrack.getSettings().frameRate should reflect configured rate, not actual

### ISSUE THREAD

**Issue by henbos** [w3c/mediacapture-main#906]
Sub-issue of #826.

Problem: As explained in #826, some implementations are inconsistent in whether frameRate is a setting or a measurement.

Proposal: Both the setting and the actual is of interest, but getSettings() sometimes not returning a setting is just confusing. Let's clarify it is the setting. In other words:
- If the camera/source is configured for 30 fps, settings.frameRate should say 30, even if the camera is only able to produce 20 fps.
- If the source is configured to do frame decimation to 25 fps, settings.frameRate should say 25, even if the camera is only able to produce 20 fps.

**Comment by henbos** [comment]
To answer the question of what the actual fps is, see https://github.com/w3c/mediacapture-extensions/issues/76

**Comment by dogben** [comment]
This proposal seems to conflict with the definitions for settings in https://w3c.github.io/mediacapture-transform/#generator-constrainable-properties related to VideoTrackGenerator.

**Comment by henbos** [comment]
Interesting, I didn't know that. But for GUM tracks there is a definite setting and we do want to expose it. For a generated track though, any setting is an implementation detail.

I'm also [trying to add frame counters to MediaStreamTrack](https://github.com/w3c/mediacapture-extensions/pull/77/files) because I recognize both the setting and the measurement is of interest, but I think it would be a mistake to use the same API to mean different things in different contexts.

**Comment by dogben** [comment]
@alvestrand, do you have an opinion? Should https://w3c.github.io/mediacapture-transform/ be changed to say that getSettings() returns only values where constraints have been set?

**Comment by henbos** [comment]
It turns out that what I am trying to clarify [was already clarified back in 2018](https://github.com/w3c/mediacapture-main/pull/512) so while mistaking getSettings() for returning measurements rather than settings keeps happening, arguably my PR is [not even needed because the spec already says this](https://github.com/w3c/mediacapture-main/pull/908#issuecomment-1276501501).
