### ISSUE TITLE
When device is in use, enumerateDevices() does not show alternatives

### ISSUE THREAD

**Issue by ma1hman** [w3c/mediacapture-main#911]
I am using GetUserMedia to show available webcams and mics for a video capture tool. This works fine when no devices are in use. For the first time, user is prompted to gain access to camera / mic and then all devices are shown for video and audio. But if that user has forgotten to close Teams or Zoom and goes to view devices, none are shown. I would think that the unused devices would be available. This is the current code I'm using:

```js
navigator.mediaDevices.getUserMedia({audio: true, video: true})
         .then((stream) => {
            navigator.mediaDevices.enumerateDevices().then((devices) => {
                 devices.forEach((device) => {
                    if (device.kind === "videoinput") {
                        addItemToList("video-devices", device.label, device.deviceId);
                    } else if (device.kind === "audioinput") {
                        addItemToList("audio-devices", device.label, device.deviceId);
                    }
                 });
               stream.getTracks().forEach(x => x.stop());
            });
        });
```
The addItemToList() is just a function to add these to drop down menu to choose before beginning capture. 

Any insight in how to adjust this so that if a device is in use, alternatives are pulled. 

Thanks in advance,
Jason

**Comment by jan-ivar** [comment]
Hi ma1hman! Sounds like you're having an issue with a specific browser or have a coding question?

Unfortunately, this issue tracker is for requesting changes to the specification, so I'm going to have to close this.

FWIW, I don't see anything wrong with the code you present. You might want to check out the [WebRTC samples](https://webrtc.github.io/samples/src/content/devices/input-output/) to determine if this is a browser issue or not.

For code help, I recommend https://stackoverflow.com/questions/tagged/getusermedia (feel free to [ping me](https://stackoverflow.com/users/918910/jib) there).
