### ISSUE TITLE
Check if we use "Browsing Context" in our specs

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-main#913]
With the rewrite done in https://github.com/whatwg/html/pull/6315 it seems that HTML5 has abandoned the concept of "browsing context", introducing instead "navigable" and more.

We should check if we use that concept anywhere.

**Comment by dontcallmedom** [comment]
we use "nested browsing context", which has disappeared from the HTML spec (and thus generates a ReSpec error at the moment); if I read https://github.com/whatwg/html/pull/8462 correctly, it looks like it should be replaced with "child navigable" cc @jan-ivar

**Comment by jan-ivar** [comment]
I fixed the ReSpec error in https://github.com/w3c/mediacapture-main/pull/912 to unblock merge.

I count 11 other uses of "browsing context" though, that I think need updating. It seems we mean navigable sometimes, and other times Document.
