### ISSUE TITLE
Settings are signed while constraints are unsigned

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#944]
All integer [MediaTrackSettings](https://w3c.github.io/mediacapture-main/#media-track-settings) are still signed, in spite of this spec only defining [ConstrainULong](https://w3c.github.io/mediacapture-main/#dom-constrainulong) since https://github.com/w3c/mediacapture-main/pull/515:

<img width="779" alt="image" src="https://user-images.githubusercontent.com/3136226/227966501-79b4ee0f-ae2f-4c91-96b1-b4040052b0cb.png">

Since these are only returned to JS, never taken as input, it should hopefully be web compatible to update them to unsigned.

**Comment by guidou** [comment]
All browsers define these as signed.
If anything, I think we should change the spec to use signed for constraints, since that is was all implementations use.

I think the bar for changes that make all implementations noncompliant should be high.
