### ISSUE TITLE
ability to pass metadata on add track [Feature Request]

### ISSUE THREAD

**Issue by JSmithOner** [w3c/mediacapture-main#952]
This would be nice to be able to pass in metadata per track.
example:

`  peer.addTrack( track, streams, metadata );`

where the prototype of `params` could look like this in TypeScript:

```
interface RTCTrackMetadata {
  [ key:string ]:string|number
}

```

then retrieve on end

```
peer.ontrack = ( event ) => {

  console.log( event.metadata );

}
```

Would this be possible?

**Comment by fippo** [comment]
(this belongs more to webrtc-pc)

Since this would have to be serialized in SDP it would require an extension to that format which is... hard to justify.
The general approach to solving this is to associate the metadata with the stream id and pass it along with the offer/answer at application level.

**Comment by JSmithOner** [comment]
Thank you for your answer.Even if that looks hard to justify in a technical point of view, I keep seeing partially resolved answers on SO of people facing similar issues, from a user experience point of view I feel like webrtc lacks a mechanism of this kind because what the point of sending data you can hardly identify, this limits the possibilities of the technology and push people to use hacky workarounds.Feel free to share your thoughs about this...Best

**Comment by fippo** [comment]
WebRTC as an API does exactly what it is supposed to - let the application solve the problem. There is nothing "hacky" about this, APIs building on top of WebRTC can provide such a feature.

**Comment by JSmithOner** [comment]
@fippo 
thank you for your answer
