### ISSUE TITLE
Can devicechange fire prior to enumerateDevices?

### ISSUE THREAD

**Issue by fippo** [w3c/mediacapture-main#956]
I'm looking at a [Chrome bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=1403403) and noticed I dislike the current behavior from a privacy point of view.

Does `devicechange` fire if the application never called `enumerateDevices`?
The argument for "no" is "you don't know what devices were available so why do you care about changes". It also means we have two vectors leaking device information instead of being able to focus on enumerateDevices (which is [a big mess](https://chromestatus.com/metrics/feature/timeline/popularity/1119))

Firefox doesn't seem to fire devicechange prior to enumerateDevices from what I can see (@jan-ivar to confirm)

**Comment by youennf** [comment]
> Does `devicechange` fire if the application never called `enumerateDevices`?

As per spec, I think so. For both APIs, the privacy protection is based on getUserMedia being called successfully.
Testing implementations, it seems that both Safari and Firefox are firing the devicechange event if getUserMedia is called but not enumerateDevices.
This might be somehow handy to know that the user's setup changed to offer some dedicated UI to the user although I agree the web page should probably call enumerateDevices beforehand to actually understand whether a device was added or removed

I am not sure what would be the privacy benefits for further restricting devicechange events, I would expect fingerprinters to call enumerateDevices anyway. One potential case would be setups that go from zero camera to one camera, but again, fingerprinters will call enumerateDevices.

**Comment by jan-ivar** [comment]
Closing this as answered.

> Testing implementations, it seems that both Safari and Firefox are firing the devicechange event if getUserMedia is called but not enumerateDevices.

Note that Firefox, Chrome, and the [spec](https://w3c.github.io/mediacapture-main/#ref-for-creating-a-list-of-device-info-objects-1) also fire the devicechange event ahead of getUserMedia() in the case where the number of cameras or microphones transition to or from zero ([try it](https://jan-ivar.github.io/dummy/enumerate.html)). 

This may not be apparent on devices that have camera and microphone built in (I was unable to test Safari for this reason).
