### ISSUE TITLE
Reconsider the text on streaming from a file

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-main#96]
This:

> When a MediaStream object is being generated from a local file (as opposed to a live audio/video source), the user agent SHOULD stream the data from the file in real time, rather than sending the entire file immediately. The MediaStream object is also used in contexts outside getUserMedia, such as [WEBRTC10]. In both cases, ensuring a realtime stream reduces the ease with which pages can distinguish live video from pre-recorded video, which can help protect the user's privacy.

Is not especially actionable without more specification guidance about what it means to stream from a file.  It is also unclear what the purpose of this paragraph is: to establish the potential for a file-based input device, or to describe a way to provide a fake device for the purposes of privacy.  Either is grossly under-specified.

I'd recommend removing this paragraph entirely.  Implementations that care to spoof gUM for the purposes of protecting privacy know how to do that and we have other specifications coming for producing content from "files" if that is the goal.

Note also that spoofing for privacy purposes needs to also generate appropriate device information to provide when devices are enumerated.  That information will need to match up with the actual content that is chosen.  That suggests that there could be a need to preempt the desire to spoof to ensure that it is even possible to do a believable job at it.

**Comment by alvestrand** [comment]
Closed because relevant text removed.
