### ISSUE TITLE
Transformation of camera signal into displayed frames on screen in a video capture pipeline.

### ISSUE THREAD

**Issue by abdikaiym01** [w3c/mediacapture-main#981]
Does the browser introduce additional compression resulting in loss in the final frame displayed on the screen from the webcam, or does it primarily involve format transitions (e.g., YUV to RGB) without compression or losses?
In such a context getUserMedia(...) -> HTMLMediaElement

**Comment by jan-ivar** [comment]
Closing as this sounds like an implementation question, whereas this repo is about questions around the specification of the API.

In short you'd have to ask each browser vendor what they do, though I suspect the answer from most is: no, why would they add additional compression apart from format transitions?

However, that doesn't mean you'll get full resolution by default, as this [spec note](https://w3c.github.io/mediacapture-main/#h-note-23).

You can interrogate and select resolution and frame rates using constraints. E.g. https://jsfiddle.net/jib1/3kvb7j9o/show
