### ISSUE TITLE
The [=muted=] concept is exported wrongly

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-main#985]
As per comments in https://github.com/w3c/mediasession/pull/313 by @marcoscaceres, we probably want to fix how we export the muted concept in media capture-main to:

```<dfn class="export" for="MediaStreamTrack">muted state</dfn>```

The same apparently applies for the set MediaStreamTrack muted state algorithm.

**Comment by jan-ivar** [comment]
I couldn't find any examples of `for=` so I used `data-dfn-for=` which seemed the closest.
