### ISSUE TITLE
(webkit|moz)getUserMedia usage and webcompat issues

### ISSUE THREAD

**Issue by karlcow** [w3c/mediacapture-main#992]
On [navigator.getUserMedia still creates webcompat issues](https://github.com/whatwg/compat/issues/266), I was trying to understand what is the current state of implementations.

| API | WebKit | Gecko | Blink |
|-|-|-|-|
| `navigator.getUserMedia`| `undefined` | `undefined` | ✅ |
| `navigator.webkitGetUserMedia`| `undefined` | `undefined`  | ✅ |
| `navigator.mozGetUserMedia`| `undefined` | ✅  | `undefined` |
| `navigator.mediaDevices.getUserMedia`| ✅ | ✅  | ✅ |

Some bugs have been opened for Gecko and Blink to deprecate/remove the prefixed version of `navigator.getUserMedia`

* Gecko [Deprecate navigator.mozGetUserMedia()](https://bugzilla.mozilla.org/show_bug.cgi?id=1609254). It didn't happen yet.
* Blink [Remove navigator.webkitGetUserMedia](https://issues.chromium.org/issues/40506759), [Deprecate navigator.getUserMedia()](https://issues.chromium.org/issues/40225258)
* seeAlso [WPT for not supporting it](https://github.com/web-platform-tests/wpt/pull/44909/files)

WebKit is getting breakage because of code like 

```js
navigator.getUserMedia =
  navigator.getUserMedia ||
  navigator.webkitGetUserMedia ||
  navigator.mozGetUserMedia ||
  navigator.msGetUserMedia;
```

Trying to explore further the implementation history around WebKit

* Apr 2011: [Media Stream API: add the getUserMedia method and the Javascript bindings](https://bugs.webkit.org/show_bug.cgi?id=56586). This was adding in fact `navigator.webkitGetUserMedia`
* Some back and forth for implementing, adjustment to match spec changes.
* Apr 2015: Support for [`navigator.mediaDevices.getUserMedia()`](https://bugs.webkit.org/show_bug.cgi?id=143255)
* Jun 2016: [getUserMedia() exposed, but not functional](https://bugs.webkit.org/show_bug.cgi?id=158393)
* **Feb 9, 2017**:[[MediaStream] Remove legacy Navigator.webkitGetUserMedia](https://bugs.webkit.org/show_bug.cgi?id=168016)
* **Feb 14, 2017**: [[MediaStream] add navigator.getUserMedia for compatibility with legacy content](https://bugs.webkit.org/show_bug.cgi?id=168324)
* **Aug 2018**: [Remove WebRTC legacy API implementation](https://bugs.webkit.org/show_bug.cgi?id=189040)
* Mar 2020: [navigator.getUserMedia is not available in WKWebView iOS 13.4 beta 4](https://bugs.webkit.org/show_bug.cgi?id=208788)

# Some questions

* What is the usage situation for Blink, Gecko on the prefixed versions?
* Is their will to remove them soonish? (and do site interventions at least for Gecko)
* Or was there attempt to remove that were reverted because of compat issues?

The [spec is currently saying](https://w3c.github.io/mediacapture-main/#legacy-getusermedia-interface):

> This decision reflected consensus as long as the original API remained available here under the Navigator object for backwards compatibility reasons, since the working group acknowledges that early users of these APIs have been encouraged to define getUserMedia as "var getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia;" in order for their code to be functional both before and after official implementations of getUserMedia() in popular browsers. To ensure functional equivalence, the getUserMedia() method here is defined in terms of the method under MediaDevices.

**Comment by fippo** [comment]
Code that does look for `msGetUserMedia` (which was not a thing in Edge Spartan even) is doing bad things that folks in the WebRTC space agreed were for ages ([2012](https://web.dev/articles/webrtc-basics?hl=en)) which led to adapter.js as something that does this kind of stuff in a more controlled fashion.

Usage for chromium is small but not zero: https://webrtchacks.github.io/chromestatus/?buckets=1401,1402
See also https://github.com/webrtcHacks/adapter/issues/764 (five years... oops)

**Comment by karlcow** [comment]
> See also https://github.com/webrtcHacks/adapter/issues/764 (five years... oops)

Oh nooooo… ! 😭

**Comment by karlcow** [comment]
> Usage for chromium is small but not zero: https://webrtchacks.github.io/chromestatus/?buckets=1401,1402

as of today around 0.008% of page loads. 
I wonder what is the opinion of @foolip on this.

**Comment by fippo** [comment]
That is still 4% of relative usage sadly. It isn't in video conferencing, the usage is pretty flat.

But good news, I think I figured out *why* people might be copy-pasting this:
  https://web.dev/articles/getusermedia-intro?hl=en
still mentions it... that should be fixable!

**Comment by eladalon1983** [comment]
@beaufortfrancois

**Comment by karlcow** [comment]
@samdutton would it be possible to change the article content on https://web.dev/articles/getusermedia-intro?hl=en
so that the code is using the more modern API call.

**Comment by beaufortfrancois** [comment]
I'll be happy to update https://web.dev/articles/getusermedia-intro. Please let me know which changes you'd like to make to the article.

**Comment by beaufortfrancois** [comment]
As discussed offline with @fippo, I'm in the process of updating https://web.dev/articles/getusermedia-intro.

**Comment by beaufortfrancois** [comment]
FYI https://web.dev/articles/getusermedia-intro has been updated.

**Comment by fippo** [comment]
https://github.com/webrtcHacks/adapter/issues/764 has been addressed by the newly published 9.0.0. How long that will take to get adopted...

**Comment by jan-ivar** [comment]
Firefox is blocked on essentially the same issue https://github.com/webrtcHacks/adapter/issues/1156.

**Comment by foolip** [comment]
Perhaps the spec should just spec these aliases conditional on https://html.spec.whatwg.org/multipage/system-state.html#concept-navigator-compatibility-mode?

**Comment by aboba** [comment]
Closing - not a spec issue.
